from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class TimeoutInjectorProtocol(Protocol):
    """Auto-inferred Protocol surface for `TimeoutInjector`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_staging/`.
    """

    async def inject(self) -> None: ...
