from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class LoadShedderProtocol(Protocol):
    """Auto-inferred Protocol surface for `LoadShedder`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    def record_latency(self, latency_ms: float) -> None: ...
    def get_p99(self) -> float: ...
    def is_shedding(self) -> bool: ...
    def get_tier(self) -> DegradationTier: ...
