from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class SagaProtocol(Protocol):
    """Auto-inferred Protocol surface for `Saga`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_staging/`.
    """

    @classmethod
    def collect_steps(cls) -> list[dict[str, Any]]: ...
