from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class LocalStorageBackendProtocol(Protocol):
    """Auto-inferred Protocol surface for `LocalStorageBackend`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    async def save(self, buf: BinaryIO, key: str, *, content_type: str) -> None: ...
    async def presigned_url(self, key: str, *, expires_in: int = 86400) -> str: ...
    async def delete(self, key: str) -> None: ...
