from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class RequestFingerprinterProtocol(Protocol):
    """Auto-inferred Protocol surface for `RequestFingerprinter`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    def compute(self, user_id: str | None, method: str, path: str, body: bytes | str) -> str: ...
