from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class DataSeederProtocol(Protocol):
    """Auto-inferred Protocol surface for `DataSeeder`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_staging/`.
    """

    async def seed(self, count: int = 10) -> dict[str, int]: ...
