from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class DeprecationRegistryProtocol(Protocol):
    """Auto-inferred Protocol surface for `DeprecationRegistry`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_staging/`.
    """

    def register(self, path: str, method: str, sunset: str, replacement: str, description: str = '') -> DeprecationEntry: ...
    def get(self, path: str, method: str) -> DeprecationEntry | None: ...
    def list_all(self) -> list[dict[str, Any]]: ...
