from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class RedactorProtocol(Protocol):
    """Auto-inferred Protocol surface for `Redactor`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_staging/`.
    """

    def __call__(self, logger: Any, method: str, event_dict: dict[str, Any]) -> dict[str, Any]: ...
