from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class BatchCoreProtocol(Protocol):
    """Auto-inferred Protocol surface for `BatchCore`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_staging/`.
    """

    async def run(self, items: list[Any], *, mode: IsolationMode, strategy: ProcessingStrategy, idempotency_keys: list[str] | None = None) -> list[BatchItemResult]: ...
