from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class DeliveryTrackerProtocol(Protocol):
    """Auto-inferred Protocol surface for `DeliveryTracker`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    async def track(self, *, message_id: str, event_type: str, recipient: str, provider: str) -> None: ...
    async def list_events(self, *, limit: int = 50, offset: int = 0) -> list: ...
