from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class DBQueryCostEstimatorProtocol(Protocol):
    """Auto-inferred Protocol surface for `DBQueryCostEstimator`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_staging/`.
    """

    def estimate(self, ctx: RequestContext) -> float: ...
