from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class SignatureHeaderProtocol(Protocol):
    """Auto-inferred Protocol surface for `SignatureHeader`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    def to_header_value(self) -> str: ...
