"""Prerequisite checker + auto-scaffolder for adapt tools.

Two modes:

**Check mode** — validates prerequisites, returns errors::

    errors = check_prerequisites(project_dir, Prereq.BASE_MODEL, ...)
    if errors:
        return ToolResult(status="error", error=..., notes=[...])

**Standalone mode** — auto-creates missing prerequisites so the tool
works on ANY FastAPI project, not just ones generated by the skill::

    created = scaffold_prerequisites(project_dir, Prereq.BASE_MODEL, ...)
    # created = ["app/models/base.py", "app/models/__init__.py"]
    # Now the tool can proceed — minimal scaffolding was created.

The auto-scaffolded files are minimal but functional: a Base class that
works with SQLAlchemy 2.0, a Settings class that reads env vars, an
empty models __init__, etc. They don't include full SKILL-001
conventions (no security headers, no middleware stack) — just enough
for the specific adapt tool to operate correctly.
"""

from __future__ import annotations

import textwrap
from enum import Enum
from pathlib import Path


class Prereq(str, Enum):
    """Prerequisites that adapt tools may require."""

    BASE_MODEL = "base_model"
    CONFIG_SETTINGS = "config_settings"
    ROUTES_INIT = "routes_init"
    MODELS_INIT = "models_init"
    AUTH_DEPS = "auth_deps"
    AUTH_SECURITY = "auth_security"
    SESSION_DEP = "session_dep"
    REQUIREMENTS_TXT = "requirements_txt"
    ALEMBIC_VERSIONS = "alembic_versions"


_CHECKS: dict[Prereq, tuple[str, str, str]] = {
    # (relative_path, content_marker, human_description)
    Prereq.BASE_MODEL: (
        "app/models/base.py",
        "class Base",
        "SQLAlchemy Base declarative class (app/models/base.py)",
    ),
    Prereq.CONFIG_SETTINGS: (
        "app/core/config.py",
        "class Settings",
        "Pydantic Settings class (app/core/config.py)",
    ),
    Prereq.ROUTES_INIT: (
        "app/routes/__init__.py",
        "api_router",
        "API router assembly (app/routes/__init__.py)",
    ),
    Prereq.MODELS_INIT: (
        "app/models/__init__.py",
        "import",
        "Model registration file (app/models/__init__.py)",
    ),
    Prereq.AUTH_DEPS: (
        "app/api/deps.py",
        "CurrentUser",
        "Auth dependencies with CurrentUser (app/api/deps.py)",
    ),
    Prereq.AUTH_SECURITY: (
        "app/core/security.py",
        "verify_password",
        "Password verification (app/core/security.py)",
    ),
    Prereq.SESSION_DEP: (
        "app/core/session.py",
        "get_session",
        "Database session dependency (app/core/session.py)",
    ),
    Prereq.REQUIREMENTS_TXT: (
        "requirements.txt",
        "",  # just needs to exist
        "Python dependencies file (requirements.txt)",
    ),
    Prereq.ALEMBIC_VERSIONS: (
        "alembic/versions",
        "",  # directory, not file
        "Alembic versions directory (alembic/versions/)",
    ),
}


def check_prerequisites(project_dir: str | Path, *prereqs: Prereq) -> list[str]:
    """Check that all required prerequisites are present in the project.

    Args:
        project_dir: Root of the FastAPI project.
        *prereqs: One or more ``Prereq`` enum values to check.

    Returns:
        List of human-readable error strings for missing prerequisites.
        Empty list means all prerequisites are satisfied.
    """
    errors: list[str] = []
    root = Path(project_dir)

    for prereq in prereqs:
        rel_path, marker, description = _CHECKS[prereq]
        target = root / rel_path

        if prereq == Prereq.ALEMBIC_VERSIONS:
            if not target.is_dir():
                errors.append(f"Missing: {description}")
            continue

        if not target.is_file():
            errors.append(f"Missing: {description}")
            continue

        if marker:
            content = target.read_text(errors="replace")
            if marker not in content:
                errors.append(
                    f"Found {rel_path} but missing '{marker}' — "
                    f"expected: {description}"
                )

    return errors


# ---------------------------------------------------------------------------
# Standalone mode: auto-scaffold missing prerequisites
# ---------------------------------------------------------------------------

_SCAFFOLDS: dict[Prereq, tuple[str, str]] = {
    Prereq.BASE_MODEL: (
        "app/models/base.py",
        textwrap.dedent("""\
            \"\"\"Shared declarative base for all ORM models.\"\"\"

            from sqlalchemy.orm import DeclarativeBase


            class Base(DeclarativeBase):
                \"\"\"Base class for all models.\"\"\"

                pass
        """),
    ),
    Prereq.CONFIG_SETTINGS: (
        "app/core/config.py",
        textwrap.dedent("""\
            \"\"\"Application settings — loaded from environment variables.\"\"\"

            from __future__ import annotations

            from pydantic_settings import BaseSettings, SettingsConfigDict


            class Settings(BaseSettings):
                model_config = SettingsConfigDict(
                    env_file=".env", env_file_encoding="utf-8",
                    env_ignore_empty=True, extra="ignore",
                )

                SECRET_KEY: str = "changethis"
                ENVIRONMENT: str = "local"
                ACCESS_TOKEN_EXPIRE_MINUTES: int = 30

                POSTGRES_SERVER: str = "localhost"
                POSTGRES_PORT: int = 5432
                POSTGRES_USER: str = "postgres"
                POSTGRES_PASSWORD: str = ""
                POSTGRES_DB: str = "app"

                REDIS_URL: str = "redis://localhost:6379/0"


            settings = Settings()
        """),
    ),
    Prereq.ROUTES_INIT: (
        "app/routes/__init__.py",
        textwrap.dedent("""\
            \"\"\"Route registration.\"\"\"

            from fastapi import APIRouter

            api_router = APIRouter()

            __all__ = ["api_router"]
        """),
    ),
    Prereq.MODELS_INIT: (
        "app/models/__init__.py",
        '"""import all models here for Alembic auto-discovery."""\n',
    ),
    Prereq.SESSION_DEP: (
        "app/core/session.py",
        textwrap.dedent("""\
            \"\"\"Async session factory and FastAPI dependency.\"\"\"

            from collections.abc import AsyncGenerator

            from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

            from app.core.db import engine

            async_session = async_sessionmaker(
                engine, class_=AsyncSession, expire_on_commit=False,
            )


            async def get_session() -> AsyncGenerator[AsyncSession, None]:
                async with async_session() as session:
                    yield session
        """),
    ),
    Prereq.REQUIREMENTS_TXT: (
        "requirements.txt",
        (
            "fastapi>=0.115.0\n"
            "uvicorn[standard]>=0.32.0\n"
            "pydantic>=2.10.0\n"
            "pydantic-settings>=2.6.0\n"
            "sqlalchemy[asyncio]>=2.0.36\n"
            "asyncpg>=0.30.0\n"
            "alembic>=1.14.0\n"
            "structlog>=24.4.0\n"
            "httpx>=0.28.0\n"
        ),
    ),
    Prereq.ALEMBIC_VERSIONS: (
        "alembic/versions/.gitkeep",
        "",
    ),
}


def ensure_prerequisites(
    project_dir: str | Path,
    *prereqs: Prereq,
    auto_scaffold: bool = False,
) -> tuple[list[str], list[str]]:
    """Check prerequisites and optionally auto-scaffold missing ones.

    Convenience wrapper that combines ``check_prerequisites`` +
    ``scaffold_prerequisites``. When ``auto_scaffold=True``, missing
    prerequisites are created automatically before returning.

    Args:
        project_dir: Root of the FastAPI project.
        *prereqs: Prerequisites to check (and optionally scaffold).
        auto_scaffold: When ``True``, create missing prerequisites instead
            of returning errors. Only scaffoldable prereqs are created;
            non-scaffoldable ones (like AUTH_DEPS) still return errors.

    Returns:
        Tuple of ``(errors, scaffolded_files)``.

        * ``errors``: remaining prerequisite errors AFTER scaffolding
          (empty if everything was resolved).
        * ``scaffolded_files``: paths created during auto-scaffolding
          (empty if ``auto_scaffold=False`` or nothing was missing).
    """
    errors = check_prerequisites(project_dir, *prereqs)
    if not errors or not auto_scaffold:
        return errors, []

    # Scaffold what we can, then re-check for anything that couldn't
    # be auto-created (e.g., AUTH_DEPS requires full auth stack)
    scaffolded = scaffold_prerequisites(project_dir, *prereqs)
    remaining = check_prerequisites(project_dir, *prereqs)
    return remaining, scaffolded


def scaffold_prerequisites(
    project_dir: str | Path,
    *prereqs: Prereq,
) -> list[str]:
    """Auto-create missing prerequisites with minimal, functional content.

    Only creates files that are actually missing — existing files are
    NEVER overwritten. This makes adapt tools work on ANY FastAPI project,
    not just ones generated by the skill.

    Args:
        project_dir: Root of the FastAPI project.
        *prereqs: Prerequisites to scaffold if missing.

    Returns:
        List of ABSOLUTE paths to ``.py`` files that were created. Empty
        if everything already existed. Non-Python artefacts (``.gitkeep``,
        ``requirements.txt``, alembic versions directory) are scaffolded
        on disk but NOT included in the return list, because downstream
        tools iterate the list and call ``ast.parse(p.read_text())`` on
        every entry, which crashes on non-Python content.
    """
    created: list[str] = []
    root = Path(project_dir).resolve()

    def _record(path: Path) -> None:
        """Append *path* to ``created`` only when it is a real ``.py`` file.

        Non-Python scaffold artefacts (requirements.txt, .gitkeep, etc.)
        are excluded so downstream ``_validate_py`` loops in adapt tools
        don't choke on them.
        """
        if path.suffix == ".py" and path.is_file():
            created.append(str(path))

    # Collect the set of paths that have explicit scaffold content so the
    # parent-package __init__.py creation below doesn't pre-empt them with
    # a generic placeholder (e.g. MODELS_INIT targets app/models/__init__.py).
    explicit_targets: set[str] = set()
    for prereq in prereqs:
        if prereq in _SCAFFOLDS:
            explicit_targets.add(_SCAFFOLDS[prereq][0])

    # Ensure the app/ package exists
    app_init = root / "app" / "__init__.py"
    if not app_init.exists() and "app/__init__.py" not in explicit_targets:
        app_init.parent.mkdir(parents=True, exist_ok=True)
        app_init.write_text('"""Application package."""\n')
        _record(app_init)

    for prereq in prereqs:
        if prereq not in _SCAFFOLDS:
            continue

        rel_path, content = _SCAFFOLDS[prereq]
        target = root / rel_path

        if prereq == Prereq.ALEMBIC_VERSIONS:
            versions_dir = root / "alembic" / "versions"
            if not versions_dir.is_dir():
                versions_dir.mkdir(parents=True, exist_ok=True)
                (versions_dir / ".gitkeep").write_text("")
                # Directory created, but NOT appended to ``created``: the
                # list is consumed by downstream tools that iterate it and
                # call ``ast.parse(p.read_text())``. A directory path or a
                # non-Python placeholder file would crash that loop. The
                # scaffolded directory is represented implicitly by the
                # absence of the crash, not by a list entry.
            continue

        if target.exists():
            continue

        target.parent.mkdir(parents=True, exist_ok=True)
        # Ensure parent package __init__.py exists
        for parent in target.relative_to(root).parents:
            if parent == Path("."):
                continue
            parent_init = root / parent / "__init__.py"
            if not parent_init.exists() and (root / parent).is_dir():
                # Don't create a generic placeholder if this path has an
                # explicit scaffold (will be written by a later iteration).
                parent_rel = str(parent / "__init__.py")
                if parent_rel in explicit_targets:
                    continue
                parent_init.write_text(f'"""{parent.name} package."""\n')
                _record(parent_init)

        target.write_text(content)
        _record(target)

    return created
