"""Protocol for StructuredLogger — generated from StructuredLogger.py."""

from __future__ import annotations

from typing import Any, Optional, Protocol, runtime_checkable
from collections.abc import Mapping

@runtime_checkable
class StructuredLogger(Protocol):
    """StructuredLogger primitive — key/value log records, fixed taxonomy, JSON lines."""

    def debug(self, event: str) -> None: ...
    def info(self, event: str) -> None: ...
    def warn(self, event: str) -> None: ...
    def error(self, event: str) -> None: ...
    def bind(self) -> StructuredLogger: ...
    def with_context(self, context: Mapping[str, Any]) -> StructuredLogger: ...
