from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class ResourceAccessPolicyProtocol(Protocol):
    """Auto-inferred Protocol surface for `ResourceAccessPolicy`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    def allows(self, user_id: Any, resource_id: Any, write: bool = False) -> bool: ...
