from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class OutboxServiceProtocol(Protocol):
    """Auto-inferred Protocol surface for `OutboxService`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    async def emit(self, event_type: str, payload: dict[str, Any], *, aggregate_type: str | None = None, aggregate_id: str | None = None, idempotency_key: str | None = None) -> uuid.UUID: ...
