from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class OwnershipVerifierProtocol(Protocol):
    """Auto-inferred Protocol surface for `OwnershipVerifier`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    async def __call__(self, request: Request, session: AsyncSession = Depends(lambda: None)) -> None: ...
