from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class StripeBillingProtocol(Protocol):
    """Auto-inferred Protocol surface for `StripeBilling`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    def create_customer(self, email: str, metadata: dict[str, str] | None = None) -> Any: ...
    def create_subscription(self, customer_id: str, price_id: str, trial_period_days: int | None = None) -> Any: ...
    def cancel_subscription(self, stripe_subscription_id: str) -> Any: ...
    def change_plan(self, stripe_subscription_id: str, new_price_id: str) -> Any: ...
    def construct_webhook_event(self, payload: bytes, sig_header: str) -> Any: ...
