from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class ShutdownMiddlewareProtocol(Protocol):
    """Auto-inferred Protocol surface for `ShutdownMiddleware`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_staging/`.
    """

    async def dispatch(self, request: Request, call_next: RequestResponseEndpoint) -> Response: ...
