from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class UploadSizeMiddlewareProtocol(Protocol):
    """Auto-inferred Protocol surface for `UploadSizeMiddleware`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    async def dispatch(self, request: Request, call_next: object) -> Response: ...
