"""BEHAVIOR TEST — TOOL-001 add_soft_delete (P1-#14).

Proves that the code generated by ``add_soft_delete`` works at **runtime**:
boots a real ASGI app, patches CRUDBase, and verifies:

  * the soft-delete patch is loaded into the CRUDBase class object;
  * the patched delete() flips ``is_deleted=True`` instead of issuing SQL DELETE;
  * the patched get_multi() filters soft-deleted rows out by default;
  * per-model opt-out (F-04): a model WITHOUT ``is_deleted`` falls through to
    hard-delete (so auth/infra tables keep PII/rotation correctness);
  * the orphan ``app/soft_delete.py`` UoW shim is NOT emitted.

Patches applied (so tests run without Docker):
- ``app/core/db.py``               → SQLite + aiosqlite (no Postgres)
- ``app/middleware/idempotency.py`` → pass-through stub (no Redis)
- ``REDIS_URL`` env var             → removed
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Environment setup — MUST happen before any app import
# ---------------------------------------------------------------------------
import os

os.environ.setdefault("RATE_LIMITING_ENABLED", "false")
os.environ.setdefault("ENVIRONMENT", "local")
os.environ.setdefault("SECRET_KEY", "behavior-test-soft-delete-secret-key-32+!")
os.environ.pop("REDIS_URL", None)

import importlib
import sys
import textwrap
from datetime import UTC
from pathlib import Path
from typing import Any

import httpx
import pytest

from adapt.contracts import ToolInput
from adapt.extend.crud_data.add_soft_delete import add_soft_delete
from tests.common.fixture_factory import create_fixture_project

# ---------------------------------------------------------------------------
# Patch templates
# ---------------------------------------------------------------------------

_SQLITE_DB_PY = textwrap.dedent("""\
    \"\"\"Patched db.py — SQLite+aiosqlite, no Docker required.\"\"\"

    from sqlalchemy import text
    from sqlalchemy.ext.asyncio import create_async_engine

    engine = create_async_engine(
        "sqlite+aiosqlite:///:memory:",
        echo=False,
        future=True,
        connect_args={"check_same_thread": False},
    )


    async def init_db() -> None:
        \"\"\"Run startup checks (connection test).\"\"\"
        async with engine.begin() as conn:
            await conn.execute(text("SELECT 1"))


    __all__ = ["engine", "init_db"]
""")

_PASSTHROUGH_IDEMPOTENCY_PY = textwrap.dedent("""\
    \"\"\"Patched idempotency.py — pass-through stub (no Redis).\"\"\"

    from __future__ import annotations

    from starlette.middleware.base import BaseHTTPMiddleware, RequestResponseEndpoint
    from starlette.requests import Request
    from starlette.responses import Response


    class IdempotencyMiddleware(BaseHTTPMiddleware):
        \"\"\"No-op pass-through stub for testing without Redis.\"\"\"

        async def dispatch(
            self,
            request: Request,
            call_next: RequestResponseEndpoint,
        ) -> Response:
            return await call_next(request)
""")


def _patch_project(project_dir: Path) -> None:
    (project_dir / "app" / "core" / "db.py").write_text(_SQLITE_DB_PY)
    idempotency_path = project_dir / "app" / "middleware" / "idempotency.py"
    if idempotency_path.exists():
        idempotency_path.write_text(_PASSTHROUGH_IDEMPOTENCY_PY)


def _load_app(project_dir: Path) -> Any:
    _orig_path = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        app_module = importlib.import_module("app.main")
    finally:
        sys.path[:] = _orig_path
    return app_module.app


def _setup_project() -> tuple[Path, Any]:
    project_dir = create_fixture_project(name="sd_behavior")
    result = add_soft_delete(ToolInput(project_dir=str(project_dir)))
    assert result.status == "success", (
        f"add_soft_delete failed: {result.error}\nnotes: {result.notes}"
    )
    _patch_project(project_dir)
    asgi_app = _load_app(project_dir)
    return project_dir, asgi_app


# ---------------------------------------------------------------------------
# Module-level shared state
# ---------------------------------------------------------------------------

_PROJECT_DIR: Path | None = None
_ASGI_APP: Any = None


def _get_shared_app() -> tuple[Path, Any]:
    global _PROJECT_DIR, _ASGI_APP
    if _PROJECT_DIR is None:
        _PROJECT_DIR, _ASGI_APP = _setup_project()
    return _PROJECT_DIR, _ASGI_APP


@pytest.fixture(scope="module")
def project_dir_and_app() -> tuple[Path, Any]:
    return _get_shared_app()


@pytest.fixture(scope="module")
def project_dir(project_dir_and_app: tuple[Path, Any]) -> Path:
    return project_dir_and_app[0]


@pytest.fixture(scope="module")
def asgi_app(project_dir_and_app: tuple[Path, Any]) -> Any:
    return project_dir_and_app[1]


# ---------------------------------------------------------------------------
# B-01: App boots after CRUDBase patched
# ---------------------------------------------------------------------------


@pytest.mark.anyio
async def test_b01_healthz_returns_200(asgi_app: Any) -> None:
    """B-01: GET /healthz returns 200 after CRUDBase patched in place."""
    transport = httpx.ASGITransport(app=asgi_app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.get("/healthz")
    assert response.status_code == 200, (
        f"Expected 200, got {response.status_code}; body: {response.text}"
    )


# ---------------------------------------------------------------------------
# B-02: CRUDBase methods are rebound to soft-delete-aware variants
# ---------------------------------------------------------------------------


def test_b02_crudbase_methods_rebound(project_dir: Path) -> None:
    """B-02: After import, CRUDBase.get/get_multi/delete are the _sd_* variants."""
    _orig_path = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        from app.crud import base as crud_base_mod

        assert crud_base_mod.CRUDBase.get.__name__ == "_sd_get", (
            f"CRUDBase.get not rebound to _sd_get; got {crud_base_mod.CRUDBase.get.__name__}"
        )
        assert crud_base_mod.CRUDBase.get_multi.__name__ == "_sd_get_multi", (
            f"CRUDBase.get_multi not rebound; got {crud_base_mod.CRUDBase.get_multi.__name__}"
        )
        assert crud_base_mod.CRUDBase.delete.__name__ == "_sd_delete", (
            f"CRUDBase.delete not rebound; got {crud_base_mod.CRUDBase.delete.__name__}"
        )
    finally:
        sys.path[:] = _orig_path


# ---------------------------------------------------------------------------
# B-03: P1-#14 — orphan UoW shim NOT emitted
# ---------------------------------------------------------------------------


def test_b03_no_orphan_uow_shim(project_dir: Path) -> None:
    """B-03: P1-#14 — app/soft_delete.py is dead code and must NOT exist."""
    orphan = project_dir / "app" / "soft_delete.py"
    assert not orphan.exists(), (
        "app/soft_delete.py is the orphan UoW shim (no caller) — must not be emitted"
    )


# ---------------------------------------------------------------------------
# B-04: is_deleted column injected into the domain model
# ---------------------------------------------------------------------------


def test_b04_is_deleted_column_injected(project_dir: Path) -> None:
    """B-04: domain model file contains is_deleted + deleted_at columns."""
    model_file = project_dir / "app" / "models" / "item.py"
    assert model_file.exists(), "item.py model missing"
    body = model_file.read_text()
    assert "is_deleted" in body, "is_deleted column not injected (BUG C regression)"
    assert "deleted_at" in body, "deleted_at column not injected"
    assert "Boolean" in body and "DateTime" in body, (
        "Boolean/DateTime imports must be added when columns are injected"
    )


# ---------------------------------------------------------------------------
# B-05: F-04 per-model opt-out — model WITHOUT is_deleted hard-deletes
# ---------------------------------------------------------------------------


@pytest.mark.anyio
async def test_b05_per_model_opt_out_hard_deletes(project_dir: Path) -> None:
    """B-05: F-04 — the patched delete() falls through to SQL DELETE for opt-out models.

    Constructs a model WITHOUT ``is_deleted`` in-memory and exercises
    CRUDBase.delete on it; the patched code must call session.delete (hard
    delete) because hasattr(obj, 'is_deleted') is False.
    """
    _orig_path = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        from app.crud.base import CRUDBase  # noqa: F401  (load the patched class)
        from sqlalchemy import Column, Integer, String
        from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine
        from sqlalchemy.orm import DeclarativeBase

        class _Base(DeclarativeBase):
            pass

        class OptOutModel(_Base):
            __tablename__ = "optout_model"
            id = Column(Integer, primary_key=True)
            name = Column(String, nullable=False)

        engine = create_async_engine("sqlite+aiosqlite:///:memory:")
        async with engine.begin() as conn:
            await conn.run_sync(_Base.metadata.create_all)
        session_factory = async_sessionmaker(engine, expire_on_commit=False)

        crud = CRUDBase(OptOutModel)
        async with session_factory() as session:
            obj = OptOutModel(id=1, name="ephemeral")
            session.add(obj)
            await session.flush()
            deleted = await crud.delete(session, 1)
            await session.commit()
            assert deleted is not None, "delete() must return the deleted object"
            # Hard-delete: a subsequent get() must return None because the row is gone.
            re_fetched = await crud.get(session, 1)
            assert re_fetched is None, (
                "Opt-out model must hard-delete; got a row back (F-04 regression)"
            )
        await engine.dispose()
    finally:
        sys.path[:] = _orig_path


# ---------------------------------------------------------------------------
# B-06: opt-in (is_deleted column) → soft-delete flips the flag
# ---------------------------------------------------------------------------


@pytest.mark.anyio
async def test_b06_opt_in_soft_deletes(project_dir: Path) -> None:
    """B-06: P1-#14 — model WITH is_deleted gets soft-deleted (flag flip, no SQL DELETE)."""
    _orig_path = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        from datetime import datetime

        from app.crud.base import CRUDBase
        from sqlalchemy import Boolean, Column, DateTime, Integer, String
        from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine
        from sqlalchemy.orm import DeclarativeBase

        class _Base(DeclarativeBase):
            pass

        class SoftModel(_Base):
            __tablename__ = "soft_model"
            id = Column(Integer, primary_key=True)
            name = Column(String, nullable=False)
            created_at = Column(DateTime, default=lambda: datetime.now(UTC))
            is_deleted = Column(Boolean, default=False, nullable=False)
            deleted_at = Column(DateTime, nullable=True)

        engine = create_async_engine("sqlite+aiosqlite:///:memory:")
        async with engine.begin() as conn:
            await conn.run_sync(_Base.metadata.create_all)
        session_factory = async_sessionmaker(engine, expire_on_commit=False)

        crud = CRUDBase(SoftModel)
        async with session_factory() as session:
            obj = SoftModel(id=1, name="alive")
            session.add(obj)
            await session.flush()
            await crud.delete(session, 1)
            await session.commit()

        async with session_factory() as session:
            # get() must filter soft-deleted rows out — returns None.
            filtered = await crud.get(session, 1)
            assert filtered is None, (
                "get() must filter is_deleted rows out (read-side filter regression)"
            )
            # But the row is still physically present.
            from sqlalchemy import select

            raw = await session.execute(select(SoftModel).where(SoftModel.id == 1))
            row = raw.scalar_one_or_none()
            assert row is not None, "Soft-delete must NOT issue SQL DELETE (P1-#14 regression)"
            assert row.is_deleted is True, "is_deleted flag must be flipped True"
            assert row.deleted_at is not None, "deleted_at must be stamped"
        await engine.dispose()
    finally:
        sys.path[:] = _orig_path
