from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class StripeVerifierProtocol(Protocol):
    """Auto-inferred Protocol surface for `StripeVerifier`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    def verify(self, body: bytes, headers: dict[str, str]) -> VerifiedEvent: ...
