from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class ReportEngineProtocol(Protocol):
    """Auto-inferred Protocol surface for `ReportEngine`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_staging/`.
    """

    def render_template(self, template_name: str, context: dict) -> str: ...
    def render_html_to_pdf(self, html: str) -> bytes: ...
    async def generate_pdf_async(self, template_name: str, context: dict) -> bytes: ...
