from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class SchedulerFactoryProtocol(Protocol):
    """Auto-inferred Protocol surface for `SchedulerFactory`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_staging/`.
    """

    @staticmethod
    def build() -> Any: ...
