from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class TimeoutRegistryProtocol(Protocol):
    """Auto-inferred Protocol surface for `TimeoutRegistry`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    def get_or_create(self, name: str) -> 'AdaptiveTimeout': ...
    def all_stats(self) -> dict[str, dict[str, float]]: ...
    def names(self) -> list[str]: ...
