from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class AdminScenarioProtocol(Protocol):
    """Auto-inferred Protocol surface for `AdminScenario`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    def list_users(self) -> None: ...
    def check_health(self) -> None: ...
