"""TOOL-027: add_load_profile — Locust load-test profiles for a FastAPI project.

Generates a production-grade ``tests/load/`` directory with locustfile.py,
scenarios, auth mixin, data factories, SLO config, SLO assertions, shapes,
and a CI workflow.

The tool is idempotent: a second run returns ``status="no_op"`` when the
``tests/load/locustfile.py`` fingerprint is already present.
"""

from __future__ import annotations

import ast
import time
from pathlib import Path

from adapt._base import render_to
from adapt.contracts import ToolInput, ToolResult, validate_project_dir
from adapt.contracts.tool_result import _elapsed_ms
from adapt.contracts.tool_result import _elapsed_ms
from adapt.contracts.prerequisites import Prereq, ensure_prerequisites

_HERE = Path(__file__).parent

MCP_TOOL = {
    "name": "fastapi_testing_add_load_profile",
    "description": "Add k6 load test profiles (smoke, load, stress, soak) for the project's endpoints.",
    "tags": ["extend", "testing"],
    "entry": "add_load_profile",
    "imports_primitives": [],
    "imports_adapters": [],

}


def add_load_profile(
    inp: ToolInput,
    endpoints: list[str] | None = None,
    users: int = 100,
    spawn_rate: int = 10,
    duration_seconds: int = 60,
    targets_p99_ms: dict[str, int] | None = None,
) -> ToolResult:
    """Generate Locust load-test profiles for a FastAPI project.

    Args:
        inp: ``ToolInput`` with ``project_dir`` and optional ``dry_run``.
        endpoints: Endpoint paths to include (``None`` = all authenticated endpoints).
        users: Target concurrent users (default 100).
        spawn_rate: Users spawned per second during ramp-up (default 10).
        duration_seconds: Smoke profile duration in seconds (default 60).
        targets_p99_ms: Dict mapping endpoint labels to p99 latency SLOs in ms.

    Returns:
        ``ToolResult`` with ``status``, ``files_created``, ``files_modified``,
        ``notes``, and ``next_steps``.
    """
    start = time.monotonic()
    project = Path(inp.project_dir)
    err = validate_project_dir(inp.project_dir)
    if err:
        return ToolResult(status="error", error=err, execution_time_ms=_elapsed_ms(start))

    prereq_errors, scaffolded = ensure_prerequisites(
        inp.project_dir,
        Prereq.BASE_MODEL,
        auto_scaffold=not inp.dry_run,
    )
    if prereq_errors:
        return ToolResult(
            status="error",
            error="Prerequisites not met:\n" + "\n".join(f"  - {e}" for e in prereq_errors),
            notes=[
                "These prerequisites cannot be auto-created.",
                "Generate a base project first:",
                "  fastapi_generate_project(output_dir='...', profile='api', models={...})",
            ],
            execution_time_ms=_elapsed_ms(start),
        )

    files_created: list[str] = list(scaffolded or [])
    load_dir = project / "tests" / "load"

    _locustfile = load_dir / "locustfile.py"
    if _locustfile.exists() and "BrowsingUser" in _locustfile.read_text():
        return ToolResult(
            status="no_op",
            notes=["tests/load/locustfile.py already present — skipped."],
            execution_time_ms=_elapsed_ms(start),
        )

    if inp.dry_run:
        return ToolResult(
            status="success",
            notes=[
                f"[dry_run] Would generate Locust profiles (users={users}, spawn_rate={spawn_rate}).",
                f"[dry_run] duration_seconds={duration_seconds}.",
                "[dry_run] No files written.",
            ],
            next_steps=["Re-run without dry_run=True to apply changes."],
            execution_time_ms=_elapsed_ms(start),
        )

    slos = targets_p99_ms or {
        "GET /api/v1/items": 300,
        "POST /api/v1/items": 500,
        "GET /api/v1/users/me": 200,
    }

    load_dir.mkdir(parents=True, exist_ok=True)
    ci_dir = project / ".github" / "workflows"
    ci_dir.mkdir(parents=True, exist_ok=True)

    files_modified: list[str] = []

    init_file = load_dir / "__init__.py"
    init_file.write_text('"""Load test package generated by add_load_profile (TOOL-027)."""\n')
    files_created.append(str(init_file))

    render_to(_HERE, "auth_mixin.py.tmpl", dest=load_dir / "auth.py", substitutions={})
    files_created.append(str(load_dir / "auth.py"))

    render_to(
        _HERE, "data_factories.py.tmpl", dest=load_dir / "data_factories.py", substitutions={}
    )
    files_created.append(str(load_dir / "data_factories.py"))

    render_to(
        _HERE, "slo_assertions.py.tmpl", dest=load_dir / "slo_assertions.py", substitutions={}
    )
    files_created.append(str(load_dir / "slo_assertions.py"))

    _write_slo_yaml(load_dir / "slo_config.yaml", slos)
    files_created.append(str(load_dir / "slo_config.yaml"))

    _write_shapes(load_dir / "shapes.py", users, spawn_rate, duration_seconds)
    files_created.append(str(load_dir / "shapes.py"))

    render_to(_HERE, "scenarios.py.tmpl", dest=load_dir / "scenarios.py", substitutions={})
    files_created.append(str(load_dir / "scenarios.py"))

    _write_locustfile(load_dir / "locustfile.py", users, spawn_rate)
    files_created.append(str(load_dir / "locustfile.py"))

    _write_ci_workflow(ci_dir / "load-tests.yml", users, spawn_rate, duration_seconds)
    files_created.append(str(ci_dir / "load-tests.yml"))

    for path_str in files_created:
        p = Path(path_str)
        if p.suffix == ".py" and p.is_file():
            try:
                ast.parse(p.read_text())
            except SyntaxError as exc:
                return ToolResult(
                    status="error",
                    error=f"Generated file has syntax error: {p}: {exc}",
                    execution_time_ms=_elapsed_ms(start),
                )

    (project / "tests").mkdir(parents=True, exist_ok=True)
    emitted = project / "tests" / "test_add_load_profile_emitted.py"
    if not emitted.exists():
        render_to(_HERE, "test_add_load_profile_emitted.py.tmpl", dest=emitted, substitutions={})
        files_created.append(str(emitted))

    return ToolResult(
        status="success",
        files_created=files_created,
        files_modified=files_modified,
        notes=[
            f"3 load profiles: smoke ({duration_seconds}s / 10 users), "
            f"baseline ({users} users), peak ({users * 3} users).",
            "SLO assertions wired via locust.events.quitting — non-zero exit on violation.",
            "Step-load shape in shapes.py ramps users gradually for time-to-failure capture.",
            f"Default p99 SLO targets: {slos}",
        ],
        next_steps=[
            "pip install locust faker",
            f"locust -f tests/load/locustfile.py --users 10 --spawn-rate 2 "
            f"--run-time {duration_seconds}s --headless",
            f"locust -f tests/load/locustfile.py --users {users} "
            f"--spawn-rate {spawn_rate} --run-time 300s --headless",
            "Edit tests/load/slo_config.yaml to tune p99 targets per environment.",
        ],
        execution_time_ms=_elapsed_ms(start),
    )


def _write_slo_yaml(dest: Path, slos: dict[str, int]) -> None:
    slo_lines = "\n".join(f'  "{label}": {ms}' for label, ms in sorted(slos.items()))
    content = (
        "# tests/load/slo_config.yaml\n"
        "# Per-endpoint p99 latency SLO targets (milliseconds).\n"
        "# Generated by add_load_profile tool (TOOL-027).\n\n"
        "p99_targets_ms:\n"
        f"{slo_lines}\n\n"
        "max_error_rate_pct: 1.0\n"
        "min_rps: 10\n"
    )
    dest.write_text(content)


def _write_shapes(dest: Path, users: int, spawn_rate: int, duration_seconds: int) -> None:
    smoke_users = max(5, users // 10)
    peak_users = users * 3
    users_fifth = max(1, users // 5)
    users_half = users // 2
    content = (
        '"""Locust LoadTestShape classes for stepped load profiles.\n\n'
        "Generated by add_load_profile tool (TOOL-027).\n"
        '"""\n\n'
        "from __future__ import annotations\n\n"
        "from locust import LoadTestShape\n\n\n"
        "class SmokeShape(LoadTestShape):\n"
        f'    """Minimal smoke profile: {smoke_users} users for {duration_seconds} seconds."""\n\n'
        "    stages = [\n"
        f"        {{'duration': {duration_seconds}, 'users': {smoke_users}, "
        f"'spawn_rate': {spawn_rate}}},\n"
        "    ]\n\n"
        "    def tick(self) -> tuple[int, float] | None:\n"
        '        """Return (user_count, spawn_rate) or None to stop."""\n'
        "        run_time = self.get_run_time()\n"
        "        for stage in self.stages:\n"
        '            if run_time <= stage["duration"]:\n'
        '                return stage["users"], stage["spawn_rate"]\n'
        "        return None\n\n\n"
        "class BaselineShape(LoadTestShape):\n"
        f'    """Graduated ramp to {users} users, then hold for regression detection."""\n\n'
        "    stages = [\n"
        f"        {{'duration': 30,  'users': {users_fifth}, 'spawn_rate': {spawn_rate}}},\n"
        f"        {{'duration': 90,  'users': {users_half}, 'spawn_rate': {spawn_rate}}},\n"
        f"        {{'duration': 240, 'users': {users}, 'spawn_rate': {spawn_rate}}},\n"
        "    ]\n\n"
        "    def tick(self) -> tuple[int, float] | None:\n"
        '        """Return (user_count, spawn_rate) or None to stop."""\n'
        "        run_time = self.get_run_time()\n"
        "        for stage in self.stages:\n"
        '            if run_time <= stage["duration"]:\n'
        '                return stage["users"], stage["spawn_rate"]\n'
        "        return None\n\n\n"
        "class PeakShape(LoadTestShape):\n"
        f'    """Step-load up to {peak_users} users to find the capacity envelope."""\n\n'
        "    stages = [\n"
        f"        {{'duration': 60,  'users': {users},         'spawn_rate': {spawn_rate}}},\n"
        f"        {{'duration': 120, 'users': {users * 2},     'spawn_rate': {spawn_rate * 2}}},\n"
        f"        {{'duration': 200, 'users': {peak_users},    'spawn_rate': {spawn_rate * 3}}},\n"
        f"        {{'duration': 260, 'users': {users},         'spawn_rate': {spawn_rate}}},\n"
        "    ]\n\n"
        "    def tick(self) -> tuple[int, float] | None:\n"
        '        """Return (user_count, spawn_rate) or None to stop."""\n'
        "        run_time = self.get_run_time()\n"
        "        for stage in self.stages:\n"
        '            if run_time <= stage["duration"]:\n'
        '                return stage["users"], stage["spawn_rate"]\n'
        "        return None\n"
    )
    dest.write_text(content)


def _write_locustfile(dest: Path, users: int, spawn_rate: int) -> None:
    content = (
        '"""Main Locust load-test entry point.\n\n'
        "Three weighted user classes simulate production traffic distribution.\n\n"
        "Generated by add_load_profile tool (TOOL-027).\n"
        '"""\n\n'
        "from __future__ import annotations\n\n"
        "from locust import HttpUser, between\n\n"
        "from tests.load.auth import AuthMixin\n"
        "from tests.load.scenarios import ActiveUserScenario, AdminScenario, BrowsingScenario\n"
        "from tests.load.slo_assertions import register_slo_handlers\n\n"
        "register_slo_handlers()\n\n\n"
        "class BrowsingUser(HttpUser, AuthMixin):\n"
        '    """Simulates a read-heavy browsing user (70% traffic share)."""\n\n'
        "    weight = 5\n"
        "    wait_time = between(0.5, 2.5)\n"
        "    tasks = [BrowsingScenario]\n\n"
        "    def on_start(self) -> None:\n"
        '        """Login once at spawn and cache the JWT."""\n'
        "        self.login()\n\n\n"
        "class ActiveUser(HttpUser, AuthMixin):\n"
        '    """Simulates a write-active user (25% traffic share)."""\n\n'
        "    weight = 3\n"
        "    wait_time = between(1.0, 3.0)\n"
        "    tasks = [ActiveUserScenario]\n\n"
        "    def on_start(self) -> None:\n"
        '        """Login once at spawn and cache the JWT."""\n'
        "        self.login()\n\n\n"
        "class AdminUser(HttpUser, AuthMixin):\n"
        '    """Simulates an admin user (5% traffic share)."""\n\n'
        "    weight = 1\n"
        "    wait_time = between(2.0, 5.0)\n"
        "    tasks = [AdminScenario]\n\n"
        "    def on_start(self) -> None:\n"
        '        """Login once at spawn and cache the JWT."""\n'
        "        self.login()\n"
    )
    dest.write_text(content)


def _write_ci_workflow(dest: Path, users: int, spawn_rate: int, duration: int) -> None:
    smoke_users = max(5, users // 10)
    content = (
        "# .github/workflows/load-tests.yml\n"
        "# Load regression detection — runs smoke profile on every PR.\n"
        "# Generated by add_load_profile tool (TOOL-027).\n\n"
        "name: Load Tests\n\n"
        "on:\n"
        "  pull_request:\n"
        "    branches: [main, develop]\n\n"
        "jobs:\n"
        "  smoke:\n"
        "    name: Smoke load profile\n"
        "    runs-on: ubuntu-latest\n"
        "    steps:\n"
        "      - uses: actions/checkout@v4\n\n"
        "      - name: Set up Python\n"
        "        uses: actions/setup-python@v5\n"
        "        with:\n"
        '          python-version: "3.12"\n'
        "          cache: pip\n\n"
        "      - name: Install Locust\n"
        "        run: pip install locust faker pyyaml\n\n"
        "      - name: Run smoke profile\n"
        "        run: |\n"
        "          locust \\\n"
        "            -f tests/load/locustfile.py \\\n"
        "            --host http://localhost:8000 \\\n"
        f"            --users {smoke_users} \\\n"
        f"            --spawn-rate {spawn_rate} \\\n"
        f"            --run-time {duration}s \\\n"
        "            --headless \\\n"
        "            --csv load_results\n"
        "        env:\n"
        "          PYTHONPATH: .\n\n"
        "      - name: Upload load results\n"
        "        if: always()\n"
        "        uses: actions/upload-artifact@v4\n"
        "        with:\n"
        "          name: load-results\n"
        "          path: |\n"
        "            load_results*.csv\n"
        "            load_slo_violations.json\n"
    )
    dest.write_text(content)


