"""TOOL-013: add_mfa — ship TotpVerifier primitive + FastAPI adapter.

CONTRACT §B1.0 + §B1.0.1 pattern (mirrors `add_graceful_shutdown`):

1. Copy the framework-agnostic primitive `core.venous.auth.TotpVerifier`
   into the generated project.
2. Copy the FastAPI adapter `core.venous._adapters.fastapi.TotpVerifierAdapter`
   alongside it.
3. Emit a thin ``app/mfa.py`` (≤20 lines of glue) that calls
   ``install(app)`` and exposes ``verify_totp(secret, code, last_step)``.
"""

from __future__ import annotations

import ast
import time
from pathlib import Path

from adapt.contracts import ToolInput, ToolResult, validate_project_dir

MCP_TOOL = {
    "name": "fastapi_auth_add_mfa",
    "description": (
        "Copy TotpVerifier primitive + FastAPI adapter into the project and "
        "wire a ≤20-line app/mfa.py caller."
    ),
    "tags": ["extend", "auth_access"],
    "entry": "add_mfa",
    "imports_primitives": [
        "core.venous.auth.TotpVerifier",
    ],
    "imports_adapters": [
        "core.venous._adapters.fastapi.TotpVerifierAdapter",
    ],
}


_GLUE = '''\
"""Wire MFA (TOTP) into the FastAPI app.

Delegates to `TotpVerifierAdapter` copied under `core/venous/` by
`add_mfa`. Hand-editing is safe but the file is re-emitted idempotently
on subsequent tool runs.

⚠ MFA IS NOT ENFORCED: the login route does NOT require a second factor
  until you wire verify_code into your login flow. No MFA state (secret,
  last_used_step) exists on the user model — you must add those fields.
  See app/api/routes/_mfa_example.py for the copy-paste login-verify step.

Minimal wiring (login route, after password check)::

    from app.mfa import get_verifier, verify_code
    verifier = get_verifier(request.app)
    new_step = await verify_code(verifier, secret=user.totp_secret,
                                 code=body.totp_code,
                                 last_step=user.totp_last_step)
    # persist new_step → user.totp_last_step before returning the token

Missing user-model fields you MUST add::

    totp_secret: bytes | None = None   # store the TOTP shared secret
    totp_last_step: int = 0            # anti-replay: last accepted step
"""

from __future__ import annotations

from fastapi import FastAPI

from core.venous._adapters.fastapi.TotpVerifierAdapter import (
    get_verifier,
    install as _install,
    verify_code,
)


def install_mfa(app: FastAPI):
    """Attach a StandardTotpVerifier to app.state.totp; return it."""
    return _install(app)


__all__ = ["install_mfa", "get_verifier", "verify_code"]
'''

# Warning text emitted in every ToolResult so callers cannot mistake "success"
# for "MFA is now active".  All-caps prefix is intentional — this is a P0
# honesty requirement: the tool ships the MECHANISM, not the POLICY.
_WARN_NOT_AUTO_ENFORCED = (
    "⚠ MFA IS NOT ENFORCED: login does not require a second factor until you "
    "wire verify_code into the login flow. No MFA state (totp_secret, "
    "totp_last_step) exists on the user model — you must add those fields. "
    "See app/api/routes/_mfa_example.py for the exact copy-paste wiring."
)

# Concrete wired example: the TOTP verification step inserted into a login flow.
_MFA_EXAMPLE = '''\
"""COPY-PASTE TEMPLATE: wiring MFA (TOTP) into the login flow.

This file is generated by add_mfa as a concrete, runnable reference.
It is NOT registered automatically — wire the verify step into your
existing login route (app/api/routes/login.py) as shown below.

⚠ MFA IS NOT ENFORCED on any route until you perform the steps below.
  The tool ships the mechanism; wiring is your responsibility.

Missing user-model fields (add to app/models/user.py)::

    totp_secret: bytes | None = None   # shared TOTP secret (keep encrypted at rest)
    totp_last_step: int = 0            # anti-replay: last accepted TOTP step counter

How to wire into app/api/routes/login.py (after password check)::

    from app.mfa import get_verifier, verify_code
    from fastapi import HTTPException, Request

    # Inside your login endpoint, after validating password:
    if user.totp_secret is not None:
        verifier = get_verifier(request.app)
        try:
            new_step = await verify_code(
                verifier,
                secret=user.totp_secret,
                code=body.totp_code,       # add totp_code to your login schema
                last_step=user.totp_last_step,
            )
        except Exception:
            raise HTTPException(status_code=401, detail="invalid or replayed TOTP code")
        # Persist the new step to prevent replay attacks:
        user.totp_last_step = new_step
        await db.commit()
    # then issue the access token as usual

Standalone example route (for testing the verifier in isolation):
"""

from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException, Request
from pydantic import BaseModel

from app.mfa import get_verifier, verify_code

router = APIRouter(prefix="/mfa-example", tags=["mfa-example"])


class _VerifyBody(BaseModel):
    secret_hex: str   # hex-encoded TOTP secret (for testing only — never expose real secrets)
    code: str         # 6-digit TOTP code
    last_step: int = 0


@router.post(
    "/verify",
    summary="[MFA example] Verify a TOTP code (testing endpoint — remove before prod)",
)
async def verify_totp_example(body: _VerifyBody, request: Request) -> dict:
    """Verify a TOTP code using the shipped StandardTotpVerifier.

    Returns the new last_step that you must persist on the user model to
    prevent replay attacks.
    """
    verifier = get_verifier(request.app)
    try:
        new_step = await verify_code(
            verifier,
            secret=bytes.fromhex(body.secret_hex),
            code=body.code,
            last_step=body.last_step,
        )
    except Exception as exc:
        raise HTTPException(status_code=401, detail=f"TOTP verification failed: {exc}") from exc
    return {"status": "ok", "new_last_step": new_step}
'''


# Mounted MFA router (prefix /auth/mfa). Every endpoint requires an
# authenticated user (Depends(get_current_user)) so unauthenticated probes
# get 401 before any model/DB access — there is no 500 path. The enrollment
# secret + step are returned to the caller to persist on the user model
# (totp_secret / totp_last_step), which add_mfa does NOT auto-create.
_MFA_ROUTER = '''\
"""Mounted MFA (TOTP) router — prefix ``/auth/mfa``.

Generated by add_mfa and registered in ``app/routes/__init__.py`` so it is
mounted under ``{API_V1_STR}/auth/mfa``. All endpoints require an
authenticated user.

⚠ MFA IS NOT ENFORCED on login until you wire verify_code into the login
  flow and persist totp_secret / totp_last_step on the user model. These
  endpoints manage enrollment state but do NOT gate the access-token issuance
  — see app/api/routes/_mfa_example.py for the login-flow wiring.
"""

from __future__ import annotations

from fastapi import APIRouter, HTTPException, Request, status
from pydantic import BaseModel

from app.api.deps import CurrentUser
from app.mfa import get_verifier, verify_code

router = APIRouter(prefix="/auth/mfa", tags=["mfa"])


class _EnrollResponse(BaseModel):
    secret_hex: str
    note: str


class _VerifyEnrollmentBody(BaseModel):
    secret_hex: str
    code: str


class _ChallengeBody(BaseModel):
    code: str
    last_step: int = 0


@router.post("/enroll", response_model=_EnrollResponse)
async def mfa_enroll(current_user: CurrentUser, request: Request) -> _EnrollResponse:
    """Generate a fresh TOTP secret for the current user to enroll.

    The caller must persist the returned secret on ``user.totp_secret`` and
    confirm enrollment via ``/verify-enrollment`` before MFA is active.
    """
    import secrets

    secret = secrets.token_bytes(20)
    return _EnrollResponse(
        secret_hex=secret.hex(),
        note="Persist secret_hex on user.totp_secret, then call /verify-enrollment.",
    )


@router.post("/verify-enrollment")
async def mfa_verify_enrollment(
    body: _VerifyEnrollmentBody,
    current_user: CurrentUser,
    request: Request,
) -> dict:
    """Verify the first TOTP code to confirm enrollment of a new secret."""
    verifier = get_verifier(request.app)
    try:
        new_step = await verify_code(
            verifier,
            secret=bytes.fromhex(body.secret_hex),
            code=body.code,
            last_step=0,
        )
    except Exception as exc:  # noqa: BLE001 — surface as 401, never 500
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="invalid TOTP code",
        ) from exc
    return {"status": "enrolled", "last_step": new_step}


@router.post("/challenge")
async def mfa_challenge(
    body: _ChallengeBody,
    current_user: CurrentUser,
    request: Request,
) -> dict:
    """Verify a TOTP challenge for an already-enrolled user.

    The caller supplies the user's stored ``last_step`` and persists the
    returned value to defeat replay.
    """
    secret = getattr(current_user, "totp_secret", None)
    if not secret:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="MFA not enrolled for this user",
        )
    verifier = get_verifier(request.app)
    try:
        new_step = await verify_code(
            verifier,
            secret=secret,
            code=body.code,
            last_step=body.last_step,
        )
    except Exception as exc:  # noqa: BLE001 — surface as 401, never 500
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="invalid or replayed TOTP code",
        ) from exc
    return {"status": "ok", "last_step": new_step}


@router.post("/disable")
async def mfa_disable(current_user: CurrentUser) -> dict:
    """Acknowledge MFA disable for the current user.

    The caller must clear ``user.totp_secret`` / ``user.totp_last_step`` to
    finalise — this endpoint does not mutate the user model directly.
    """
    return {"status": "disabled", "note": "Clear user.totp_secret to finalise."}
'''


def add_mfa(inp: ToolInput) -> ToolResult:
    start = time.monotonic()
    project = Path(inp.project_dir)

    err = validate_project_dir(inp.project_dir)
    if err:
        return ToolResult(status="error", error=err, execution_time_ms=_elapsed_ms(start))

    from adapt.contracts.prerequisites import ensure_prerequisites, Prereq

    prereq_errors, scaffolded = ensure_prerequisites(
        inp.project_dir,
        Prereq.CONFIG_SETTINGS,
        Prereq.REQUIREMENTS_TXT,
        Prereq.ROUTES_INIT,
        auto_scaffold=not inp.dry_run,
    )
    if prereq_errors:
        return ToolResult(
            status="error",
            error="Prerequisites not met:\n" + "\n".join(f"  - {e}" for e in prereq_errors),
            notes=["Generate a base project first via fastapi_generate_project."],
            execution_time_ms=_elapsed_ms(start),
        )

    files_created: list[str] = list(scaffolded or [])
    app_dir = project / "app"
    glue_file = app_dir / "mfa.py"

    if glue_file.exists() and "TotpVerifierAdapter" in glue_file.read_text():
        return ToolResult(
            status="no_op",
            notes=["MFA already wired via the TotpVerifier adapter."],
            execution_time_ms=_elapsed_ms(start),
        )

    if inp.dry_run:
        return ToolResult(
            status="success",
            warnings=[_WARN_NOT_AUTO_ENFORCED],
            notes=[
                "[dry_run] Would copy TotpVerifier primitive + adapter and write app/mfa.py + _mfa_example.py."
            ],
            next_steps=["Re-run without dry_run=True to apply."],
            execution_time_ms=_elapsed_ms(start),
        )

    from generators.scaffold_venous import ensure_primitives

    manifest = ensure_primitives(
        str(project),
        names=["core.venous.auth.TotpVerifier"],
        adapters=["core.venous._adapters.fastapi.TotpVerifierAdapter"],
    )
    files_created.append(manifest.path)

    app_dir.mkdir(parents=True, exist_ok=True)
    glue_file.write_text(_GLUE)
    files_created.append(str(glue_file))

    # Emit the concrete wired example so the LLM driver / developer has
    # an exact login-flow snippet to copy — not just a warning.
    routes_dir = app_dir / "api" / "routes"
    routes_dir.mkdir(parents=True, exist_ok=True)
    example_file = routes_dir / "_mfa_example.py"
    if not example_file.exists():
        example_file.write_text(_MFA_EXAMPLE)
        files_created.append(str(example_file))

    # Emit a real, mounted MFA router (prefix /auth/mfa) and register it in
    # the project's route registry so enrollment/challenge endpoints exist.
    files_modified: list[str] = []
    mfa_router_file = routes_dir / "mfa.py"
    if not mfa_router_file.exists():
        mfa_router_file.write_text(_MFA_ROUTER)
        files_created.append(str(mfa_router_file))

    routes_init = app_dir / "routes" / "__init__.py"
    if routes_init.exists() and _patch_routes_init(routes_init):
        files_modified.append(str(routes_init))

    for path_str in files_created:
        p = Path(path_str)
        if p.suffix == ".py" and p.is_file():
            try:
                ast.parse(p.read_text())
            except SyntaxError as exc:
                return ToolResult(
                    status="error",
                    error=f"Generated file has syntax error: {p}: {exc}",
                    execution_time_ms=_elapsed_ms(start),
                )

    return ToolResult(
        status="success",
        files_created=files_created,
        files_modified=files_modified,
        warnings=[_WARN_NOT_AUTO_ENFORCED],
        notes=[
            "Shipped primitive: core.venous.auth.TotpVerifier (RFC 6238 TOTP, replay-safe).",
            "Shipped adapter: TotpVerifierAdapter (install + verify_code + get_verifier).",
            "Wrote app/mfa.py — call install_mfa(app) from main.py.",
            "Wrote app/api/routes/mfa.py — a mounted /auth/mfa router "
            "(enroll / verify-enrollment / challenge / disable) registered in "
            "app/routes/__init__.py.",
            "Wrote app/api/routes/_mfa_example.py — exact login-flow TOTP verify snippet.",
            "Missing user-model fields: totp_secret (bytes|None) + totp_last_step (int).",
        ],
        next_steps=[
            "STEP 1 — add `totp_secret: bytes | None` and `totp_last_step: int = 0` to your User model.",
            "STEP 2 — call `install_mfa(app)` in main.py lifespan (after app creation).",
            "STEP 3 — in your login route (after password check): call verify_code(verifier, secret=user.totp_secret, code=body.totp_code, last_step=user.totp_last_step).",
            "STEP 4 — persist the returned step as user.totp_last_step before issuing the access token.",
            "See app/api/routes/_mfa_example.py for the exact copy-paste implementation.",
        ],
        execution_time_ms=_elapsed_ms(start),
    )


def _patch_routes_init(routes_init: Path) -> bool:
    """Register the mfa router in ``app/routes/__init__.py`` idempotently.

    Returns ``True`` when the registry is modified, ``False`` when the
    import line is already present.
    """
    src = routes_init.read_text()
    import_line = "from app.api.routes.mfa import router as mfa_router"
    include_line = "api_router.include_router(mfa_router)"
    if import_line in src:
        return False
    lines = src.splitlines()
    last_app_import_idx = -1
    for idx, line in enumerate(lines):
        if line.startswith("from app."):
            last_app_import_idx = idx
    if last_app_import_idx == -1:
        for idx, line in enumerate(lines):
            if "api_router" in line and "APIRouter()" in line:
                last_app_import_idx = idx - 1
                break
    lines.insert(last_app_import_idx + 1, import_line)
    last_include_idx = -1
    for idx, line in enumerate(lines):
        if line.startswith("api_router.include_router"):
            last_include_idx = idx
    if last_include_idx == -1:
        for idx, line in enumerate(lines):
            if "api_router" in line and "APIRouter()" in line:
                last_include_idx = idx
                break
    lines.insert(last_include_idx + 1, include_line)
    routes_init.write_text("\n".join(lines) + ("\n" if src.endswith("\n") else ""))
    return True


def _elapsed_ms(start: float) -> int:
    return int((time.monotonic() - start) * 1000)
