from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class EnvSecretProviderProtocol(Protocol):
    """Auto-inferred Protocol surface for `EnvSecretProvider`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_staging/`.
    """

    def get(self, name: str, default: str = '') -> str: ...
    def set(self, name: str, value: str) -> None: ...
