from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class AuthMixinProtocol(Protocol):
    """Auto-inferred Protocol surface for `AuthMixin`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    def login(self) -> None: ...
    def refresh_token(self) -> None: ...
