from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class CSRFProtectionProtocol(Protocol):
    """Auto-inferred Protocol surface for `CSRFProtection`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    def generate_token(self) -> str: ...
    def validate_token(self, token: str) -> bool: ...
    def get_csrf_cookie(self, response: Response, token: str) -> None: ...
