"""Emitted-project audit — verify compose tools never red-line the GENERATED suite.

This is the regression net for the bug class the first external ("linkpocket")
cold run exposed on 2026-05-26. Two failures were found in
``add_cursor_pagination`` that nine internal audit waves had missed:

1. **Silent suite breakage.** The tool mutated the shared list-response schema
   (dropped ``count`` from ``<Model>sPublic``) as a side effect but did NOT
   update the scaffold's own generated tests — turning a green emitted suite
   red after a *valid* compose. ``meta_audit`` could not catch it: it only
   checks kit integrity, never the emitted project.
2. **Idempotency claim false.** Contract §A1 promises every extend tool returns
   ``no_op`` on re-run via a fingerprint; this tool returned ``success`` twice.

Both bugs hid for nine waves because the unit-test fixtures scaffold a model
named ``Item``, so a hardcoded ``crud/item.py`` fingerprint always resolved
in-test. They only surfaced on a real project with a differently-named model.

So this harness deliberately scaffolds with a **non-"Item" model**
(``Bookmark``), then for each contract-touching compose tool asserts the
end-to-end invariant that the unit tests cannot:

    baseline emitted pytest GREEN
      -> compose returns "success"
      -> emitted pytest STILL GREEN (no regression, same pass count)
      -> 2nd compose returns "no_op" (idempotent)
      -> every emitted .py still parses

Runs as a standalone script or via pytest::

    # Standalone (this is how `make test` / audit_l1 invokes it)
    PYTHONPATH=. python3 tests/test_emitted_project_audit.py

    # Via pytest
    PYTHONPATH=. pytest tests/test_emitted_project_audit.py -v

Exit code 0 -> all tools clean; 1 -> one or more regressed.
"""

from __future__ import annotations

import ast
import importlib
import re
import secrets
import subprocess
import sys
import tempfile
from pathlib import Path

import pytest

from adapt.contracts import ToolInput
from tests.common.fixture_factory import create_fixture_project

# ---------------------------------------------------------------------------
# Tools under audit
# ---------------------------------------------------------------------------
# The crud_data family — every tool that mutates the emitted model's schema,
# CRUD, routes or tests. These are exactly the tools that *can* desync the
# generated suite, so they are the ones worth running the emitted pytest
# against. Add a tool here the moment it touches a response contract.
CONTRACT_COMPOSE_TOOLS: list[tuple[str, str]] = [
    ("add_cursor_pagination", "adapt.extend.crud_data.add_cursor_pagination"),
    ("add_search", "adapt.extend.crud_data.add_search"),
    ("add_soft_delete", "adapt.extend.crud_data.add_soft_delete"),
    ("add_audit_log", "adapt.extend.crud_data.add_audit_log"),
    ("add_bulk_operations", "adapt.extend.crud_data.add_bulk_operations"),
    ("add_data_export", "adapt.extend.crud_data.add_data_export"),
    ("add_file_upload", "adapt.extend.crud_data.add_file_upload"),
]

# Deliberately NOT "Item": the hardcoded-fingerprint bug only surfaces on a
# model the fixtures never use. "Bookmark" echoes the linkpocket cold run.
_AUDIT_MODEL = "Bookmark"

# The generated login tests authenticate as the configured superuser with this
# exact password (see generators/testing/test_suite.py), so the emitted suite
# is only fully green when the project is configured with a superuser. The
# fixture factory leaves FIRST_SUPERUSER_* empty on purpose; we supply a valid
# pair here so the BASELINE is green and any post-compose red is the tool's
# fault, not a missing seed.
_SUPERUSER_EMAIL = "admin@example.com"
_SUPERUSER_PASSWORD = "testpassword123"

_PYTEST_TIMEOUT_S = 120

_SUMMARY_RE = re.compile(r"(\d+)\s+(passed|failed|error|errors)")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _scaffold_audit_project(tmp_dir: Path) -> Path:
    """Scaffold a fresh project with a non-"Item" model and a seeded superuser.

    Args:
        tmp_dir: Parent directory the project is created inside.

    Returns:
        Path to the generated project root, configured so its emitted pytest
        suite is fully green before any compose tool runs.
    """
    project_dir = create_fixture_project(
        name="bookmarkapp",
        models={_AUDIT_MODEL: {"url": "str", "title": "str"}},
        tmp_dir=tmp_dir,
    )
    # Overwrite the fixture's no-seed .env so the generated login tests pass.
    (project_dir / ".env").write_text(
        "# Generated by test_emitted_project_audit for test-only use.\n"
        f"SECRET_KEY={secrets.token_hex(32)}\n"
        "ENVIRONMENT=local\n"
        f"FIRST_SUPERUSER_EMAIL={_SUPERUSER_EMAIL}\n"
        f"FIRST_SUPERUSER_PASSWORD={_SUPERUSER_PASSWORD}\n",
        encoding="utf-8",
    )
    return project_dir


def _run_emitted_pytest(project_dir: Path) -> tuple[int, int, int, str]:
    """Run the emitted project's own pytest suite in a subprocess.

    Args:
        project_dir: Root of the generated project.

    Returns:
        Tuple of (returncode, passed_count, failed_count, summary_line).
        ``passed``/``failed`` are -1 when the summary line is unparseable
        (e.g. a collection error), which the caller treats as a failure.
    """
    proc = subprocess.run(
        [sys.executable, "-m", "pytest", "tests/", "-q", "--no-header"],
        cwd=str(project_dir),
        capture_output=True,
        text=True,
        timeout=_PYTEST_TIMEOUT_S,
    )
    summary = proc.stdout.strip().splitlines()[-1] if proc.stdout.strip() else ""
    passed = failed = 0
    found = False
    for count, kind in _SUMMARY_RE.findall(summary):
        found = True
        if kind == "passed":
            passed = int(count)
        else:  # failed / error / errors
            failed += int(count)
    if not found:
        passed = failed = -1
    return proc.returncode, passed, failed, summary or "(no pytest output)"


def _assert_all_py_parse(project_dir: Path) -> None:
    """Raise AssertionError if any emitted .py file fails ``ast.parse``."""
    for py_file in sorted(project_dir.rglob("*.py")):
        try:
            ast.parse(py_file.read_text(encoding="utf-8"))
        except SyntaxError as exc:  # pragma: no cover - failure path
            raise AssertionError(
                f"compose corrupted emitted file {py_file.name}: {exc}"
            ) from exc


def _audit_tool(name: str, module: str) -> list[str]:
    """Run the full emitted-project audit cycle for one compose tool.

    Args:
        name: Tool function name (also the module's exported callable).
        module: Dotted import path of the tool module.

    Returns:
        A list of failure strings; empty means the tool passed cleanly.
    """
    failures: list[str] = []
    tool = getattr(importlib.import_module(module), name)

    with tempfile.TemporaryDirectory() as tmp:
        project_dir = _scaffold_audit_project(Path(tmp))

        # 1. Baseline must be green, or the assertion below is meaningless.
        rc0, pass0, fail0, sum0 = _run_emitted_pytest(project_dir)
        if rc0 != 0 or fail0 != 0:
            failures.append(
                f"{name}: BASELINE emitted suite not green ({sum0}) — "
                "cannot attribute post-compose failures to the tool."
            )
            return failures

        # 2. Compose must succeed.
        r1 = tool(ToolInput(project_dir=str(project_dir)))
        if r1.status != "success":
            failures.append(
                f"{name}: first compose returned {r1.status!r} "
                f"(error={r1.error!r}), expected 'success'."
            )
            return failures

        # 3. Emitted suite must STILL be green — and not by silently dropping
        #    tests: the pass count must not fall below baseline. (bug-class #1)
        rc1, pass1, fail1, sum1 = _run_emitted_pytest(project_dir)
        if rc1 != 0 or fail1 != 0:
            failures.append(
                f"{name}: RED-LINED the emitted suite — baseline [{sum0}] "
                f"became [{sum1}] after a valid compose."
            )
        elif pass1 < pass0:
            failures.append(
                f"{name}: emitted pass count dropped {pass0} -> {pass1} "
                f"(tests silently removed): [{sum1}]"
            )

        # 4. Idempotency: a re-run must be a no_op. (bug-class #2)
        r2 = tool(ToolInput(project_dir=str(project_dir)))
        if r2.status != "no_op":
            failures.append(
                f"{name}: second compose returned {r2.status!r}, expected "
                "'no_op' (Contract §A1 idempotency)."
            )

        # 5. Composition must never produce unparseable Python.
        try:
            _assert_all_py_parse(project_dir)
        except AssertionError as exc:
            failures.append(str(exc))

    return failures


# ---------------------------------------------------------------------------
# Pytest entrypoint
# ---------------------------------------------------------------------------

@pytest.mark.parametrize(
    "name,module",
    CONTRACT_COMPOSE_TOOLS,
    ids=[t[0] for t in CONTRACT_COMPOSE_TOOLS],
)
def test_compose_tool_preserves_emitted_suite(name: str, module: str) -> None:
    """A compose tool must keep the emitted pytest suite green and be idempotent.

    Args:
        name: Tool callable / id.
        module: Dotted module path of the tool.
    """
    failures = _audit_tool(name, module)
    assert not failures, "\n".join(failures)


# ---------------------------------------------------------------------------
# Standalone runner (used by `make test` / audit_l1 --tests-only)
# ---------------------------------------------------------------------------

def main() -> int:
    """Audit every contract-touching compose tool against the emitted suite.

    Returns:
        0 if all tools pass, 1 if any regressed.
    """
    all_failures: list[str] = []
    for name, module in CONTRACT_COMPOSE_TOOLS:
        print(f"Auditing {name} against emitted suite...", flush=True)
        failures = _audit_tool(name, module)
        if failures:
            all_failures.extend(failures)
            for f in failures:
                print(f"  FAIL  {f}")
        else:
            print(f"  PASS  {name}")

    print(f"\n{'=' * 60}")
    if all_failures:
        print(
            f"Emitted-project audit: "
            f"{len(CONTRACT_COMPOSE_TOOLS) - len(all_failures)}/"
            f"{len(CONTRACT_COMPOSE_TOOLS)} tools clean"
        )
        return 1
    print(
        f"Emitted-project audit: {len(CONTRACT_COMPOSE_TOOLS)}/"
        f"{len(CONTRACT_COMPOSE_TOOLS)} tools keep the emitted suite green "
        "and compose idempotently."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
