from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class MemoryGuardProtocol(Protocol):
    """Auto-inferred Protocol surface for `MemoryGuard`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    @property
    def threshold(self) -> float: ...
    def check(self, device = None) -> None: ...
