"""Protocol for CircuitBreaker — generated from CircuitBreaker.py."""

from __future__ import annotations

from typing import Any, Optional, Protocol, runtime_checkable

@runtime_checkable
class CircuitBreaker(Protocol):
    """CircuitBreaker primitive — three-state stability guard for a failing dependency."""

    async def call(self) -> T: ...
    def on_success(self, elapsed_ms: float) -> None: ...
    def on_failure(self, exc: BaseException, elapsed_ms: float) -> None: ...
    def force_open(self, reason: str) -> None: ...
    def allow_probe(self) -> bool: ...
