"""BEHAVIOR TEST — TOOL-006 add_data_export.

Proves that the code generated by ``add_data_export`` works at **runtime**:
boots a real ASGI app and verifies the /<model>/export route is registered
and the streaming export utilities import cleanly.

Patches applied (so tests run without Docker):
- ``app/core/db.py``                → SQLite + aiosqlite (no Postgres)
- ``app/middleware/idempotency.py`` → pass-through stub (no Redis)

Run::

    PYTHONPATH=. .venv/bin/pytest adapt/extend/crud_data/test_add_data_export_behavior.py -v
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Environment setup — MUST happen before any app import
# ---------------------------------------------------------------------------
import os

os.environ.setdefault("RATE_LIMITING_ENABLED", "false")
os.environ.setdefault("ENVIRONMENT", "local")
os.environ.setdefault("SECRET_KEY", "behavior-test-data-export-secret-key-32+chars")
os.environ.pop("REDIS_URL", None)

import importlib
import sys
import textwrap
from pathlib import Path
from typing import Any

import httpx
import pytest

from adapt.contracts import ToolInput
from adapt.extend.crud_data.add_data_export import add_data_export
from tests.common.fixture_factory import create_fixture_project

# ---------------------------------------------------------------------------
# Patch templates
# ---------------------------------------------------------------------------

_SQLITE_DB_PY = textwrap.dedent("""\
    \"\"\"Patched db.py — SQLite+aiosqlite, no Docker required.\"\"\"

    from sqlalchemy import text
    from sqlalchemy.ext.asyncio import create_async_engine

    engine = create_async_engine(
        "sqlite+aiosqlite:///:memory:",
        echo=False,
        future=True,
        connect_args={"check_same_thread": False},
    )


    async def init_db() -> None:
        \"\"\"Run startup checks (connection test).\"\"\"
        async with engine.begin() as conn:
            await conn.execute(text("SELECT 1"))


    __all__ = ["engine", "init_db"]
""")

_PASSTHROUGH_IDEMPOTENCY_PY = textwrap.dedent("""\
    \"\"\"Patched idempotency.py — pass-through stub (no Redis).\"\"\"

    from __future__ import annotations

    from starlette.middleware.base import BaseHTTPMiddleware, RequestResponseEndpoint
    from starlette.requests import Request
    from starlette.responses import Response


    class IdempotencyMiddleware(BaseHTTPMiddleware):
        \"\"\"No-op pass-through stub for testing without Redis.\"\"\"

        async def dispatch(
            self,
            request: Request,
            call_next: RequestResponseEndpoint,
        ) -> Response:
            return await call_next(request)
""")


def _patch_project(project_dir: Path) -> None:
    (project_dir / "app" / "core" / "db.py").write_text(_SQLITE_DB_PY)
    idempotency = project_dir / "app" / "middleware" / "idempotency.py"
    if idempotency.exists():
        idempotency.write_text(_PASSTHROUGH_IDEMPOTENCY_PY)


def _load_app(project_dir: Path) -> Any:
    _orig_path = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        app_module = importlib.import_module("app.main")
    finally:
        sys.path[:] = _orig_path
    return app_module.app


def _setup_project() -> tuple[Path, Any]:
    project_dir = create_fixture_project(name="export_behavior")
    result = add_data_export(ToolInput(project_dir=str(project_dir)))
    assert result.status == "success", (
        f"add_data_export failed: {result.error}\nnotes: {result.notes}"
    )
    _patch_project(project_dir)
    asgi_app = _load_app(project_dir)
    return project_dir, asgi_app


# ---------------------------------------------------------------------------
# Module-level shared state
# ---------------------------------------------------------------------------

_PROJECT_DIR: Path | None = None
_ASGI_APP: Any = None


def _get_shared_app() -> tuple[Path, Any]:
    global _PROJECT_DIR, _ASGI_APP
    if _PROJECT_DIR is None:
        _PROJECT_DIR, _ASGI_APP = _setup_project()
    return _PROJECT_DIR, _ASGI_APP


@pytest.fixture(scope="module")
def project_dir_and_app() -> tuple[Path, Any]:
    return _get_shared_app()


@pytest.fixture(scope="module")
def project_dir(project_dir_and_app: tuple[Path, Any]) -> Path:
    return project_dir_and_app[0]


@pytest.fixture(scope="module")
def asgi_app(project_dir_and_app: tuple[Path, Any]) -> Any:
    return project_dir_and_app[1]


# ---------------------------------------------------------------------------
# B-01: app boots cleanly after data_export applied
# ---------------------------------------------------------------------------


@pytest.mark.anyio
async def test_b01_healthz_returns_200(asgi_app: Any) -> None:
    """B-01: GET /healthz returns 200 after data_export wired."""
    transport = httpx.ASGITransport(app=asgi_app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.get("/healthz")
    assert response.status_code == 200, (
        f"Expected 200, got {response.status_code}; body: {response.text}"
    )


# ---------------------------------------------------------------------------
# B-02: /items/export route is registered (not 404)
# ---------------------------------------------------------------------------


@pytest.mark.anyio
async def test_b02_export_route_registered(asgi_app: Any) -> None:
    """B-02: GET /api/v1/items/export route exists (not 404)."""
    transport = httpx.ASGITransport(app=asgi_app, raise_app_exceptions=False)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.get("/api/v1/items/export?format=csv")
    assert response.status_code != 404, (
        f"GET /api/v1/items/export not registered: {response.status_code}; body: {response.text}"
    )


# ---------------------------------------------------------------------------
# B-03: streaming utilities import cleanly (memory-bounded API surface)
# ---------------------------------------------------------------------------


def test_b03_export_utilities_import(project_dir: Path) -> None:
    """B-03: export_csv/ndjson/xlsx/parquet generators import and are async."""
    import inspect

    _orig_path = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        from app.core.export import (  # type: ignore[import-not-found]
            SENSITIVE_COLUMNS,
            export_csv,
            export_ndjson,
            export_parquet,
            export_xlsx,
        )

        # All exporters must be async generator functions.
        for fn in (export_csv, export_ndjson, export_xlsx, export_parquet):
            assert inspect.isasyncgenfunction(fn), (
                f"{fn.__name__} must be an async generator (streaming) — got {type(fn).__name__}"
            )
        # Sensitive columns must be a frozenset and include hashed_password.
        assert isinstance(SENSITIVE_COLUMNS, frozenset), "SENSITIVE_COLUMNS must be frozenset"
        assert "hashed_password" in SENSITIVE_COLUMNS, "hashed_password must be excluded"
    finally:
        sys.path[:] = _orig_path


# ---------------------------------------------------------------------------
# B-04: rerun is no_op (idempotency invariant)
# ---------------------------------------------------------------------------


def test_b04_rerun_is_noop(project_dir: Path) -> None:
    """B-04: A second run returns no_op without re-emitting files."""
    r2 = add_data_export(ToolInput(project_dir=str(project_dir)))
    assert r2.status == "no_op", f"Expected no_op on rerun, got {r2.status}: {r2.error}"
