"""BEHAVIOR TEST — TOOL-001 add_soft_delete (P1-#14).

Proves that the code generated by ``add_soft_delete`` works at **runtime**
under the SPEC-v2 design (#19): boots a real ASGI app and verifies:

  * the SPEC-v2 surface is wired in: ``CRUDBase.delete`` is the ``_sd_delete``
    soft-flip override, reads are filtered by the GLOBAL ``do_orm_execute``
    listener (not per-query rebinds);
  * the patched delete() flips ``is_deleted=True`` instead of issuing SQL DELETE;
  * opt-in == inheriting ``SoftDeleteMixin``: the global filter then excludes
    soft-deleted rows from reads, with ``include_deleted=True`` as the opt-out;
  * the domain model gains the deletion columns by inheriting SoftDeleteMixin
    (columns live on the emitted mixin);
  * per-model opt-out (F-04): a model WITHOUT ``is_deleted`` falls through to
    hard-delete (so auth/infra tables keep PII/rotation correctness);
  * the orphan ``app/soft_delete.py`` UoW shim is NOT emitted.

Patches applied (so tests run without Docker):
- ``app/core/db.py``               → SQLite + aiosqlite (no Postgres)
- ``app/middleware/idempotency.py`` → pass-through stub (no Redis)
- ``REDIS_URL`` env var             → removed
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Environment setup — MUST happen before any app import
# ---------------------------------------------------------------------------
import os

os.environ.setdefault("RATE_LIMITING_ENABLED", "false")
os.environ.setdefault("ENVIRONMENT", "local")
os.environ.setdefault("SECRET_KEY", "behavior-test-soft-delete-secret-key-32+!")
os.environ.pop("REDIS_URL", None)

import importlib
import sys
import textwrap
from pathlib import Path
from typing import Any

import httpx
import pytest

from adapt.contracts import ToolInput
from adapt.extend.crud_data.add_soft_delete import add_soft_delete
from tests.common.fixture_factory import create_fixture_project

# ---------------------------------------------------------------------------
# Patch templates
# ---------------------------------------------------------------------------

_SQLITE_DB_PY = textwrap.dedent("""\
    \"\"\"Patched db.py — SQLite+aiosqlite, no Docker required.\"\"\"

    from sqlalchemy import text
    from sqlalchemy.ext.asyncio import create_async_engine

    engine = create_async_engine(
        "sqlite+aiosqlite:///:memory:",
        echo=False,
        future=True,
        connect_args={"check_same_thread": False},
    )


    async def init_db() -> None:
        \"\"\"Run startup checks (connection test).\"\"\"
        async with engine.begin() as conn:
            await conn.execute(text("SELECT 1"))


    __all__ = ["engine", "init_db"]
""")

_PASSTHROUGH_IDEMPOTENCY_PY = textwrap.dedent("""\
    \"\"\"Patched idempotency.py — pass-through stub (no Redis).\"\"\"

    from __future__ import annotations

    from starlette.middleware.base import BaseHTTPMiddleware, RequestResponseEndpoint
    from starlette.requests import Request
    from starlette.responses import Response


    class IdempotencyMiddleware(BaseHTTPMiddleware):
        \"\"\"No-op pass-through stub for testing without Redis.\"\"\"

        async def dispatch(
            self,
            request: Request,
            call_next: RequestResponseEndpoint,
        ) -> Response:
            return await call_next(request)
""")


def _patch_project(project_dir: Path) -> None:
    (project_dir / "app" / "core" / "db.py").write_text(_SQLITE_DB_PY)
    idempotency_path = project_dir / "app" / "middleware" / "idempotency.py"
    if idempotency_path.exists():
        idempotency_path.write_text(_PASSTHROUGH_IDEMPOTENCY_PY)


def _load_app(project_dir: Path) -> Any:
    _orig_path = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        app_module = importlib.import_module("app.main")
    finally:
        sys.path[:] = _orig_path
    return app_module.app


def _setup_project() -> tuple[Path, Any]:
    project_dir = create_fixture_project(name="sd_behavior")
    result = add_soft_delete(ToolInput(project_dir=str(project_dir)))
    assert result.status == "success", (
        f"add_soft_delete failed: {result.error}\nnotes: {result.notes}"
    )
    _patch_project(project_dir)
    asgi_app = _load_app(project_dir)
    return project_dir, asgi_app


# ---------------------------------------------------------------------------
# Module-level shared state
# ---------------------------------------------------------------------------

_PROJECT_DIR: Path | None = None
_ASGI_APP: Any = None


def _get_shared_app() -> tuple[Path, Any]:
    global _PROJECT_DIR, _ASGI_APP
    if _PROJECT_DIR is None:
        _PROJECT_DIR, _ASGI_APP = _setup_project()
    return _PROJECT_DIR, _ASGI_APP


@pytest.fixture(scope="module")
def project_dir_and_app() -> tuple[Path, Any]:
    return _get_shared_app()


@pytest.fixture(scope="module")
def project_dir(project_dir_and_app: tuple[Path, Any]) -> Path:
    return project_dir_and_app[0]


@pytest.fixture(scope="module")
def asgi_app(project_dir_and_app: tuple[Path, Any]) -> Any:
    return project_dir_and_app[1]


# ---------------------------------------------------------------------------
# B-01: App boots after CRUDBase patched
# ---------------------------------------------------------------------------


@pytest.mark.anyio
async def test_b01_healthz_returns_200(asgi_app: Any) -> None:
    """B-01: GET /healthz returns 200 after CRUDBase patched in place."""
    transport = httpx.ASGITransport(app=asgi_app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.get("/healthz")
    assert response.status_code == 200, (
        f"Expected 200, got {response.status_code}; body: {response.text}"
    )


# ---------------------------------------------------------------------------
# B-02: SPEC-v2 — delete() is rebound to the soft-delete-aware variant; reads
# are filtered GLOBALLY (do_orm_execute), so get/get_multi are NOT rebound.
# ---------------------------------------------------------------------------


def test_b02_crudbase_methods_rebound(project_dir: Path) -> None:
    """B-02: SPEC-v2 — only CRUDBase.delete is rebound to ``_sd_delete``.

    Re-anchored from the OLD design (which reassigned CRUDBase.get / get_multi /
    delete to per-query ``_sd_*`` filtering callables). SPEC-v2 (#19) moves read
    exclusion to a single GLOBAL ``do_orm_execute`` listener
    (app/core/soft_delete_filter.py) keyed off SoftDeleteMixin, so the read
    methods are deliberately left untouched — rebinding them would shadow the
    global filter. We assert the real shipped mechanism at runtime:

      * the emitted ``soft_delete_filter`` module registers a ``do_orm_execute``
        listener (the global read filter exists);
      * ``CRUDBase.delete`` is the ``_sd_delete`` soft-flip override;
      * ``CRUDBase.get`` / ``get_multi`` are NOT rebound to any ``_sd_*`` variant.
    """
    _orig_path = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        from app.crud import base as crud_base_mod

        # delete() is the soft-delete-aware override (INV-SD-03).
        assert crud_base_mod.CRUDBase.delete.__name__ == "_sd_delete", (
            f"CRUDBase.delete not rebound; got {crud_base_mod.CRUDBase.delete.__name__}"
        )
        # Reads are filtered globally — they must NOT be reassigned to _sd_* here.
        assert not crud_base_mod.CRUDBase.get.__name__.startswith("_sd_"), (
            "CRUDBase.get must NOT be rebound — reads are filtered by the global "
            f"do_orm_execute listener under SPEC-v2; got {crud_base_mod.CRUDBase.get.__name__}"
        )
        assert not crud_base_mod.CRUDBase.get_multi.__name__.startswith("_sd_"), (
            "CRUDBase.get_multi must NOT be rebound — reads are filtered by the "
            f"global filter; got {crud_base_mod.CRUDBase.get_multi.__name__}"
        )

        # The global read filter is the SPEC-v2 mechanism: importing the emitted
        # module registers a do_orm_execute listener on Session (INV-SD-01).
        from sqlalchemy import event
        from sqlalchemy.orm import Session

        from app.core import soft_delete_filter  # noqa: F401  (registers the listener)

        assert event.contains(
            Session, "do_orm_execute", soft_delete_filter._enforce_soft_delete_filter
        ), (
            "soft_delete_filter must register a do_orm_execute listener on Session "
            "(global read exclusion, INV-SD-01)."
        )
    finally:
        sys.path[:] = _orig_path


# ---------------------------------------------------------------------------
# B-03: P1-#14 — orphan UoW shim NOT emitted
# ---------------------------------------------------------------------------


def test_b03_no_orphan_uow_shim(project_dir: Path) -> None:
    """B-03: P1-#14 — app/soft_delete.py is dead code and must NOT exist."""
    orphan = project_dir / "app" / "soft_delete.py"
    assert not orphan.exists(), (
        "app/soft_delete.py is the orphan UoW shim (no caller) — must not be emitted"
    )


# ---------------------------------------------------------------------------
# B-04: SPEC-v2 — the domain model gains deletion columns via SoftDeleteMixin
# inheritance; the columns themselves live on the emitted mixin.
# ---------------------------------------------------------------------------


def test_b04_is_deleted_column_injected(project_dir: Path) -> None:
    """B-04: SPEC-v2 — the model inherits SoftDeleteMixin; the mixin declares the 3 columns.

    Re-anchored from the OLD design (an ``is_deleted``/``deleted_at`` column
    literal + Boolean/DateTime imports injected directly into every model file).
    SPEC-v2 (#19) instead emits ``app/models/mixins.py::SoftDeleteMixin`` carrying
    the deletion columns and rewrites each domain model's bases to inherit it, so
    the global do_orm_execute listener can key off that single class. We assert
    the real shipped behaviour: the model imports + actually inherits the mixin
    (AST), and the mixin declares all three deletion columns.
    """
    model_file = project_dir / "app" / "models" / "item.py"
    assert model_file.exists(), "item.py model missing"
    body = model_file.read_text()

    # The model imports + inherits the mixin (soft-delete is inert otherwise).
    assert "from app.models.mixins import SoftDeleteMixin" in body, (
        "Model must import SoftDeleteMixin (BUG C regression — soft-delete inert)."
    )
    import ast as _ast

    tree = _ast.parse(body)
    item_cls = next(
        (n for n in _ast.walk(tree) if isinstance(n, _ast.ClassDef) and n.name == "Item"),
        None,
    )
    assert item_cls is not None, "Item class not found in model file"
    base_names = {b.id for b in item_cls.bases if isinstance(b, _ast.Name)}
    assert "SoftDeleteMixin" in base_names, (
        "Item must inherit SoftDeleteMixin so it gains the deletion columns."
    )

    # The deletion columns live on the emitted mixin (single source of truth).
    mixin_file = project_dir / "app" / "models" / "mixins.py"
    assert mixin_file.exists(), "app/models/mixins.py not emitted — columns have no home."
    mixin_src = mixin_file.read_text()
    assert "class SoftDeleteMixin" in mixin_src, "SoftDeleteMixin class not emitted."
    for col in ("is_deleted", "deleted_at", "deleted_by"):
        assert col in mixin_src, f"{col} column NOT defined on SoftDeleteMixin."
    assert "Boolean" in mixin_src and "DateTime" in mixin_src, (
        "Boolean/DateTime must be imported by the mixin (it declares those columns)."
    )


# ---------------------------------------------------------------------------
# B-05: F-04 per-model opt-out — model WITHOUT is_deleted hard-deletes
# ---------------------------------------------------------------------------


@pytest.mark.anyio
async def test_b05_per_model_opt_out_hard_deletes(project_dir: Path) -> None:
    """B-05: F-04 — the patched delete() falls through to SQL DELETE for opt-out models.

    Constructs a model WITHOUT ``is_deleted`` in-memory and exercises
    CRUDBase.delete on it; the patched code must call session.delete (hard
    delete) because hasattr(obj, 'is_deleted') is False.
    """
    _orig_path = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        from app.crud.base import CRUDBase  # noqa: F401  (load the patched class)
        from sqlalchemy import Column, Integer, String
        from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine
        from sqlalchemy.orm import DeclarativeBase

        class _Base(DeclarativeBase):
            pass

        class OptOutModel(_Base):
            __tablename__ = "optout_model"
            id = Column(Integer, primary_key=True)
            name = Column(String, nullable=False)

        engine = create_async_engine("sqlite+aiosqlite:///:memory:")
        async with engine.begin() as conn:
            await conn.run_sync(_Base.metadata.create_all)
        session_factory = async_sessionmaker(engine, expire_on_commit=False)

        crud = CRUDBase(OptOutModel)
        async with session_factory() as session:
            obj = OptOutModel(id=1, name="ephemeral")
            session.add(obj)
            await session.flush()
            deleted = await crud.delete(session, 1)
            await session.commit()
            assert deleted is not None, "delete() must return the deleted object"
            # Hard-delete: a subsequent get() must return None because the row is gone.
            re_fetched = await crud.get(session, 1)
            assert re_fetched is None, (
                "Opt-out model must hard-delete; got a row back (F-04 regression)"
            )
        await engine.dispose()
    finally:
        sys.path[:] = _orig_path


# ---------------------------------------------------------------------------
# B-06: SPEC-v2 opt-in — a SoftDeleteMixin model soft-deletes (flag flip, no
# SQL DELETE) AND the global filter excludes it from reads, with include_deleted
# as the opt-out.
# ---------------------------------------------------------------------------


@pytest.mark.anyio
async def test_b06_opt_in_soft_deletes(project_dir: Path) -> None:
    """B-06: SPEC-v2 opt-in — a model that inherits SoftDeleteMixin is soft-deleted
    (is_deleted flipped True, no SQL DELETE) and is filtered out of reads by the
    GLOBAL do_orm_execute listener; ``include_deleted=True`` is the read opt-out.

    Re-anchored from the OLD design, where opt-in was an ad-hoc ``is_deleted``
    column on a standalone model and read exclusion came from a per-query
    ``CRUDBase.get`` rebind. SPEC-v2 (#19) makes opt-in mean *inheriting the
    emitted SoftDeleteMixin*: the global filter (app/core/soft_delete_filter.py)
    keys off that mixin via ``with_loader_criteria``, so reads exclude
    soft-deleted rows transparently while ``execution_options(include_deleted=
    True)`` opts back in. We exercise the REAL shipped artefacts: the emitted
    mixin (so the row is genuinely filterable) + the emitted filter module (so
    the listener is registered).
    """
    _orig_path = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        from app.crud.base import CRUDBase
        from app.models.mixins import SoftDeleteMixin
        from sqlalchemy import Column, Integer, String, Uuid, select
        from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine
        from sqlalchemy.orm import DeclarativeBase

        from app.core import soft_delete_filter  # noqa: F401  (registers the listener)

        class _Base(DeclarativeBase):
            pass

        # SoftDeleteMixin.deleted_by is an FK to ``users.id`` — provide a minimal
        # users table in the same metadata so the FK resolves at create_all.
        class _Users(_Base):
            __tablename__ = "users"
            id = Column(Uuid, primary_key=True)

        # Opt-in == inheriting the emitted SoftDeleteMixin (gains the 3 columns
        # AND is keyed by the global filter).
        class SoftModel(SoftDeleteMixin, _Base):
            __tablename__ = "soft_model"
            id = Column(Integer, primary_key=True)
            name = Column(String, nullable=False)

        engine = create_async_engine("sqlite+aiosqlite:///:memory:")
        async with engine.begin() as conn:
            await conn.run_sync(_Base.metadata.create_all)
        session_factory = async_sessionmaker(engine, expire_on_commit=False)

        crud = CRUDBase(SoftModel)
        async with session_factory() as session:
            obj = SoftModel(id=1, name="alive")
            session.add(obj)
            await session.flush()
            await crud.delete(session, 1)
            await session.commit()

        async with session_factory() as session:
            # Default reads go through the global do_orm_execute filter and must
            # exclude the soft-deleted row.
            filtered = await crud.get(session, 1)
            assert filtered is None, (
                "Global do_orm_execute filter must exclude soft-deleted rows from "
                "default reads (INV-SD-01 regression)."
            )
            # Opt-out: include_deleted=True returns the soft-deleted row.
            opted_in = await session.execute(
                select(SoftModel).where(SoftModel.id == 1).execution_options(include_deleted=True)
            )
            row = opted_in.scalar_one_or_none()
            assert row is not None, (
                "Soft-delete must NOT issue SQL DELETE; include_deleted=True must "
                "return the row (P1-#14 / opt-out regression)."
            )
            assert row.is_deleted is True, "is_deleted flag must be flipped True"
            assert row.deleted_at is not None, "deleted_at must be stamped"
        await engine.dispose()
    finally:
        sys.path[:] = _orig_path
