"""
SKILL-001 Deployment Tool: Generate production-grade Kubernetes manifests.

Generates a complete set of K8s manifests for a FastAPI application with
SOTA patterns: zero-downtime rolling updates (maxSurge=1, maxUnavailable=0),
3-level probes (liveness/readiness/startup), preStop hook for connection
draining, HPA with scale-up/down stabilization, PDB, resource limits,
security context, and ConfigMap/Secret references.

Generated manifests:
    deployment.yaml  — Deployment with rolling update, probes, preStop, security context
    service.yaml     — ClusterIP Service with named port
    hpa.yaml         — HorizontalPodAutoscaler with CPU/memory metrics and behavior policies
    pdb.yaml         — PodDisruptionBudget with minAvailable
"""

from __future__ import annotations

MCP_TOOL = {
    'name': 'fastapi_deployment_generate_k8s_bundle',
    'description': 'Generate production Kubernetes manifests for FastAPI: Deployment, Service, HPA, PDB with rolling updates and probes.',
    'tags': ['deployment', 'generator'],
    'entry': 'generate_k8s_manifests',
    'annotations': {'readOnlyHint': False, 'destructiveHint': False},
}

import sys
import textwrap
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))
from core.models import Finding, Severity


# ---------------------------------------------------------------------------
# Deployment manifest
# ---------------------------------------------------------------------------


def _deployment_yaml(
    app_name: str,
    image: str,
    replicas: int,
    port: int,
    env_vars: dict[str, str] | None,
    cpu_request: str,
    cpu_limit: str,
    memory_request: str,
    memory_limit: str,
    prestop_sleep: int,
    termination_grace: int,
    graceful_shutdown_timeout: int,
) -> str:
    """Generate a Deployment manifest with SOTA zero-downtime patterns."""
    # Build env section from env_vars dict
    env_section = ""
    if env_vars:
        env_lines = []
        for key, value in sorted(env_vars.items()):
            env_lines.append(f"        - name: {key}")
            env_lines.append(f'          value: "{value}"')
        env_section = "\n".join(env_lines)

    env_block = ""
    if env_section:
        env_block = f"""
        env:
{env_section}"""

    return textwrap.dedent(f"""\
        # Generated by SKILL-001 Deployment Module
        # Zero-downtime rolling update with 3-level probes
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: {app_name}
          labels:
            app: {app_name}
        spec:
          replicas: {replicas}
          revisionHistoryLimit: 5
          selector:
            matchLabels:
              app: {app_name}
          strategy:
            type: RollingUpdate
            rollingUpdate:
              maxSurge: 1            # Create 1 extra pod during update
              maxUnavailable: 0      # NEVER fewer than desired replicas
          template:
            metadata:
              labels:
                app: {app_name}
            spec:
              terminationGracePeriodSeconds: {termination_grace}
              securityContext:
                runAsNonRoot: true
                runAsUser: 10001
                runAsGroup: 10001
                fsGroup: 10001
              containers:
              - name: {app_name}
                image: {image}
                imagePullPolicy: IfNotPresent
                ports:
                - name: http
                  containerPort: {port}
                  protocol: TCP{env_block}
                envFrom:
                - configMapRef:
                    name: {app_name}-config
                    optional: true
                - secretRef:
                    name: {app_name}-secrets
                    optional: true
                resources:
                  requests:
                    cpu: "{cpu_request}"
                    memory: "{memory_request}"
                  limits:
                    cpu: "{cpu_limit}"
                    memory: "{memory_limit}"

                # --- 3-level probes ---
                # Liveness: process alive? NEVER check DB/Redis here
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: {port}
                  initialDelaySeconds: 0
                  periodSeconds: 15
                  timeoutSeconds: 3
                  failureThreshold: 3

                # Readiness: can accept traffic? Check ALL dependencies
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: {port}
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 2

                # Startup: init complete? Disables liveness/readiness until success
                startupProbe:
                  httpGet:
                    path: /startupz
                    port: {port}
                  initialDelaySeconds: 0
                  periodSeconds: 5
                  timeoutSeconds: 3
                  failureThreshold: 30   # 30 * 5s = 150s max startup time

                # --- Zero-downtime: preStop hook ---
                # Sleep gives kube-proxy/LB time to deregister endpoints
                lifecycle:
                  preStop:
                    exec:
                      command: ["sh", "-c", "sleep {prestop_sleep}"]

                securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  capabilities:
                    drop:
                      - ALL
    """)


# ---------------------------------------------------------------------------
# Service manifest
# ---------------------------------------------------------------------------


def _service_yaml(app_name: str, port: int) -> str:
    """Generate a ClusterIP Service manifest."""
    return textwrap.dedent(f"""\
        # Generated by SKILL-001 Deployment Module
        apiVersion: v1
        kind: Service
        metadata:
          name: {app_name}
          labels:
            app: {app_name}
        spec:
          type: ClusterIP
          selector:
            app: {app_name}
          ports:
          - name: http
            port: 80
            targetPort: {port}
            protocol: TCP
    """)


# ---------------------------------------------------------------------------
# HPA manifest
# ---------------------------------------------------------------------------


def _hpa_yaml(
    app_name: str,
    min_replicas: int,
    max_replicas: int,
    cpu_target: int,
    memory_target: int,
) -> str:
    """Generate an HPA manifest with CPU/memory metrics and stabilization policies."""
    return textwrap.dedent(f"""\
        # Generated by SKILL-001 Deployment Module
        # CPU target 70% leaves headroom for spikes during scale-up lag
        apiVersion: autoscaling/v2
        kind: HorizontalPodAutoscaler
        metadata:
          name: {app_name}-hpa
          labels:
            app: {app_name}
        spec:
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: {app_name}
          minReplicas: {min_replicas}
          maxReplicas: {max_replicas}
          metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: {cpu_target}
          - type: Resource
            resource:
              name: memory
              target:
                type: Utilization
                averageUtilization: {memory_target}
          behavior:
            scaleUp:
              stabilizationWindowSeconds: 60      # Prevent rapid scale-up flapping
              policies:
              - type: Pods
                value: 2                           # Add max 2 pods per event
                periodSeconds: 60
            scaleDown:
              stabilizationWindowSeconds: 300     # 5min cooldown before scale-down
              policies:
              - type: Pods
                value: 1                           # Remove max 1 pod per event
                periodSeconds: 120
    """)


# ---------------------------------------------------------------------------
# PDB manifest
# ---------------------------------------------------------------------------


def _pdb_yaml(app_name: str, min_available: int) -> str:
    """Generate a PodDisruptionBudget manifest."""
    return textwrap.dedent(f"""\
        # Generated by SKILL-001 Deployment Module
        # Ensures at least {min_available} pod(s) remain during voluntary disruptions
        # (node drain, cluster upgrades). Does NOT protect against node crashes.
        apiVersion: policy/v1
        kind: PodDisruptionBudget
        metadata:
          name: {app_name}-pdb
          labels:
            app: {app_name}
        spec:
          minAvailable: {min_available}
          selector:
            matchLabels:
              app: {app_name}
    """)


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


def _validate_config(
    app_name: str,
    replicas: int,
    min_available: int,
    min_replicas: int,
    max_replicas: int,
    prestop_sleep: int,
    termination_grace: int,
) -> list[Finding]:
    """Validate configuration and return findings for anti-patterns."""
    findings: list[Finding] = []

    if replicas < 2:
        findings.append(Finding(
            rule_id="DEPLOY-001",
            severity=Severity.HIGH,
            title="Single replica deployment",
            description=(
                f"replicas={replicas}. A single replica means zero capacity "
                "during pod restarts, deploys, and node failures. Use at least 2."
            ),
            fix_suggestion="Set replicas to at least 2 for production.",
        ))

    if min_available >= replicas:
        findings.append(Finding(
            rule_id="DEPLOY-002",
            severity=Severity.CRITICAL,
            title="PDB minAvailable equals or exceeds replica count",
            description=(
                f"minAvailable={min_available} with replicas={replicas}. "
                "This blocks ALL voluntary evictions — kubectl drain will hang "
                "forever and node upgrades become impossible."
            ),
            fix_suggestion=f"Set minAvailable to {max(1, replicas - 1)} or lower.",
        ))

    if prestop_sleep >= termination_grace:
        findings.append(Finding(
            rule_id="DEPLOY-003",
            severity=Severity.HIGH,
            title="preStop sleep exceeds terminationGracePeriodSeconds",
            description=(
                f"preStop sleep={prestop_sleep}s but terminationGracePeriodSeconds="
                f"{termination_grace}s. Kubernetes will SIGKILL the container "
                "before the sleep finishes, defeating the purpose of graceful drain."
            ),
            fix_suggestion=(
                f"Set terminationGracePeriodSeconds to at least "
                f"{prestop_sleep + 35} (preStop + graceful shutdown + buffer)."
            ),
        ))

    if min_replicas < 2:
        findings.append(Finding(
            rule_id="DEPLOY-004",
            severity=Severity.MEDIUM,
            title="HPA minReplicas is 1",
            description=(
                f"minReplicas={min_replicas}. With a single replica during low "
                "traffic, any pod failure means zero capacity until HPA scales up."
            ),
            fix_suggestion="Set HPA minReplicas to at least 2.",
        ))

    if max_replicas <= min_replicas:
        findings.append(Finding(
            rule_id="DEPLOY-005",
            severity=Severity.HIGH,
            title="HPA maxReplicas not greater than minReplicas",
            description=(
                f"maxReplicas={max_replicas}, minReplicas={min_replicas}. "
                "HPA has no room to scale — it is effectively disabled."
            ),
            fix_suggestion="Set maxReplicas to at least 2x minReplicas.",
        ))

    return findings


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------


def generate_k8s_manifests(
    app_name: str,
    image: str,
    replicas: int = 3,
    port: int = 8000,
    env_vars: dict[str, str] | None = None,
    with_hpa: bool = True,
    with_pdb: bool = True,
    *,
    cpu_request: str = "200m",
    cpu_limit: str = "500m",
    memory_request: str = "256Mi",
    memory_limit: str = "512Mi",
    cpu_target: int = 70,
    memory_target: int = 80,
    min_replicas: int = 2,
    max_replicas: int = 10,
    min_available: int = 1,
    prestop_sleep: int = 10,
    termination_grace: int = 45,
    graceful_shutdown_timeout: int = 30,
) -> dict[str, str]:
    """
    Generate production-grade Kubernetes manifests for a FastAPI application.

    Creates a complete set of K8s YAML manifests with zero-downtime rolling
    update strategy, 3-level health probes (liveness/readiness/startup),
    preStop hook for connection draining, resource limits, security context
    (non-root, read-only FS, drop all capabilities), HPA with stabilization
    policies, and PDB for disruption protection.

    Args:
        app_name: Application name used for metadata, labels, and selectors.
        image: Container image reference (e.g., "ghcr.io/org/myapi:v1.2.3").
        replicas: Number of desired pod replicas (default: 3).
        port: Container port the app listens on (default: 8000).
        env_vars: Optional dict of environment variables to inject.
        with_hpa: Generate HorizontalPodAutoscaler manifest (default: True).
        with_pdb: Generate PodDisruptionBudget manifest (default: True).
        cpu_request: CPU request for scheduler reservation (default: "200m").
        cpu_limit: CPU limit / throttle ceiling (default: "500m").
        memory_request: Memory request for scheduler reservation (default: "256Mi").
        memory_limit: Memory limit / OOMKill threshold (default: "512Mi").
        cpu_target: HPA CPU utilization target percentage (default: 70).
        memory_target: HPA memory utilization target percentage (default: 80).
        min_replicas: HPA minimum replicas (default: 2).
        max_replicas: HPA maximum replicas (default: 10).
        min_available: PDB minAvailable pods during disruption (default: 1).
        prestop_sleep: Seconds to sleep in preStop hook (default: 10).
        termination_grace: terminationGracePeriodSeconds (default: 45).
        graceful_shutdown_timeout: Uvicorn graceful shutdown timeout (default: 30).

    Returns:
        Dict mapping filename to YAML content string. Keys:
        "deployment.yaml", "service.yaml", and optionally "hpa.yaml", "pdb.yaml".

        Also includes a "findings" key with a list of Finding dicts for any
        detected configuration anti-patterns.

    Example::

        manifests = generate_k8s_manifests(
            app_name="billing-api",
            image="ghcr.io/myorg/billing-api:v2.1.0",
            replicas=3,
            port=8000,
            env_vars={"LOG_LEVEL": "info"},
        )
        for filename, content in manifests.items():
            if filename != "findings":
                Path(filename).write_text(content)
    """
    # Validate and collect findings
    findings = _validate_config(
        app_name=app_name,
        replicas=replicas,
        min_available=min_available,
        min_replicas=min_replicas,
        max_replicas=max_replicas,
        prestop_sleep=prestop_sleep,
        termination_grace=termination_grace,
    )

    result: dict[str, str] = {}

    result["deployment.yaml"] = _deployment_yaml(
        app_name=app_name,
        image=image,
        replicas=replicas,
        port=port,
        env_vars=env_vars,
        cpu_request=cpu_request,
        cpu_limit=cpu_limit,
        memory_request=memory_request,
        memory_limit=memory_limit,
        prestop_sleep=prestop_sleep,
        termination_grace=termination_grace,
        graceful_shutdown_timeout=graceful_shutdown_timeout,
    )

    result["service.yaml"] = _service_yaml(app_name, port)

    if with_hpa:
        result["hpa.yaml"] = _hpa_yaml(
            app_name=app_name,
            min_replicas=min_replicas,
            max_replicas=max_replicas,
            cpu_target=cpu_target,
            memory_target=memory_target,
        )

    if with_pdb:
        result["pdb.yaml"] = _pdb_yaml(app_name, min_available)

    # Attach findings as serializable dicts
    result["findings"] = [f.model_dump() for f in findings]  # type: ignore[assignment]

    return result
