"""Protocol for CorrelationContext — generated from CorrelationContext.py."""

from __future__ import annotations

from typing import Any, Optional, Protocol, runtime_checkable
from collections.abc import Iterator, Mapping
from contextlib import AbstractContextManager

@runtime_checkable
class CorrelationContext(Protocol):
    """CorrelationContext primitive — request-scoped baggage + stable request_id."""

    def request_id(self) -> str: ...
    def trace_id(self) -> str | None: ...
    def baggage(self) -> Mapping[str, str]: ...
    def activate(self) -> AbstractContextManager[None]: ...
    def current(self) -> CorrelationContext: ...
    def from_headers(self, headers: Mapping[str, str]) -> CorrelationContext: ...
    def to_headers(self) -> Mapping[str, str]: ...
