from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class CostEstimateProtocol(Protocol):
    """Auto-inferred Protocol surface for `CostEstimate`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_staging/`.
    """

    def as_header_value(self) -> str: ...
