from __future__ import annotations

from abc import abstractmethod
from typing import Protocol, runtime_checkable


@runtime_checkable
class SecretProviderProtocol(Protocol):
    """Auto-inferred Protocol surface for `SecretProvider`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_staging/`.
    """

    @abstractmethod
    def get(self, name: str, default: str = '') -> str: ...
    @abstractmethod
    def set(self, name: str, value: str) -> None: ...
    def rotate(self, name: str, new_value: str, interval_h: int = 24) -> None: ...
