from __future__ import annotations

from typing import Protocol, runtime_checkable
from typing import Any

@runtime_checkable
class WebSocketManagerProtocol(Protocol):
    """Auto-inferred Protocol surface for `WebSocketManager`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_staging/`.
    """

    async def connect(self, ws: WebSocket, *, room_id: str, user_id: str) -> bool: ...
    async def disconnect(self, ws: WebSocket, *, room_id: str, user_id: str) -> None: ...
    async def broadcast(self, *, room_id: str, payload: dict[str, Any]) -> None: ...
    async def subscribe_loop(self, *, ws: WebSocket, room_id: str) -> None: ...
