from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class ProjectorProtocol(Protocol):
    """Auto-inferred Protocol surface for `Projector`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    def project(self, event: DomainEvent) -> None: ...
    def handle_event(self, event: DomainEvent) -> None: ...
    def save_snapshot(self, stream_id: str, version: int, state: dict[str, Any]) -> None: ...
    async def rebuild(self, session: AsyncSession, store: EventStore, stream_id: str) -> dict[str, Any]: ...
