from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class SafetyCheckerProtocol(Protocol):
    """Auto-inferred Protocol surface for `SafetyChecker`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_staging/`.
    """

    def detect_destructive(self) -> dict[str, Any]: ...
