"""BEHAVIOR TEST — TOOL-112 add_bola_guard.

Proves that the code generated by ``add_bola_guard`` works at runtime:
boots a real ASGI app, hits /healthz, verifies OwnershipVerifier and
bola_test_gen are importable and functionally correct.

Patches applied (so tests run without Docker):
- ``app/core/db.py``               → SQLite + aiosqlite (no Postgres)
- ``app/middleware/idempotency.py`` → pass-through stub (no Redis)
- ``REDIS_URL`` env var             → removed (no Redis needed)

Run::

    PYTHONPATH=. pytest adapt/extend/auth_access/test_add_bola_guard_behavior.py -v

or standalone::

    PYTHONPATH=. python3 adapt/extend/auth_access/test_add_bola_guard_behavior.py
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Environment setup — MUST happen before any app import
# ---------------------------------------------------------------------------
import os

os.environ.setdefault("RATE_LIMITING_ENABLED", "false")
os.environ.setdefault("ENVIRONMENT", "local")
os.environ.setdefault("SECRET_KEY", "behavior-test-bola-secret-key-32+chars!!")
os.environ.setdefault("BOLA_GUARD_ENABLED", "true")
os.environ.setdefault("BOLA_GUARD_STRICT_MODE", "false")
os.environ.pop("REDIS_URL", None)

import ast
import importlib
import importlib.util
import sys
import textwrap
from pathlib import Path
from typing import Any

import anyio
import httpx
import pytest

from adapt.contracts import ToolInput
from adapt.extend.auth_access.add_bola_guard import add_bola_guard
from tests.common.fixture_factory import create_fixture_project


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_SQLITE_DB_PY = textwrap.dedent("""\
    \"\"\"Patched db.py — SQLite+aiosqlite, no Docker required.\"\"\"

    from sqlalchemy import text
    from sqlalchemy.ext.asyncio import create_async_engine

    engine = create_async_engine(
        "sqlite+aiosqlite:///:memory:",
        echo=False,
        future=True,
        connect_args={"check_same_thread": False},
    )


    async def init_db() -> None:
        \"\"\"Run startup checks (connection test).\"\"\"
        async with engine.begin() as conn:
            await conn.execute(text("SELECT 1"))


    __all__ = ["engine", "init_db"]
""")

_PASSTHROUGH_IDEMPOTENCY_PY = textwrap.dedent("""\
    \"\"\"Patched idempotency.py — pass-through stub (no Redis).\"\"\"

    from __future__ import annotations

    from starlette.middleware.base import BaseHTTPMiddleware, RequestResponseEndpoint
    from starlette.requests import Request
    from starlette.responses import Response


    class IdempotencyMiddleware(BaseHTTPMiddleware):
        \"\"\"No-op pass-through stub for testing without Redis.\"\"\"

        async def dispatch(
            self,
            request: Request,
            call_next: RequestResponseEndpoint,
        ) -> Response:
            return await call_next(request)
""")


def _patch_project(project_dir: Path) -> None:
    """Apply SQLite + idempotency stubs to the fixture project."""
    (project_dir / "app" / "core" / "db.py").write_text(_SQLITE_DB_PY)
    idempotency_path = project_dir / "app" / "middleware" / "idempotency.py"
    if idempotency_path.exists():
        idempotency_path.write_text(_PASSTHROUGH_IDEMPOTENCY_PY)


def _load_app(project_dir: Path) -> Any:
    """Load ``app.main:app`` from *project_dir* in an isolated sys.path context."""
    _orig_path = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        app_module = importlib.import_module("app.main")
    finally:
        sys.path[:] = _orig_path
    return app_module.app


def _setup_project() -> tuple[Path, Any]:
    """Create, patch, apply tool, and load app."""
    project_dir = create_fixture_project(name="bola_behavior")
    result = add_bola_guard(ToolInput(project_dir=str(project_dir)))
    assert result.status == "success", (
        f"add_bola_guard failed: {result.error}\nnotes: {result.notes}"
    )
    _patch_project(project_dir)
    asgi_app = _load_app(project_dir)
    return project_dir, asgi_app


# ---------------------------------------------------------------------------
# Module-level shared fixture
# ---------------------------------------------------------------------------

_PROJECT_DIR: Path | None = None
_ASGI_APP: Any = None


def _get_shared_app() -> tuple[Path, Any]:
    global _PROJECT_DIR, _ASGI_APP
    if _PROJECT_DIR is None:
        _PROJECT_DIR, _ASGI_APP = _setup_project()
    return _PROJECT_DIR, _ASGI_APP


@pytest.fixture(scope="module")
def project_dir_and_app() -> tuple[Path, Any]:
    return _get_shared_app()


@pytest.fixture(scope="module")
def project_dir(project_dir_and_app: tuple[Path, Any]) -> Path:
    return project_dir_and_app[0]


@pytest.fixture(scope="module")
def asgi_app(project_dir_and_app: tuple[Path, Any]) -> Any:
    return project_dir_and_app[1]


# ---------------------------------------------------------------------------
# B-01: GET /healthz → 200
# ---------------------------------------------------------------------------

@pytest.mark.anyio
async def test_b01_healthz_returns_200(asgi_app: Any) -> None:
    """B-01: GET /healthz must return 200 after add_bola_guard applied."""
    transport = httpx.ASGITransport(app=asgi_app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.get("/healthz")
    assert response.status_code == 200, (
        f"Expected 200, got {response.status_code}; body: {response.text}"
    )


# ---------------------------------------------------------------------------
# B-02: bola_guard.py importable without raising
# ---------------------------------------------------------------------------

def test_b02_bola_guard_importable(project_dir: Path) -> None:
    """B-02: app/auth/bola_guard.py must be importable without raising."""
    bola_file = project_dir / "app" / "auth" / "bola_guard.py"
    assert bola_file.exists()
    orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        spec = importlib.util.spec_from_file_location(
            "app.auth.bola_guard_b02", str(bola_file)
        )
        assert spec and spec.loader
        mod = importlib.util.module_from_spec(spec)
        sys.modules["app.auth.bola_guard_b02"] = mod  # required for @dataclass in Py3.14
        spec.loader.exec_module(mod)  # type: ignore[attr-defined]
    except Exception as exc:
        raise AssertionError(f"bola_guard.py raised on import: {exc}") from exc
    finally:
        sys.path[:] = orig
    assert hasattr(mod, "OwnershipVerifier")
    assert hasattr(mod, "require_ownership")
    assert hasattr(mod, "TenantIsolationFilter")
    assert hasattr(mod, "ResourceAccessPolicy")


# ---------------------------------------------------------------------------
# B-03: ResourceAccessPolicy.allows() correct logic
# ---------------------------------------------------------------------------

def test_b03_resource_access_policy_allows_logic(project_dir: Path) -> None:
    """B-03: ResourceAccessPolicy.allows() returns True for grantee, False for other."""
    bola_file = project_dir / "app" / "auth" / "bola_guard.py"
    orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        spec = importlib.util.spec_from_file_location(
            "app.auth.bola_guard_b03", str(bola_file)
        )
        assert spec and spec.loader
        mod = importlib.util.module_from_spec(spec)
        sys.modules["app.auth.bola_guard_b03"] = mod  # required for @dataclass in Py3.14
        spec.loader.exec_module(mod)  # type: ignore[attr-defined]
        policy = mod.ResourceAccessPolicy(
            grantor_id=1,
            grantee_id=2,
            resource_model="Order",
            resource_id=42,
            read_only=True,
        )
        assert policy.allows(user_id=2, resource_id=42), "Grantee should have access"
        assert not policy.allows(user_id=3, resource_id=42), "Other user should be denied"
        assert not policy.allows(user_id=2, resource_id=99), "Wrong resource should be denied"
        assert not policy.allows(user_id=2, resource_id=42, write=True), (
            "Write should be denied on read-only policy"
        )
    finally:
        sys.path[:] = orig


# ---------------------------------------------------------------------------
# B-04: bola_test_gen.py importable
# ---------------------------------------------------------------------------

def test_b04_bola_test_gen_importable(project_dir: Path) -> None:
    """B-04: app/auth/bola_test_gen.py must be importable without raising."""
    test_gen = project_dir / "app" / "auth" / "bola_test_gen.py"
    assert test_gen.exists()
    orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        spec = importlib.util.spec_from_file_location(
            "app.auth.bola_test_gen_b04", str(test_gen)
        )
        assert spec and spec.loader
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)  # type: ignore[attr-defined]
    except Exception as exc:
        raise AssertionError(f"bola_test_gen.py raised on import: {exc}") from exc
    finally:
        sys.path[:] = orig
    assert hasattr(mod, "generate_bola_tests"), "generate_bola_tests not exported"


# ---------------------------------------------------------------------------
# B-05: generate_bola_tests() creates a parseable test file
# ---------------------------------------------------------------------------

def test_b05_generate_bola_tests_creates_parseable_file(
    project_dir: Path, tmp_path: Path
) -> None:
    """B-05: generate_bola_tests() creates a Python file that parses cleanly."""
    test_gen = project_dir / "app" / "auth" / "bola_test_gen.py"
    orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        spec = importlib.util.spec_from_file_location(
            "app.auth.bola_test_gen_b05", str(test_gen)
        )
        assert spec and spec.loader
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)  # type: ignore[attr-defined]
        output = str(tmp_path / "test_bola_order.py")
        mod.generate_bola_tests(
            model_name="Order",
            route_prefix="/api/v1/orders",
            output_path=output,
        )
    finally:
        sys.path[:] = orig
    generated = Path(output)
    assert generated.exists(), "Generated test file not created"
    try:
        ast.parse(generated.read_text())
    except SyntaxError as exc:
        raise AssertionError(f"Generated BOLA test file has syntax error: {exc}") from exc


# ---------------------------------------------------------------------------
# B-06: bola_enabled check in bola_guard.py
# ---------------------------------------------------------------------------

def test_b06_bola_enabled_env_respected(project_dir: Path) -> None:
    """B-06: bola_guard.py contains BOLA_GUARD_ENABLED check."""
    bola_file = project_dir / "app" / "auth" / "bola_guard.py"
    content = bola_file.read_text()
    assert "BOLA_GUARD_ENABLED" in content, (
        "BOLA_GUARD_ENABLED env var not checked in bola_guard.py"
    )


# ---------------------------------------------------------------------------
# B-07: all generated functions <= 50 LOC
# ---------------------------------------------------------------------------

def test_b07_all_generated_functions_under_50_loc(project_dir: Path) -> None:
    """B-07: All generated functions in app/auth/ are <= 50 LOC."""
    auth_dir = project_dir / "app" / "auth"
    violations: list[str] = []
    for py_file in sorted(auth_dir.rglob("*.py")):
        tree = ast.parse(py_file.read_text())
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                loc = (node.end_lineno or node.lineno) - node.lineno + 1
                if loc > 50:
                    violations.append(f"{py_file.name}:{node.name} ({loc} LOC)")
    assert not violations, "Functions > 50 LOC:\n" + "\n".join(violations)


# ---------------------------------------------------------------------------
# B-08: config fields 4-space indent
# ---------------------------------------------------------------------------

def test_b08_config_fields_4_space_indent(project_dir: Path) -> None:
    """B-08: BOLA_* config fields have 4-space indent in config.py."""
    config = project_dir / "app" / "core" / "config.py"
    assert config.exists()
    content = config.read_text()
    for line in content.splitlines():
        if any(f in line for f in ("BOLA_GUARD_ENABLED", "BOLA_GUARD_STRICT_MODE")):
            assert line.startswith("    "), f"Not 4-space indented: {line!r}"


# ---------------------------------------------------------------------------
# Standalone runner
# ---------------------------------------------------------------------------

def _run_async_test(coro_fn: Any, *args: Any) -> None:
    import inspect

    async def _wrapper() -> None:
        await coro_fn(*args)

    if inspect.iscoroutinefunction(coro_fn):
        anyio.run(_wrapper)
    else:
        coro_fn(*args)


if __name__ == "__main__":
    import tempfile
    _pd, _app = _get_shared_app()
    _tmp = Path(tempfile.mkdtemp())

    _TESTS: list[tuple[str, Any]] = [
        ("B-01: /healthz → 200", lambda: _run_async_test(test_b01_healthz_returns_200, _app)),
        ("B-02: bola_guard.py importable", lambda: test_b02_bola_guard_importable(_pd)),
        ("B-03: ResourceAccessPolicy.allows() logic", lambda: test_b03_resource_access_policy_allows_logic(_pd)),
        ("B-04: bola_test_gen.py importable", lambda: test_b04_bola_test_gen_importable(_pd)),
        ("B-05: generate_bola_tests() parseable file", lambda: test_b05_generate_bola_tests_creates_parseable_file(_pd, _tmp)),
        ("B-06: BOLA_GUARD_ENABLED env respected", lambda: test_b06_bola_enabled_env_respected(_pd)),
        ("B-07: all funcs <= 50 LOC", lambda: test_b07_all_generated_functions_under_50_loc(_pd)),
        ("B-08: config 4-space indent", lambda: test_b08_config_fields_4_space_indent(_pd)),
    ]

    passed = failed = 0
    for name, fn in _TESTS:
        try:
            fn()
            print(f"  PASS  {name}")
            passed += 1
        except Exception as exc:
            print(f"  FAIL  {name}: {exc}")
            failed += 1

    print(f"\n{'='*60}")
    print(f"TOOL-112 BEHAVIOR: {passed}/{passed + failed} passed")
    if failed:
        sys.exit(1)
