"""BEHAVIOR TEST — TOOL-069 add_ml_gpu_inference.

Proves that the code generated by ``add_ml_gpu_inference`` works at **runtime**:
boots a real ASGI app WITHOUT torch installed, hits the GPU status endpoint
with an httpx client, and asserts generated code quality contracts.

Patches applied (so tests run without Docker / torch):
- ``app/core/db.py``                → SQLite + aiosqlite (no Postgres)
- ``app/middleware/idempotency.py`` → pass-through stub (no Redis)
- ``REDIS_URL`` env var             → removed (no Redis needed)

torch is intentionally NOT installed in this test environment.  The behavior
tests verify the app boots cleanly without it and that the GPU status endpoint
returns ``{"available": false}`` gracefully.

Run::

    PYTHONPATH=. .venv/bin/pytest adapt/extend/infrastructure/test_add_ml_gpu_inference_behavior.py -v

or standalone::

    PYTHONPATH=. .venv/bin/python adapt/extend/infrastructure/test_add_ml_gpu_inference_behavior.py
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Environment setup — MUST happen before any app import
# ---------------------------------------------------------------------------
import os

os.environ.setdefault("RATE_LIMITING_ENABLED", "false")
os.environ.setdefault("ENVIRONMENT", "local")
os.environ.setdefault("SECRET_KEY", "behavior-test-gpu-inference-secret-key-32+chars!")
# GPU settings — keep GPU disabled so no real CUDA calls happen
os.environ.setdefault("GPU_ENABLED", "false")
# Remove REDIS_URL so idempotency middleware falls back gracefully
os.environ.pop("REDIS_URL", None)

import ast
import importlib
import json
import subprocess
import sys
import textwrap
from pathlib import Path
from typing import Any

import anyio
import httpx
import pytest

from adapt.contracts import ToolInput
from adapt.extend.infrastructure.add_ml_gpu_inference import add_ml_gpu_inference
from tests.common.fixture_factory import create_fixture_project


# ---------------------------------------------------------------------------
# Project patching helpers
# ---------------------------------------------------------------------------

_SQLITE_DB_PY = textwrap.dedent("""\
    \"\"\"Patched db.py — SQLite+aiosqlite, no Docker required.\"\"\"

    from sqlalchemy import text
    from sqlalchemy.ext.asyncio import create_async_engine

    engine = create_async_engine(
        "sqlite+aiosqlite:///:memory:",
        echo=False,
        future=True,
        connect_args={"check_same_thread": False},
    )


    async def init_db() -> None:
        \"\"\"Run startup checks (connection test).\"\"\"
        async with engine.begin() as conn:
            await conn.execute(text("SELECT 1"))


    __all__ = ["engine", "init_db"]
""")

_PASSTHROUGH_IDEMPOTENCY_PY = textwrap.dedent("""\
    \"\"\"Patched idempotency.py — pass-through stub (no Redis).\"\"\"

    from __future__ import annotations

    from starlette.middleware.base import BaseHTTPMiddleware, RequestResponseEndpoint
    from starlette.requests import Request
    from starlette.responses import Response


    class IdempotencyMiddleware(BaseHTTPMiddleware):
        \"\"\"No-op pass-through stub for testing without Redis.\"\"\"

        async def dispatch(
            self,
            request: Request,
            call_next: RequestResponseEndpoint,
        ) -> Response:
            return await call_next(request)
""")


def _patch_project(project_dir: Path) -> None:
    """Apply SQLite + idempotency stubs to the fixture project."""
    (project_dir / "app" / "core" / "db.py").write_text(_SQLITE_DB_PY)
    (project_dir / "app" / "middleware" / "idempotency.py").write_text(
        _PASSTHROUGH_IDEMPOTENCY_PY
    )


def _load_app(project_dir: Path) -> Any:
    """Load ``app.main:app`` from *project_dir* in an isolated sys.path context."""
    _orig_path = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        app_module = importlib.import_module("app.main")
    finally:
        sys.path[:] = _orig_path
    return app_module.app


def _setup_project() -> tuple[Path, Any]:
    """Create, patch, apply tool, and load app. Returns (project_dir, asgi_app)."""
    project_dir = create_fixture_project(name="gpu_behavior")
    result = add_ml_gpu_inference(ToolInput(project_dir=str(project_dir)))
    assert result.status == "success", (
        f"add_ml_gpu_inference failed: {result.error}\nnotes: {result.notes}"
    )
    _patch_project(project_dir)
    asgi_app = _load_app(project_dir)
    return project_dir, asgi_app


# ---------------------------------------------------------------------------
# Module-level shared fixture: build project once, share across all tests
# ---------------------------------------------------------------------------

_PROJECT_DIR: Path | None = None
_ASGI_APP: Any = None


def _get_shared_app() -> tuple[Path, Any]:
    global _PROJECT_DIR, _ASGI_APP
    if _PROJECT_DIR is None:
        _PROJECT_DIR, _ASGI_APP = _setup_project()
    return _PROJECT_DIR, _ASGI_APP


@pytest.fixture(scope="module")
def project_dir_and_app() -> tuple[Path, Any]:
    """Shared (module-scoped) fixture: one project for all behavior tests."""
    return _get_shared_app()


@pytest.fixture(scope="module")
def project_dir(project_dir_and_app: tuple[Path, Any]) -> Path:
    return project_dir_and_app[0]


@pytest.fixture(scope="module")
def asgi_app(project_dir_and_app: tuple[Path, Any]) -> Any:
    return project_dir_and_app[1]


# ---------------------------------------------------------------------------
# BEHAVIOR-01: App boots via httpx ASGITransport — GET /healthz → 200
# ---------------------------------------------------------------------------

@pytest.mark.anyio
async def test_b01_app_boots_without_torch(asgi_app: Any) -> None:
    """B-01: App MUST boot via ASGITransport without torch installed.

    This is the primary contract: lazy imports mean the app is always
    importable and always starts, regardless of torch availability.
    """
    transport = httpx.ASGITransport(app=asgi_app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.get("/healthz")
    assert response.status_code == 200, (
        f"Expected 200 from /healthz, got {response.status_code}; body: {response.text}"
    )


# ---------------------------------------------------------------------------
# GPU status URL: the router is included inside api_router → /api/v1/ml/gpu/status
# ---------------------------------------------------------------------------

_GPU_STATUS_URL = "/api/v1/ml/gpu/status"


# ---------------------------------------------------------------------------
# BEHAVIOR-02: GET /api/v1/ml/gpu/status → 200 even without torch
# ---------------------------------------------------------------------------

@pytest.mark.anyio
async def test_b02_gpu_status_returns_200(asgi_app: Any) -> None:
    """B-02: GET /api/v1/ml/gpu/status must return 200 even without torch installed."""
    transport = httpx.ASGITransport(app=asgi_app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.get(_GPU_STATUS_URL)
    assert response.status_code == 200, (
        f"Expected 200, got {response.status_code}; body: {response.text}"
    )


# ---------------------------------------------------------------------------
# BEHAVIOR-03: /api/v1/ml/gpu/status body is valid JSON
# ---------------------------------------------------------------------------

@pytest.mark.anyio
async def test_b03_gpu_status_is_valid_json(asgi_app: Any) -> None:
    """B-03: GET /api/v1/ml/gpu/status must return a parseable JSON object."""
    transport = httpx.ASGITransport(app=asgi_app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.get(_GPU_STATUS_URL)
    body = response.json()
    assert isinstance(body, dict), f"Expected JSON object, got: {type(body)}"


# ---------------------------------------------------------------------------
# BEHAVIOR-04: /api/v1/ml/gpu/status body has 'available' key
# ---------------------------------------------------------------------------

@pytest.mark.anyio
async def test_b04_gpu_status_has_available_key(asgi_app: Any) -> None:
    """B-04: /api/v1/ml/gpu/status JSON must contain 'available' key."""
    transport = httpx.ASGITransport(app=asgi_app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.get(_GPU_STATUS_URL)
    body = response.json()
    assert "available" in body, f"Missing 'available' key in response: {body}"
    assert isinstance(body["available"], bool), (
        f"'available' must be bool, got: {type(body['available'])}"
    )


# ---------------------------------------------------------------------------
# BEHAVIOR-05: Without torch, 'available' is false
# ---------------------------------------------------------------------------

@pytest.mark.anyio
async def test_b05_gpu_unavailable_without_torch(asgi_app: Any) -> None:
    """B-05: Without GPU_ENABLED=true and CUDA, 'available' must be false."""
    transport = httpx.ASGITransport(app=asgi_app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.get(_GPU_STATUS_URL)
    body = response.json()
    # GPU_ENABLED is false in env, so available must be false regardless
    assert body.get("available") is False, (
        f"With GPU_ENABLED=false, 'available' must be false: {body}"
    )
    assert "device" in body, f"Missing 'device' key: {body}"


# ---------------------------------------------------------------------------
# QUALITY-06: torch NOT at top-level in any generated app/ file
# ---------------------------------------------------------------------------

def test_b06_torch_not_top_level_in_app(project_dir: Path) -> None:
    """B-06: torch must NOT appear in module-level imports in any app/ .py file.

    Verifies the lazy import contract programmatically — the core invariant
    of this tool.
    """
    app_dir = project_dir / "app"
    violations: list[str] = []

    for py_file in sorted(app_dir.rglob("*.py")):
        source = py_file.read_text()
        try:
            tree = ast.parse(source)
        except SyntaxError:
            continue
        for node in tree.body:  # Only top-level statements
            if isinstance(node, ast.Import):
                for alias in node.names:
                    if alias.name == "torch" or alias.name.startswith("torch."):
                        violations.append(
                            f"{py_file.relative_to(project_dir)}:"
                            f"{node.lineno}: import torch"
                        )
            elif isinstance(node, ast.ImportFrom) and node.module:
                if node.module == "torch" or node.module.startswith("torch."):
                    violations.append(
                        f"{py_file.relative_to(project_dir)}:"
                        f"{node.lineno}: from torch import ..."
                    )

    assert not violations, (
        "torch found at module top-level in the following files:\n"
        + "\n".join(f"  {v}" for v in violations)
    )


# ---------------------------------------------------------------------------
# QUALITY-07: All generated functions ≤ 50 LOC
# ---------------------------------------------------------------------------

def test_b07_no_function_over_50_loc(project_dir: Path) -> None:
    """B-07: No generated function in app/ may exceed 50 LOC."""
    app_dir = project_dir / "app"
    violations: list[str] = []

    for py_file in sorted(app_dir.rglob("*.py")):
        try:
            tree = ast.parse(py_file.read_text())
        except SyntaxError:
            continue
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                if node.end_lineno:
                    loc = node.end_lineno - node.lineno + 1
                    if loc > 50:
                        violations.append(
                            f"{py_file.relative_to(project_dir)}: "
                            f"{node.name}() = {loc} LOC (limit 50)"
                        )

    assert not violations, (
        "Functions exceeding 50 LOC:\n"
        + "\n".join(f"  {v}" for v in violations)
    )


# ---------------------------------------------------------------------------
# QUALITY-08: Config fields inside Settings class (4-space indent)
# ---------------------------------------------------------------------------

def test_b08_config_fields_4_space_indent(project_dir: Path) -> None:
    """B-08: GPU config fields must be inside the Settings class body (4-space indent)."""
    config_file = project_dir / "app" / "core" / "config.py"
    assert config_file.exists(), "app/core/config.py not found"
    content = config_file.read_text()

    for field_name in ("GPU_ENABLED", "GPU_DEVICE_ID", "GPU_MEMORY_THRESHOLD_PCT",
                       "GPU_MIXED_PRECISION"):
        assert field_name in content, f"{field_name} missing from config.py"
        for line in content.splitlines():
            if field_name in line and ":" in line and ("=" in line or "bool" in line
                                                       or "int" in line or "float" in line):
                assert line.startswith("    "), (
                    f"{field_name} not at 4-space indent (not inside Settings class): {line!r}"
                )
                break


# ---------------------------------------------------------------------------
# QUALITY-09: ruff F401 clean on generated app/ml/gpu/
# ---------------------------------------------------------------------------

def test_b09_ruff_f401_clean_on_gpu_package(project_dir: Path) -> None:
    """B-09: No dead imports (F401) in the generated app/ml/gpu/ package."""
    gpu_dir = project_dir / "app" / "ml" / "gpu"
    assert gpu_dir.exists(), "app/ml/gpu/ not found"

    result = subprocess.run(
        [sys.executable, "-m", "ruff", "check", "--select", "F401", str(gpu_dir)],
        capture_output=True,
        text=True,
    )
    stdout = result.stdout + result.stderr
    assert "F401" not in stdout, (
        f"ruff F401 violations in app/ml/gpu/:\n{stdout}"
    )


# ---------------------------------------------------------------------------
# QUALITY-10: DeviceManager and GPUPredictor importable via sys.path trick
# ---------------------------------------------------------------------------

def test_b10_device_manager_importable(project_dir: Path) -> None:
    """B-10: DeviceManager must be importable from app.ml.gpu.device without torch."""
    orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        import importlib as _il
        mod = _il.import_module("app.ml.gpu.device")
        assert hasattr(mod, "DeviceManager"), "DeviceManager not exported from device module"
        dm = mod.DeviceManager()
        device = dm.get_device()
        # Without torch, should return _CpuDevice stub or a torch CPU device
        assert device is not None, "get_device() must not return None"
        stats = dm.memory_stats()
        assert isinstance(stats, dict), "memory_stats() must return a dict"
    finally:
        sys.path[:] = orig


# ---------------------------------------------------------------------------
# QUALITY-11: MemoryGuard importable and callable without torch
# ---------------------------------------------------------------------------

def test_b11_memory_guard_importable(project_dir: Path) -> None:
    """B-11: MemoryGuard must be importable and check() must not raise without torch."""
    orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        import importlib as _il
        mod = _il.import_module("app.ml.gpu.memory_guard")
        assert hasattr(mod, "MemoryGuard"), "MemoryGuard not exported"
        guard = mod.MemoryGuard()
        # check(None) must be a no-op (no device = no check)
        guard.check(None)  # Must not raise
    finally:
        sys.path[:] = orig


# ---------------------------------------------------------------------------
# Async runner helper
# ---------------------------------------------------------------------------

def _run_async_test(coro_fn: Any, *args: Any) -> None:
    """Run an async test function synchronously via anyio.run."""
    import inspect

    async def _wrapper() -> None:
        await coro_fn(*args)

    if inspect.iscoroutinefunction(coro_fn):
        anyio.run(_wrapper)
    else:
        coro_fn(*args)


# ---------------------------------------------------------------------------
# Standalone runner
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import traceback as _tb

    _pd, _app = _get_shared_app()

    _TESTS: list[tuple[str, Any]] = [
        ("B-01: app boots without torch → /healthz 200",
         lambda: _run_async_test(test_b01_app_boots_without_torch, _app)),
        ("B-02: GET /api/v1/ml/gpu/status → 200",
         lambda: _run_async_test(test_b02_gpu_status_returns_200, _app)),
        ("B-03: /api/v1/ml/gpu/status → valid JSON",
         lambda: _run_async_test(test_b03_gpu_status_is_valid_json, _app)),
        ("B-04: /api/v1/ml/gpu/status has 'available' key",
         lambda: _run_async_test(test_b04_gpu_status_has_available_key, _app)),
        ("B-05: GPU unavailable without torch → available=false",
         lambda: _run_async_test(test_b05_gpu_unavailable_without_torch, _app)),
        ("B-06: torch NOT at top-level",
         lambda: test_b06_torch_not_top_level_in_app(_pd)),
        ("B-07: no function > 50 LOC",
         lambda: test_b07_no_function_over_50_loc(_pd)),
        ("B-08: config fields 4-space indent",
         lambda: test_b08_config_fields_4_space_indent(_pd)),
        ("B-09: ruff F401 clean on gpu package",
         lambda: test_b09_ruff_f401_clean_on_gpu_package(_pd)),
        ("B-10: DeviceManager importable without torch",
         lambda: test_b10_device_manager_importable(_pd)),
        ("B-11: MemoryGuard importable and check(None) safe",
         lambda: test_b11_memory_guard_importable(_pd)),
    ]

    passed = 0
    failed = 0
    failures: list[str] = []

    for name, fn in _TESTS:
        try:
            fn()
            print(f"  PASS  {name}")
            passed += 1
        except Exception as exc:
            print(f"  FAIL  {name}: {exc}")
            _tb.print_exc()
            failures.append(f"{name}: {exc}")
            failed += 1

    total = passed + failed
    status = "PASS" if failed == 0 else "FAIL"

    contract = {
        "tool": "TOOL-069 add_ml_gpu_inference",
        "test_file": "test_add_ml_gpu_inference_behavior.py",
        "agent": "Agent (Sonnet 4.6)",
        "total": total,
        "passed": passed,
        "failed": failed,
        "status": status,
        "failures": failures,
        "coverage": [
            "App boots without torch — GET /healthz → 200",
            "GET /api/v1/ml/gpu/status → 200 (no torch)",
            "/api/v1/ml/gpu/status → valid JSON",
            "/api/v1/ml/gpu/status has 'available' key (bool)",
            "available=false when GPU_ENABLED=false",
            "torch NOT at module top-level in any app/ file",
            "No function > 50 LOC in app/",
            "Config fields at 4-space indent (inside Settings class)",
            "ruff F401 clean on app/ml/gpu/",
            "DeviceManager importable + get_device() + memory_stats() work without torch",
            "MemoryGuard importable + check(None) is a no-op without torch",
        ],
    }

    print(f"\n{'='*60}")
    print(f"TOOL-069 BEHAVIOR: {passed}/{total} passed")
    print(f"\nDelivery contract JSON:")
    print(json.dumps(contract, indent=2))

    if failed:
        sys.exit(1)
