"""BEHAVIOR TEST — TOOL-096 add_adaptive_timeouts.

Proves that the code generated by ``add_adaptive_timeouts`` works at **runtime**:
boots a real ASGI app and verifies adaptive timeout contracts.

Patches applied (so tests run without Docker):
- ``app/core/db.py``         → SQLite + aiosqlite (no Postgres)
- ``app/middleware/idempotency.py`` → pass-through stub (no Redis)
- ``REDIS_URL`` env var      → removed (no Redis needed)

Run::

    PYTHONPATH=. pytest adapt/extend/infrastructure/test_add_adaptive_timeouts_behavior.py -v

or standalone::

    PYTHONPATH=. python3 adapt/extend/infrastructure/test_add_adaptive_timeouts_behavior.py
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Environment setup — MUST happen before any app import
# ---------------------------------------------------------------------------
import os

os.environ.setdefault("RATE_LIMITING_ENABLED", "false")
os.environ.setdefault("ENVIRONMENT", "local")
os.environ.setdefault("SECRET_KEY", "behavior-test-adaptive-timeout-secret-key-32+chars!")
os.environ.pop("REDIS_URL", None)

import ast
import asyncio
import importlib
import sys
import textwrap
from pathlib import Path
from typing import Any

import anyio
import httpx
import pytest

from adapt.contracts import ToolInput
from adapt.extend.infrastructure.add_adaptive_timeouts import add_adaptive_timeouts
from tests.common.fixture_factory import create_fixture_project


# ---------------------------------------------------------------------------
# Patch templates
# ---------------------------------------------------------------------------

_SQLITE_DB_PY = textwrap.dedent("""\
    \"\"\"Patched db.py — SQLite+aiosqlite, no Docker required.\"\"\"

    from sqlalchemy import text
    from sqlalchemy.ext.asyncio import create_async_engine

    engine = create_async_engine(
        "sqlite+aiosqlite:///:memory:",
        echo=False,
        future=True,
        connect_args={"check_same_thread": False},
    )


    async def init_db() -> None:
        \"\"\"Run startup checks (connection test).\"\"\"
        async with engine.begin() as conn:
            await conn.execute(text("SELECT 1"))


    __all__ = ["engine", "init_db"]
""")

_PASSTHROUGH_IDEMPOTENCY_PY = textwrap.dedent("""\
    \"\"\"Patched idempotency.py — pass-through stub (no Redis).\"\"\"

    from __future__ import annotations

    from starlette.middleware.base import BaseHTTPMiddleware, RequestResponseEndpoint
    from starlette.requests import Request
    from starlette.responses import Response


    class IdempotencyMiddleware(BaseHTTPMiddleware):
        \"\"\"No-op pass-through stub for testing without Redis.\"\"\"

        async def dispatch(
            self,
            request: Request,
            call_next: RequestResponseEndpoint,
        ) -> Response:
            return await call_next(request)
""")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _patch_project(project_dir: Path) -> None:
    """Apply SQLite + idempotency stubs to the fixture project."""
    (project_dir / "app" / "core" / "db.py").write_text(_SQLITE_DB_PY)
    mw_dir = project_dir / "app" / "middleware"
    mw_dir.mkdir(parents=True, exist_ok=True)
    (mw_dir / "idempotency.py").write_text(_PASSTHROUGH_IDEMPOTENCY_PY)


def _load_app(project_dir: Path) -> Any:
    """Load ``app.main:app`` from *project_dir* in an isolated sys.path context."""
    _orig_path = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        app_module = importlib.import_module("app.main")
    finally:
        sys.path[:] = _orig_path
    return app_module.app


def _setup_project() -> tuple[Path, Any]:
    """Create, patch, apply tool, and load app."""
    project_dir = create_fixture_project(name="at_behavior")
    result = add_adaptive_timeouts(ToolInput(project_dir=str(project_dir)))
    assert result.status == "success", (
        f"add_adaptive_timeouts failed: {result.error}\nnotes: {result.notes}"
    )
    _patch_project(project_dir)
    asgi_app = _load_app(project_dir)
    return project_dir, asgi_app


# ---------------------------------------------------------------------------
# Module-level shared fixture
# ---------------------------------------------------------------------------

_PROJECT_DIR: Path | None = None
_ASGI_APP: Any = None


def _get_shared_app() -> tuple[Path, Any]:
    global _PROJECT_DIR, _ASGI_APP
    if _PROJECT_DIR is None:
        _PROJECT_DIR, _ASGI_APP = _setup_project()
    return _PROJECT_DIR, _ASGI_APP


@pytest.fixture(scope="module")
def project_dir_and_app() -> tuple[Path, Any]:
    return _get_shared_app()


@pytest.fixture(scope="module")
def project_dir(project_dir_and_app: tuple[Path, Any]) -> Path:
    return project_dir_and_app[0]


@pytest.fixture(scope="module")
def asgi_app(project_dir_and_app: tuple[Path, Any]) -> Any:
    return project_dir_and_app[1]


# ---------------------------------------------------------------------------
# B-01: GET /healthz → 200
# ---------------------------------------------------------------------------

@pytest.mark.anyio
async def test_b01_healthz_returns_200(asgi_app: Any) -> None:
    """B-01: GET /healthz returns 200 after adaptive timeouts applied."""
    transport = httpx.ASGITransport(app=asgi_app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.get("/healthz")
    assert response.status_code == 200, (
        f"Expected 200, got {response.status_code}; body: {response.text}"
    )


# ---------------------------------------------------------------------------
# B-02: AdaptiveTimeout tracks latency and adjusts timeout
# ---------------------------------------------------------------------------

def test_b02_adaptive_timeout_adjusts(project_dir: Path) -> None:
    """B-02: AdaptiveTimeout adjusts timeout to p99 * 1.5 after recording samples."""
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        from app.resilience.adaptive_timeout import AdaptiveTimeout
        tracker = AdaptiveTimeout("test_svc", window_size=10, floor_ms=50.0, ceiling_ms=5000.0)
        for ms in [100.0, 110.0, 120.0, 130.0, 140.0, 150.0, 160.0, 170.0, 180.0, 190.0]:
            tracker.record(ms)
        stats = tracker.get_stats()
        # p99 of [100..190] is ~190ms; timeout = 190 * 1.5 = 285ms = 0.285s
        assert stats["p99"] >= 180.0, f"Expected p99 >= 180ms, got {stats['p99']}"
        timeout_s = tracker.get_timeout_s()
        assert timeout_s >= 0.2, f"Expected timeout >= 0.2s, got {timeout_s}"
    finally:
        sys.path.remove(str(project_dir))


# ---------------------------------------------------------------------------
# B-03: Floor and ceiling enforced
# ---------------------------------------------------------------------------

def test_b03_floor_ceiling_enforced(project_dir: Path) -> None:
    """B-03: Computed timeout is clamped between floor and ceiling."""
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        from app.resilience.adaptive_timeout import AdaptiveTimeout
        # Very low latency — timeout should not go below floor
        tracker_low = AdaptiveTimeout("low_svc", floor_ms=200.0, ceiling_ms=5000.0)
        tracker_low.record(1.0)
        assert tracker_low.get_timeout_s() >= 0.2, "Timeout must not go below floor (200ms)"
        # Very high latency — timeout should not exceed ceiling
        tracker_high = AdaptiveTimeout("high_svc", floor_ms=100.0, ceiling_ms=1000.0)
        for _ in range(10):
            tracker_high.record(10000.0)
        assert tracker_high.get_timeout_s() <= 1.0, "Timeout must not exceed ceiling (1000ms)"
    finally:
        sys.path.remove(str(project_dir))


# ---------------------------------------------------------------------------
# B-04: TimeoutRegistry per-dependency tracking
# ---------------------------------------------------------------------------

def test_b04_timeout_registry_per_dependency(project_dir: Path) -> None:
    """B-04: TimeoutRegistry returns independent trackers per dependency."""
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        from app.resilience.timeout_registry import TimeoutRegistry
        registry = TimeoutRegistry(window_size=10, floor_ms=50.0, ceiling_ms=5000.0)
        t1 = registry.get_or_create("stripe_api")
        t2 = registry.get_or_create("postgres_db")
        assert t1 is not t2, "Each dependency must have its own tracker"
        # Same key returns same tracker
        t1_again = registry.get_or_create("stripe_api")
        assert t1 is t1_again, "Same key must return the same tracker"
        assert "stripe_api" in registry.names()
        assert "postgres_db" in registry.names()
    finally:
        sys.path.remove(str(project_dir))


# ---------------------------------------------------------------------------
# B-05: @adaptive_timeout decorator enforces timeout via asyncio.wait_for
# ---------------------------------------------------------------------------

@pytest.mark.anyio
async def test_b05_decorator_enforces_timeout(project_dir: Path) -> None:
    """B-05: @adaptive_timeout decorator raises TimeoutError for slow functions."""
    os.environ["ADAPTIVE_TIMEOUT_ENABLED"] = "true"
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        from app.resilience.adaptive_timeout import AdaptiveTimeout
        from app.resilience.timeout_registry import TimeoutRegistry

        registry = TimeoutRegistry(floor_ms=50.0, ceiling_ms=200.0)
        tracker = registry.get_or_create("slow_service")
        # Seed very low p99 so timeout = ~75ms (50ms * 1.5)
        for _ in range(10):
            tracker.record(50.0)

        from app.resilience.adaptive_timeout import adaptive_timeout

        @adaptive_timeout("slow_service", registry=registry)
        async def slow_call() -> str:
            await asyncio.sleep(10)
            return "ok"

        with pytest.raises(asyncio.TimeoutError):
            await slow_call()
    finally:
        sys.path.remove(str(project_dir))
        os.environ.pop("ADAPTIVE_TIMEOUT_ENABLED", None)


# ---------------------------------------------------------------------------
# B-06: get_stats returns all required keys
# ---------------------------------------------------------------------------

def test_b06_get_stats_keys(project_dir: Path) -> None:
    """B-06: AdaptiveTimeout.get_stats() returns p50, p95, p99, current_timeout_s."""
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        from app.resilience.adaptive_timeout import AdaptiveTimeout
        tracker = AdaptiveTimeout("stats_test")
        for ms in [100.0, 200.0, 300.0]:
            tracker.record(ms)
        stats = tracker.get_stats()
        assert "p50" in stats
        assert "p95" in stats
        assert "p99" in stats
        assert "current_timeout_s" in stats
        assert "sample_count" in stats
        assert stats["sample_count"] == 3
    finally:
        sys.path.remove(str(project_dir))


# ---------------------------------------------------------------------------
# B-07: Lazy SDK imports verified via AST
# ---------------------------------------------------------------------------

def test_b07_lazy_sdk_imports(project_dir: Path) -> None:
    """B-07: No optional SDKs are imported at module top-level in OUR generated files."""
    # Only scan the directories we generated — not pre-existing project files
    generated_dirs = [
        project_dir / "app" / "resilience",
        project_dir / "app" / "middleware",
    ]
    optional_sdks = {"redis", "stripe", "boto3", "psutil", "prometheus_client"}
    violations: list[str] = []
    for check_dir in generated_dirs:
        if not check_dir.exists():
            continue
        for py_file in check_dir.rglob("*.py"):
            source = py_file.read_text()
            try:
                tree = ast.parse(source)
            except SyntaxError:
                continue
            for node in tree.body:
                if isinstance(node, ast.Import):
                    for alias in node.names:
                        root_name = alias.name.split(".")[0]
                        if root_name in optional_sdks:
                            violations.append(f"{py_file.name}:{node.lineno} import {alias.name}")
                elif isinstance(node, ast.ImportFrom):
                    if node.module:
                        root_name = node.module.split(".")[0]
                        if root_name in optional_sdks:
                            violations.append(
                                f"{py_file.name}:{node.lineno} from {node.module} import ..."
                            )
    assert not violations, (
        "Optional SDKs found at top-level in generated files:\n"
        + "\n".join(f"  {v}" for v in violations)
    )


# ---------------------------------------------------------------------------
# B-08: All functions <= 50 LOC
# ---------------------------------------------------------------------------

def test_b08_all_functions_max_50_loc(project_dir: Path) -> None:
    """B-08: No function in generated files exceeds 50 LOC."""
    resilience_dir = project_dir / "app" / "resilience"
    violations: list[str] = []
    if resilience_dir.exists():
        for py_file in resilience_dir.rglob("*.py"):
            tree = ast.parse(py_file.read_text())
            for node in ast.walk(tree):
                if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    loc = (node.end_lineno or node.lineno) - node.lineno + 1
                    if loc > 50:
                        violations.append(
                            f"{py_file.name}:{node.lineno} {node.name}() = {loc} LOC"
                        )
    assert not violations, "Functions > 50 LOC:\n" + "\n".join(violations)


# ---------------------------------------------------------------------------
# B-09: Config fields 4-space indent
# ---------------------------------------------------------------------------

def test_b09_config_fields_4_space_indent(project_dir: Path) -> None:
    """B-09: ADAPTIVE_TIMEOUT_* fields in config.py use 4-space indent."""
    config_file = project_dir / "app" / "core" / "config.py"
    assert config_file.exists()
    content = config_file.read_text()
    assert "    ADAPTIVE_TIMEOUT_ENABLED" in content, (
        "ADAPTIVE_TIMEOUT_ENABLED must be indented with 4 spaces in Settings class"
    )


# ---------------------------------------------------------------------------
# B-10: all_stats returns per-dependency data
# ---------------------------------------------------------------------------

def test_b10_all_stats(project_dir: Path) -> None:
    """B-10: TimeoutRegistry.all_stats() returns stats for every registered dependency."""
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        from app.resilience.timeout_registry import TimeoutRegistry
        registry = TimeoutRegistry(window_size=5)
        registry.get_or_create("dep_a").record(100.0)
        registry.get_or_create("dep_b").record(200.0)
        stats = registry.all_stats()
        assert "dep_a" in stats
        assert "dep_b" in stats
        assert stats["dep_a"]["sample_count"] == 1
        assert stats["dep_b"]["sample_count"] == 1
    finally:
        sys.path.remove(str(project_dir))


# ---------------------------------------------------------------------------
# Standalone runner
# ---------------------------------------------------------------------------

def _run_async_test(coro_fn: Any, *args: Any) -> None:
    import inspect
    async def _wrapper() -> None:
        await coro_fn(*args)
    if inspect.iscoroutinefunction(coro_fn):
        anyio.run(_wrapper)
    else:
        coro_fn(*args)


if __name__ == "__main__":
    _pd, _app = _get_shared_app()

    _TESTS: list[tuple[str, Any]] = [
        ("B-01: /healthz → 200", lambda: _run_async_test(test_b01_healthz_returns_200, _app)),
        ("B-02: AdaptiveTimeout adjusts", lambda: test_b02_adaptive_timeout_adjusts(_pd)),
        ("B-03: Floor/ceiling enforced", lambda: test_b03_floor_ceiling_enforced(_pd)),
        ("B-04: Registry per-dependency", lambda: test_b04_timeout_registry_per_dependency(_pd)),
        ("B-05: Decorator enforces timeout", lambda: _run_async_test(test_b05_decorator_enforces_timeout, _pd)),
        ("B-06: get_stats keys", lambda: test_b06_get_stats_keys(_pd)),
        ("B-07: Lazy SDK imports", lambda: test_b07_lazy_sdk_imports(_pd)),
        ("B-08: All functions <= 50 LOC", lambda: test_b08_all_functions_max_50_loc(_pd)),
        ("B-09: Config 4-space indent", lambda: test_b09_config_fields_4_space_indent(_pd)),
        ("B-10: all_stats per-dependency", lambda: test_b10_all_stats(_pd)),
    ]

    passed = failed = 0
    for name, fn in _TESTS:
        try:
            fn()
            print(f"  PASS  {name}")
            passed += 1
        except Exception as exc:
            print(f"  FAIL  {name}: {exc}")
            failed += 1

    print(f"\n{'='*60}")
    print(f"TOOL-096 BEHAVIOR: {passed}/{passed + failed} passed")
    if failed:
        sys.exit(1)
