"""BEHAVIOR TEST — TOOL-087 add_structured_logging.

Proves that the code generated by ``add_structured_logging`` works at **runtime**:
boots a real ASGI app, hits /healthz, and asserts the structlog contract.

Patches applied (so tests run without Docker):
- ``app/core/db.py``               → SQLite + aiosqlite (no Postgres)
- ``app/middleware/idempotency.py`` → pass-through stub (no Redis)
- ``REDIS_URL`` env var             → removed (no Redis needed)

Run::

    PYTHONPATH=. .venv/bin/pytest adapt/extend/infrastructure/test_add_structured_logging_behavior.py -v

or standalone::

    PYTHONPATH=. .venv/bin/python adapt/extend/infrastructure/test_add_structured_logging_behavior.py
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Environment setup — MUST happen before any app import
# ---------------------------------------------------------------------------
import os

os.environ.setdefault("RATE_LIMITING_ENABLED", "false")
os.environ.setdefault("ENVIRONMENT", "local")
os.environ.setdefault("SECRET_KEY", "behavior-test-slog-secret-key-32+chars!")
os.environ.setdefault("LOG_LEVEL", "INFO")
os.environ.setdefault("LOG_FORMAT", "json")
os.environ.setdefault("LOG_REDACTION_ENABLED", "true")
os.environ.pop("REDIS_URL", None)

import ast
import importlib
import importlib.util
import sys
import textwrap
from pathlib import Path
from typing import Any

import anyio
import httpx
import pytest

from adapt.contracts import ToolInput
from adapt.extend.infrastructure.add_structured_logging import add_structured_logging
from tests.common.fixture_factory import create_fixture_project


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_SQLITE_DB_PY = textwrap.dedent("""\
    \"\"\"Patched db.py — SQLite+aiosqlite, no Docker required.\"\"\"

    from sqlalchemy import text
    from sqlalchemy.ext.asyncio import create_async_engine

    engine = create_async_engine(
        "sqlite+aiosqlite:///:memory:",
        echo=False,
        future=True,
        connect_args={"check_same_thread": False},
    )


    async def init_db() -> None:
        \"\"\"Run startup checks (connection test).\"\"\"
        async with engine.begin() as conn:
            await conn.execute(text("SELECT 1"))


    __all__ = ["engine", "init_db"]
""")

_PASSTHROUGH_IDEMPOTENCY_PY = textwrap.dedent("""\
    \"\"\"Patched idempotency.py — pass-through stub (no Redis).\"\"\"

    from __future__ import annotations

    from starlette.middleware.base import BaseHTTPMiddleware, RequestResponseEndpoint
    from starlette.requests import Request
    from starlette.responses import Response


    class IdempotencyMiddleware(BaseHTTPMiddleware):
        \"\"\"No-op pass-through stub for testing without Redis.\"\"\"

        async def dispatch(
            self,
            request: Request,
            call_next: RequestResponseEndpoint,
        ) -> Response:
            return await call_next(request)
""")


def _patch_project(project_dir: Path) -> None:
    """Apply SQLite + idempotency stubs to the fixture project."""
    (project_dir / "app" / "core" / "db.py").write_text(_SQLITE_DB_PY)
    idempotency_path = project_dir / "app" / "middleware" / "idempotency.py"
    if idempotency_path.exists():
        idempotency_path.write_text(_PASSTHROUGH_IDEMPOTENCY_PY)


def _load_app(project_dir: Path) -> Any:
    """Load ``app.main:app`` from *project_dir* in an isolated sys.path context."""
    _orig_path = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        app_module = importlib.import_module("app.main")
    finally:
        sys.path[:] = _orig_path
    return app_module.app


def _setup_project() -> tuple[Path, Any]:
    """Create, patch, apply tool, and load app."""
    project_dir = create_fixture_project(name="slog_behavior")
    result = add_structured_logging(ToolInput(project_dir=str(project_dir)))
    assert result.status == "success", (
        f"add_structured_logging failed: {result.error}\nnotes: {result.notes}"
    )
    _patch_project(project_dir)
    asgi_app = _load_app(project_dir)
    return project_dir, asgi_app


# ---------------------------------------------------------------------------
# Module-level shared fixture
# ---------------------------------------------------------------------------

_PROJECT_DIR: Path | None = None
_ASGI_APP: Any = None


def _get_shared_app() -> tuple[Path, Any]:
    global _PROJECT_DIR, _ASGI_APP
    if _PROJECT_DIR is None:
        _PROJECT_DIR, _ASGI_APP = _setup_project()
    return _PROJECT_DIR, _ASGI_APP


@pytest.fixture(scope="module")
def project_dir_and_app() -> tuple[Path, Any]:
    return _get_shared_app()


@pytest.fixture(scope="module")
def project_dir(project_dir_and_app: tuple[Path, Any]) -> Path:
    return project_dir_and_app[0]


@pytest.fixture(scope="module")
def asgi_app(project_dir_and_app: tuple[Path, Any]) -> Any:
    return project_dir_and_app[1]


# ---------------------------------------------------------------------------
# BEHAVIOR-01: GET /healthz → 200
# ---------------------------------------------------------------------------

@pytest.mark.anyio
async def test_b01_healthz_returns_200(asgi_app: Any) -> None:
    """B-01: GET /healthz must return 200."""
    transport = httpx.ASGITransport(app=asgi_app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.get("/healthz")
    assert response.status_code == 200, (
        f"Expected 200, got {response.status_code}; body: {response.text}"
    )


# ---------------------------------------------------------------------------
# BEHAVIOR-02: setup.py importable without crash
# ---------------------------------------------------------------------------

def test_b02_setup_importable_without_crash(project_dir: Path) -> None:
    """B-02: app/logging/setup.py must be importable without raising."""
    setup_file = project_dir / "app" / "logging" / "setup.py"
    assert setup_file.exists(), "app/logging/setup.py not found"
    spec = importlib.util.spec_from_file_location(
        "app.logging.setup_b02", str(setup_file)
    )
    assert spec and spec.loader
    orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    try:
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)  # type: ignore[attr-defined]
    except Exception as exc:
        raise AssertionError(f"setup.py raised on import: {exc}") from exc
    finally:
        sys.path[:] = orig
    assert hasattr(mod, "configure_structlog"), "configure_structlog not found"


# ---------------------------------------------------------------------------
# BEHAVIOR-03: redactor.py importable and redacts email
# ---------------------------------------------------------------------------

def test_b03_redactor_importable_and_redacts_email(project_dir: Path) -> None:
    """B-03: app/logging/redactor.py importable; Redactor strips email addresses."""
    redactor_file = project_dir / "app" / "logging" / "redactor.py"
    assert redactor_file.exists()
    spec = importlib.util.spec_from_file_location(
        "app.logging.redactor_b03", str(redactor_file)
    )
    assert spec and spec.loader
    orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    try:
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)  # type: ignore[attr-defined]
    except Exception as exc:
        raise AssertionError(f"redactor.py raised on import: {exc}") from exc
    finally:
        sys.path[:] = orig
    assert hasattr(mod, "Redactor")
    # Verify redaction works
    redactor = mod.Redactor()
    event_dict = {"event": "User login: user@example.com was logged in"}
    result = redactor(None, "info", event_dict)
    assert "user@example.com" not in result.get("event", ""), (
        "Redactor should strip email addresses"
    )
    assert "[REDACTED]" in result.get("event", ""), "Redactor should replace with [REDACTED]"


# ---------------------------------------------------------------------------
# BEHAVIOR-04: context.py importable with bind_context and get_correlation_id
# ---------------------------------------------------------------------------

def test_b04_context_importable(project_dir: Path) -> None:
    """B-04: app/logging/context.py must be importable with required functions."""
    context_file = project_dir / "app" / "logging" / "context.py"
    assert context_file.exists()
    spec = importlib.util.spec_from_file_location(
        "app.logging.context_b04", str(context_file)
    )
    assert spec and spec.loader
    orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    try:
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)  # type: ignore[attr-defined]
    except Exception as exc:
        raise AssertionError(f"context.py raised on import: {exc}") from exc
    finally:
        sys.path[:] = orig
    assert hasattr(mod, "get_correlation_id"), "get_correlation_id not found"
    assert hasattr(mod, "bind_context"), "bind_context not found"


# ---------------------------------------------------------------------------
# BEHAVIOR-05: all functions <= 50 LOC
# ---------------------------------------------------------------------------

def test_b05_all_generated_functions_under_50_loc(project_dir: Path) -> None:
    """B-05: All generated functions in app/logging/ are <= 50 LOC."""
    logging_dir = project_dir / "app" / "logging"
    violations: list[str] = []
    for py_file in sorted(logging_dir.rglob("*.py")):
        tree = ast.parse(py_file.read_text())
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                loc = (node.end_lineno or node.lineno) - node.lineno + 1
                if loc > 50:
                    violations.append(f"{py_file.name}:{node.name} ({loc} LOC)")
    assert not violations, "Functions > 50 LOC:\n" + "\n".join(violations)


# ---------------------------------------------------------------------------
# BEHAVIOR-06: config fields 4-space indent
# ---------------------------------------------------------------------------

def test_b06_config_fields_4_space_indent(project_dir: Path) -> None:
    """B-06: LOG_* fields in config.py have 4-space indent."""
    config = project_dir / "app" / "core" / "config.py"
    assert config.exists()
    content = config.read_text()
    for line in content.splitlines():
        if any(f in line for f in ("LOG_LEVEL", "LOG_FORMAT", "LOG_REDACTION_ENABLED")):
            assert line.startswith("    "), f"Not 4-space indented: {line!r}"


# ---------------------------------------------------------------------------
# BEHAVIOR-07: get_correlation_id returns a UUID string
# ---------------------------------------------------------------------------

def test_b07_get_correlation_id_returns_uuid(project_dir: Path) -> None:
    """B-07: get_correlation_id() must return a non-empty string."""
    context_file = project_dir / "app" / "logging" / "context.py"
    spec = importlib.util.spec_from_file_location(
        "app.logging.context_b07", str(context_file)
    )
    assert spec and spec.loader
    orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    try:
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)  # type: ignore[attr-defined]
    finally:
        sys.path[:] = orig
    cid = mod.get_correlation_id()
    assert isinstance(cid, str), "get_correlation_id must return a string"
    assert len(cid) > 0, "get_correlation_id must return a non-empty string"


# ---------------------------------------------------------------------------
# BEHAVIOR-08: configure_structlog does not raise in json mode
# ---------------------------------------------------------------------------

def test_b08_configure_structlog_runs_without_crash(project_dir: Path) -> None:
    """B-08: configure_structlog() must run without raising an exception."""
    setup_file = project_dir / "app" / "logging" / "setup.py"
    spec = importlib.util.spec_from_file_location(
        "app.logging.setup_b08", str(setup_file)
    )
    assert spec and spec.loader
    orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    try:
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)  # type: ignore[attr-defined]
        mod.configure_structlog(level="INFO", fmt="json", redaction_enabled=True)
    except Exception as exc:
        raise AssertionError(f"configure_structlog raised: {exc}") from exc
    finally:
        sys.path[:] = orig


# ---------------------------------------------------------------------------
# Standalone runner
# ---------------------------------------------------------------------------

def _run_async_test(coro_fn: Any, *args: Any) -> None:
    import inspect

    async def _wrapper() -> None:
        await coro_fn(*args)

    if inspect.iscoroutinefunction(coro_fn):
        anyio.run(_wrapper)
    else:
        coro_fn(*args)


if __name__ == "__main__":
    _pd, _app = _get_shared_app()

    _TESTS: list[tuple[str, Any]] = [
        ("B-01: /healthz → 200", lambda: _run_async_test(test_b01_healthz_returns_200, _app)),
        ("B-02: setup.py importable", lambda: test_b02_setup_importable_without_crash(_pd)),
        ("B-03: redactor strips email", lambda: test_b03_redactor_importable_and_redacts_email(_pd)),
        ("B-04: context.py importable", lambda: test_b04_context_importable(_pd)),
        ("B-05: all funcs <= 50 LOC", lambda: test_b05_all_generated_functions_under_50_loc(_pd)),
        ("B-06: config 4-space indent", lambda: test_b06_config_fields_4_space_indent(_pd)),
        ("B-07: get_correlation_id uuid", lambda: test_b07_get_correlation_id_returns_uuid(_pd)),
        ("B-08: configure_structlog no crash", lambda: test_b08_configure_structlog_runs_without_crash(_pd)),
    ]

    passed = failed = 0
    for name, fn in _TESTS:
        try:
            fn()
            print(f"  PASS  {name}")
            passed += 1
        except Exception as exc:
            print(f"  FAIL  {name}: {exc}")
            failed += 1

    print(f"\n{'='*60}")
    print(f"TOOL-087 BEHAVIOR: {passed}/{passed + failed} passed")
    if failed:
        sys.exit(1)
