"""BEHAVIOR TEST — TOOL-086 add_prometheus_metrics.

Proves that the code generated by ``add_prometheus_metrics`` works at **runtime**:
boots a real ASGI app, hits /healthz and /metrics, and asserts the Prometheus
contract.

Patches applied (so tests run without Docker):
- ``app/core/db.py``               → SQLite + aiosqlite (no Postgres)
- ``app/middleware/idempotency.py`` → pass-through stub (no Redis)
- ``REDIS_URL`` env var             → removed (no Redis needed)

Run::

    PYTHONPATH=. .venv/bin/pytest adapt/extend/infrastructure/test_add_prometheus_metrics_behavior.py -v

or standalone::

    PYTHONPATH=. .venv/bin/python adapt/extend/infrastructure/test_add_prometheus_metrics_behavior.py
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Environment setup — MUST happen before any app import
# ---------------------------------------------------------------------------
import os

os.environ.setdefault("RATE_LIMITING_ENABLED", "false")
os.environ.setdefault("ENVIRONMENT", "local")
os.environ.setdefault("SECRET_KEY", "behavior-test-prom-metrics-secret-key-32+chars!")
os.environ.setdefault("PROMETHEUS_ENABLED", "true")
os.environ.setdefault("PROMETHEUS_PREFIX", "http")
os.environ.pop("REDIS_URL", None)

import ast
import importlib
import sys
import textwrap
from pathlib import Path
from typing import Any

import anyio
import httpx
import pytest

from adapt.contracts import ToolInput
from adapt.extend.infrastructure.add_prometheus_metrics import add_prometheus_metrics
from tests.common.fixture_factory import create_fixture_project

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_SQLITE_DB_PY = textwrap.dedent("""\
    \"\"\"Patched db.py — SQLite+aiosqlite, no Docker required.\"\"\"

    from sqlalchemy import text
    from sqlalchemy.ext.asyncio import create_async_engine

    engine = create_async_engine(
        "sqlite+aiosqlite:///:memory:",
        echo=False,
        future=True,
        connect_args={"check_same_thread": False},
    )


    async def init_db() -> None:
        \"\"\"Run startup checks (connection test).\"\"\"
        async with engine.begin() as conn:
            await conn.execute(text("SELECT 1"))


    __all__ = ["engine", "init_db"]
""")

_PASSTHROUGH_IDEMPOTENCY_PY = textwrap.dedent("""\
    \"\"\"Patched idempotency.py — pass-through stub (no Redis).\"\"\"

    from __future__ import annotations

    from starlette.middleware.base import BaseHTTPMiddleware, RequestResponseEndpoint
    from starlette.requests import Request
    from starlette.responses import Response


    class IdempotencyMiddleware(BaseHTTPMiddleware):
        \"\"\"No-op pass-through stub for testing without Redis.\"\"\"

        async def dispatch(
            self,
            request: Request,
            call_next: RequestResponseEndpoint,
        ) -> Response:
            return await call_next(request)
""")


def _patch_project(project_dir: Path) -> None:
    """Apply SQLite + idempotency stubs to the fixture project."""
    (project_dir / "app" / "core" / "db.py").write_text(_SQLITE_DB_PY)
    idempotency_path = project_dir / "app" / "middleware" / "idempotency.py"
    if idempotency_path.exists():
        idempotency_path.write_text(_PASSTHROUGH_IDEMPOTENCY_PY)


def _load_app(project_dir: Path) -> Any:
    """Load ``app.main:app`` from *project_dir* in an isolated sys.path context."""
    _orig_path = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        app_module = importlib.import_module("app.main")
    finally:
        sys.path[:] = _orig_path
    return app_module.app


def _setup_project() -> tuple[Path, Any]:
    """Create, patch, apply tool, and load app."""
    project_dir = create_fixture_project(name="prom_behavior")
    result = add_prometheus_metrics(ToolInput(project_dir=str(project_dir)))
    assert result.status == "success", (
        f"add_prometheus_metrics failed: {result.error}\nnotes: {result.notes}"
    )
    _patch_project(project_dir)
    asgi_app = _load_app(project_dir)
    return project_dir, asgi_app


# ---------------------------------------------------------------------------
# Module-level shared fixture
# ---------------------------------------------------------------------------

_PROJECT_DIR: Path | None = None
_ASGI_APP: Any = None


def _get_shared_app() -> tuple[Path, Any]:
    global _PROJECT_DIR, _ASGI_APP
    if _PROJECT_DIR is None:
        _PROJECT_DIR, _ASGI_APP = _setup_project()
    return _PROJECT_DIR, _ASGI_APP


@pytest.fixture(scope="module")
def project_dir_and_app() -> tuple[Path, Any]:
    return _get_shared_app()


@pytest.fixture(scope="module")
def project_dir(project_dir_and_app: tuple[Path, Any]) -> Path:
    return project_dir_and_app[0]


@pytest.fixture(scope="module")
def asgi_app(project_dir_and_app: tuple[Path, Any]) -> Any:
    return project_dir_and_app[1]


# ---------------------------------------------------------------------------
# BEHAVIOR-01: GET /healthz → 200
# ---------------------------------------------------------------------------


@pytest.mark.anyio
async def test_b01_healthz_returns_200(asgi_app: Any) -> None:
    """B-01: GET /healthz must return 200."""
    transport = httpx.ASGITransport(app=asgi_app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.get("/healthz")
    assert response.status_code == 200, (
        f"Expected 200, got {response.status_code}; body: {response.text}"
    )


# ---------------------------------------------------------------------------
# BEHAVIOR-02: GET /metrics returns 200 or 503 (503 if SDK not installed)
# ---------------------------------------------------------------------------


@pytest.mark.anyio
async def test_b02_metrics_endpoint_returns_200_or_503(asgi_app: Any) -> None:
    """B-02: GET /metrics must return 200 (SDK installed) or 503 (SDK absent).

    The route is always registered; 503 is the graceful degradation when
    prometheus_client is not installed in the test environment.
    """
    transport = httpx.ASGITransport(app=asgi_app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.get("/metrics")
    assert response.status_code in (200, 503), (
        f"Expected 200 or 503 from /metrics, got {response.status_code}; body: {response.text}"
    )


# ---------------------------------------------------------------------------
# BEHAVIOR-03: /metrics endpoint is registered (not 404)
# ---------------------------------------------------------------------------


@pytest.mark.anyio
async def test_b03_metrics_endpoint_registered(asgi_app: Any) -> None:
    """B-03: /metrics must be registered — must NOT return 404."""
    transport = httpx.ASGITransport(app=asgi_app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.get("/metrics")
    assert response.status_code != 404, (
        "/metrics returned 404 — router is not registered in main.py"
    )


# ---------------------------------------------------------------------------
# BEHAVIOR-04: prometheus_client lazy in collectors.py
# ---------------------------------------------------------------------------


def test_b04_prometheus_client_not_at_top_level(project_dir: Path) -> None:
    """B-04: prometheus_client must NOT appear at module top-level."""
    collectors = project_dir / "app" / "metrics" / "collectors.py"
    assert collectors.exists()
    tree = ast.parse(collectors.read_text())
    for node in tree.body:
        if isinstance(node, ast.Import):
            for alias in node.names:
                assert "prometheus_client" not in alias.name, (
                    "prometheus_client at top-level of collectors.py"
                )
        elif isinstance(node, ast.ImportFrom):
            assert (node.module or "") != "prometheus_client", (
                "from prometheus_client at top-level of collectors.py"
            )


# ---------------------------------------------------------------------------
# BEHAVIOR-05: all functions <= 50 LOC
# ---------------------------------------------------------------------------


def test_b05_all_generated_functions_under_50_loc(project_dir: Path) -> None:
    """B-05: All generated functions in app/metrics/ are <= 50 LOC."""
    metrics_dir = project_dir / "app" / "metrics"
    violations: list[str] = []
    for py_file in sorted(metrics_dir.rglob("*.py")):
        tree = ast.parse(py_file.read_text())
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                loc = (node.end_lineno or node.lineno) - node.lineno + 1
                if loc > 50:
                    violations.append(f"{py_file.name}:{node.name} ({loc} LOC)")
    assert not violations, "Functions > 50 LOC:\n" + "\n".join(violations)


# ---------------------------------------------------------------------------
# BEHAVIOR-06: config fields use 4-space indent
# ---------------------------------------------------------------------------


def test_b06_config_fields_4_space_indent(project_dir: Path) -> None:
    """B-06: PROMETHEUS_* fields in config.py have 4-space indent."""
    config = project_dir / "app" / "core" / "config.py"
    assert config.exists()
    content = config.read_text()
    for line in content.splitlines():
        if "PROMETHEUS_ENABLED" in line or "PROMETHEUS_PREFIX" in line:
            assert line.startswith("    "), f"Not 4-space indented: {line!r}"


# ---------------------------------------------------------------------------
# BEHAVIOR-07: RequestMetrics record_request doesn't crash without SDK
# ---------------------------------------------------------------------------


def test_b07_request_metrics_record_without_sdk(project_dir: Path) -> None:
    """B-07: RequestMetrics.record_request must not raise even if prometheus_client missing."""
    import importlib.util

    spec = importlib.util.spec_from_file_location(
        "app.metrics.collectors_b07",
        str(project_dir / "app" / "metrics" / "collectors.py"),
    )
    assert spec and spec.loader
    orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    try:
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)  # type: ignore[attr-defined]
    finally:
        sys.path[:] = orig
    # get_metrics() returns None when not initialised — that's safe
    assert hasattr(mod, "RequestMetrics")
    assert hasattr(mod, "get_metrics")


# ---------------------------------------------------------------------------
# BEHAVIOR-08: middleware file importable
# ---------------------------------------------------------------------------


def test_b08_middleware_importable_without_crash(project_dir: Path) -> None:
    """B-08: app/metrics/middleware.py must be importable without raising."""
    mw_file = project_dir / "app" / "metrics" / "middleware.py"
    assert mw_file.exists()
    orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        import importlib.util

        spec = importlib.util.spec_from_file_location("app.metrics.middleware_b08", str(mw_file))
        assert spec and spec.loader
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)  # type: ignore[attr-defined]
    except Exception as exc:
        raise AssertionError(f"middleware.py raised on import: {exc}") from exc
    finally:
        sys.path[:] = orig
    assert hasattr(mod, "PrometheusMiddleware")


# ---------------------------------------------------------------------------
# BEHAVIOR-09: path label is low-cardinality (R6-S5-F1)
# ---------------------------------------------------------------------------


@pytest.mark.anyio
async def test_b09_path_label_is_low_cardinality(asgi_app: Any) -> None:
    """B-09 (R6-S5-F1): the path label is the route template; raw unmatched
    paths collapse to a single constant so a scanner cannot explode cardinality.

    Installs a recording stub for the middleware's ``get_metrics()`` (the SDK is
    absent in CI, so the real collector is a no-op), hits a matched route
    (/healthz) and a random unmatched path, then asserts the matched request
    records the route template while the unmatched request records the
    ``__unmatched__`` constant — never the raw scanner URL.
    """
    import importlib

    mw = importlib.import_module("app.metrics.middleware")
    recorded: list[str] = []

    class _RecordingStub:
        def record_request(self, *, method: str, path: str, status: int, duration: float) -> None:
            recorded.append(path)

    orig = mw.get_metrics
    mw.get_metrics = lambda: _RecordingStub()
    try:
        transport = httpx.ASGITransport(app=asgi_app, raise_app_exceptions=False)
        async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
            await client.get("/healthz")
            await client.get("/scanner-probe-9af3c2e1")
    finally:
        mw.get_metrics = orig

    assert "/healthz" in recorded, f"matched route template not recorded: {recorded}"
    assert "__unmatched__" in recorded, f"unmatched path did not collapse to a constant: {recorded}"
    assert "/scanner-probe-9af3c2e1" not in recorded, (
        f"raw unmatched path leaked into the metrics label (cardinality DoS): {recorded}"
    )


# ---------------------------------------------------------------------------
# Standalone runner
# ---------------------------------------------------------------------------


def _run_async_test(coro_fn: Any, *args: Any) -> None:
    import inspect

    async def _wrapper() -> None:
        await coro_fn(*args)

    if inspect.iscoroutinefunction(coro_fn):
        anyio.run(_wrapper)
    else:
        coro_fn(*args)


if __name__ == "__main__":
    _pd, _app = _get_shared_app()

    _TESTS: list[tuple[str, Any]] = [
        ("B-01: /healthz → 200", lambda: _run_async_test(test_b01_healthz_returns_200, _app)),
        (
            "B-02: /metrics → 200|503",
            lambda: _run_async_test(test_b02_metrics_endpoint_returns_200_or_503, _app),
        ),
        (
            "B-03: /metrics not 404",
            lambda: _run_async_test(test_b03_metrics_endpoint_registered, _app),
        ),
        ("B-04: prometheus_client lazy", lambda: test_b04_prometheus_client_not_at_top_level(_pd)),
        ("B-05: all funcs <= 50 LOC", lambda: test_b05_all_generated_functions_under_50_loc(_pd)),
        ("B-06: config 4-space indent", lambda: test_b06_config_fields_4_space_indent(_pd)),
        (
            "B-07: RequestMetrics safe without SDK",
            lambda: test_b07_request_metrics_record_without_sdk(_pd),
        ),
        ("B-08: middleware importable", lambda: test_b08_middleware_importable_without_crash(_pd)),
        (
            "B-09: path label low-cardinality",
            lambda: _run_async_test(test_b09_path_label_is_low_cardinality, _app),
        ),
    ]

    passed = failed = 0
    for name, fn in _TESTS:
        try:
            fn()
            print(f"  PASS  {name}")
            passed += 1
        except Exception as exc:
            print(f"  FAIL  {name}: {exc}")
            failed += 1

    print(f"\n{'=' * 60}")
    print(f"TOOL-086 BEHAVIOR: {passed}/{passed + failed} passed")
    if failed:
        sys.exit(1)
