# ruff: noqa: I001
"""BEHAVIOR TESTS — TOOL-023 add_stripe_checkout.

Proves that the code generated by ``add_stripe_checkout`` works at
**runtime**: boots a real ASGI app with SQLite+aiosqlite, hits the
checkout endpoints with an httpx client, and asserts the contract.

Patches applied (so tests run without Docker or Stripe credentials):
- ``app/core/db.py``                → SQLite + aiosqlite (no Postgres)
- ``app/middleware/idempotency.py`` → pass-through stub (no Redis)
- ``REDIS_URL`` env var             → removed (no Redis needed)

Run::

    PYTHONPATH=. pytest adapt/extend/infrastructure/test_add_stripe_checkout_behavior.py -v

or standalone::

    PYTHONPATH=. python3 adapt/extend/infrastructure/test_add_stripe_checkout_behavior.py
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Environment setup — MUST happen before any app import
# ---------------------------------------------------------------------------
import os

os.environ.setdefault("RATE_LIMITING_ENABLED", "false")
os.environ.setdefault("ENVIRONMENT", "local")
os.environ.setdefault("SECRET_KEY", "behavior-test-checkout-secret-key-32+chars!")
os.environ.setdefault("STRIPE_SECRET_KEY", "sk_test_behavior")
os.environ.setdefault("STRIPE_WEBHOOK_SECRET", "whsec_behavior_test")
os.environ.pop("REDIS_URL", None)

import ast
import importlib
import json
import sys
import textwrap
from pathlib import Path
from typing import Any

import anyio
import httpx
import pytest

from adapt.contracts import ToolInput
from adapt.extend.infrastructure.add_stripe_checkout import add_stripe_checkout
from tests.common.fixture_factory import create_fixture_project


# ---------------------------------------------------------------------------
# Patch templates
# ---------------------------------------------------------------------------

_SQLITE_DB_PY = textwrap.dedent("""\
    \"\"\"Patched db.py — SQLite+aiosqlite, no Docker required.\"\"\"

    from sqlalchemy import text
    from sqlalchemy.ext.asyncio import create_async_engine

    engine = create_async_engine(
        "sqlite+aiosqlite:///:memory:",
        echo=False,
        future=True,
        connect_args={"check_same_thread": False},
    )


    async def init_db() -> None:
        \"\"\"Run startup checks (connection test).\"\"\"
        async with engine.begin() as conn:
            await conn.execute(text("SELECT 1"))


    __all__ = ["engine", "init_db"]
""")

_PASSTHROUGH_IDEMPOTENCY_PY = textwrap.dedent("""\
    \"\"\"Patched idempotency.py — pass-through stub (no Redis).\"\"\"

    from __future__ import annotations

    from starlette.middleware.base import BaseHTTPMiddleware, RequestResponseEndpoint
    from starlette.requests import Request
    from starlette.responses import Response


    class IdempotencyMiddleware(BaseHTTPMiddleware):
        \"\"\"No-op pass-through stub for testing without Redis.\"\"\"

        async def dispatch(
            self,
            request: Request,
            call_next: RequestResponseEndpoint,
        ) -> Response:
            return await call_next(request)
""")


# ---------------------------------------------------------------------------
# Setup helpers
# ---------------------------------------------------------------------------


def _patch_project(project_dir: Path) -> None:
    """Apply SQLite + idempotency stubs to the fixture project."""
    (project_dir / "app" / "core" / "db.py").write_text(_SQLITE_DB_PY)
    idem = project_dir / "app" / "middleware" / "idempotency.py"
    if idem.exists():
        idem.write_text(_PASSTHROUGH_IDEMPOTENCY_PY)


def _load_app(project_dir: Path) -> Any:
    """Load ``app.main:app`` from *project_dir* in an isolated sys.path context."""
    _orig_path = sys.path.copy()
    sys.path.insert(0, str(project_dir))

    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]

    try:
        app_module = importlib.import_module("app.main")
    finally:
        sys.path[:] = _orig_path

    return app_module.app


def _setup_project() -> tuple[Path, Any]:
    """Create, apply tool, patch, and load app. Returns (project_dir, asgi_app)."""
    project_dir = create_fixture_project(name="checkout_behavior")

    result = add_stripe_checkout(ToolInput(project_dir=str(project_dir)))
    assert result.status == "success", (
        f"add_stripe_checkout failed: {result.error}\nnotes: {result.notes}"
    )

    _patch_project(project_dir)
    asgi_app = _load_app(project_dir)
    return project_dir, asgi_app


# ---------------------------------------------------------------------------
# Module-level shared fixture
# ---------------------------------------------------------------------------

_PROJECT_DIR: Path | None = None
_ASGI_APP: Any = None


def _get_shared_app() -> tuple[Path, Any]:
    global _PROJECT_DIR, _ASGI_APP
    if _PROJECT_DIR is None:
        _PROJECT_DIR, _ASGI_APP = _setup_project()
    return _PROJECT_DIR, _ASGI_APP


@pytest.fixture(scope="module")
def project_dir_and_app() -> tuple[Path, Any]:
    """Shared module-scoped fixture: one project for all behavior tests."""
    return _get_shared_app()


@pytest.fixture(scope="module")
def project_dir(project_dir_and_app: tuple[Path, Any]) -> Path:
    return project_dir_and_app[0]


@pytest.fixture(scope="module")
def asgi_app(project_dir_and_app: tuple[Path, Any]) -> Any:
    return project_dir_and_app[1]


# ---------------------------------------------------------------------------
# BEHAVIOR-01: GET /healthz → 200
# ---------------------------------------------------------------------------


@pytest.mark.anyio
async def test_b01_healthz_returns_200(asgi_app: Any) -> None:
    """B-01: GET /healthz must return 200 — base liveness probe."""
    transport = httpx.ASGITransport(app=asgi_app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.get("/healthz")
    assert response.status_code == 200, (
        f"Expected 200, got {response.status_code}; body: {response.text}"
    )


# ---------------------------------------------------------------------------
# BEHAVIOR-02: POST /payments/checkout without auth → 401/403/404/422
# ---------------------------------------------------------------------------


@pytest.mark.anyio
async def test_b02_create_checkout_without_auth_denied(asgi_app: Any) -> None:
    """B-02: POST /payments/checkout without auth must NOT return 500."""
    transport = httpx.ASGITransport(app=asgi_app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post(
            "/api/v1/payments/checkout",
            json={
                "amount_cents": 1000,
                "currency": "USD",
                "product_name": "test",
            },
        )
    assert response.status_code in (401, 403, 404, 422), (
        f"Expected 401/403/404/422, got {response.status_code}; body: {response.text}"
    )


# ---------------------------------------------------------------------------
# BEHAVIOR-03: GET /payments/{id} without auth → 401/403/404/422
# ---------------------------------------------------------------------------


@pytest.mark.anyio
async def test_b03_get_payment_without_auth_denied(asgi_app: Any) -> None:
    """B-03: GET /payments/{id} without auth must NOT return 500."""
    transport = httpx.ASGITransport(app=asgi_app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.get("/api/v1/payments/00000000-0000-0000-0000-000000000001")
    assert response.status_code in (401, 403, 404, 422), (
        f"Expected 401/403/404/422, got {response.status_code}; body: {response.text}"
    )


# ---------------------------------------------------------------------------
# BEHAVIOR-04: POST /payments/webhook/stripe with no sig → 400 / 500 / SDK absent
# ---------------------------------------------------------------------------


@pytest.mark.anyio
async def test_b04_webhook_without_signature_returns_400(asgi_app: Any) -> None:
    """B-04: webhook without Stripe-Signature is rejected (lazy SDK guard).

    When the ``stripe`` SDK is installed:
      - missing/invalid sig → 400 (``stripe.Webhook.construct_event`` raises).
    When the SDK is NOT installed:
      - the lazy ``import stripe`` raises ``ModuleNotFoundError`` which
        propagates as a 500 (or ModuleNotFoundError) — both outcomes prove
        the route exists and the lazy-import guard is in place.
    """
    transport = httpx.ASGITransport(app=asgi_app, raise_app_exceptions=False)
    try:
        async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
            response = await client.post(
                "/api/v1/payments/webhook/stripe",
                content=b'{"type": "checkout.session.completed"}',
                headers={"content-type": "application/json"},
            )
        assert response.status_code in (400, 422, 500), (
            f"Expected 400/422/500 for missing signature, "
            f"got {response.status_code}; body: {response.text}"
        )
    except ModuleNotFoundError as exc:
        assert "stripe" in str(exc).lower(), f"Unexpected ModuleNotFoundError: {exc}"


# ---------------------------------------------------------------------------
# BEHAVIOR-05: app/models/payment.py has correct AST structure
# ---------------------------------------------------------------------------


def test_b05_payment_model_ast_structure(project_dir: Path) -> None:
    """B-05: app/models/payment.py declares ``class Payment`` with the
    required columns at AST level (SQLAlchemy ORM models cannot be
    exec'd standalone due to ``from __future__ import annotations``).
    """
    model_file = project_dir / "app" / "models" / "payment.py"
    assert model_file.exists(), "app/models/payment.py not found"

    content = model_file.read_text()
    tree = ast.parse(content)

    class_names = [node.name for node in ast.walk(tree) if isinstance(node, ast.ClassDef)]
    assert "Payment" in class_names, (
        f"class Payment not found in app/models/payment.py; classes: {class_names}"
    )

    payment_fields: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef) and node.name == "Payment":
            for item in node.body:
                if isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name):
                    payment_fields.append(item.target.id)

    for required_field in [
        "id",
        "stripe_session_id",
        "amount_cents",
        "currency",
        "status",
        "created_at",
    ]:
        assert required_field in payment_fields, (
            f"Required field '{required_field}' not in Payment model; found: {payment_fields}"
        )


# ---------------------------------------------------------------------------
# BEHAVIOR-06: app/schemas/payment.py imports without crash
# ---------------------------------------------------------------------------


def test_b06_payment_schemas_import_without_crash(project_dir: Path) -> None:
    """B-06: app/schemas/payment.py must be importable without raising."""
    schema_file = project_dir / "app" / "schemas" / "payment.py"
    assert schema_file.exists(), "app/schemas/payment.py not found"

    import importlib.util as _ilu

    spec = _ilu.spec_from_file_location("app.schemas.payment_behavior_test", str(schema_file))
    assert spec is not None and spec.loader is not None

    _orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    try:
        module = _ilu.module_from_spec(spec)
        spec.loader.exec_module(module)  # type: ignore[attr-defined]
    except Exception as exc:
        raise AssertionError(f"app/schemas/payment.py raised on import: {exc}") from exc
    finally:
        sys.path[:] = _orig

    assert hasattr(module, "CheckoutSessionCreate"), "CheckoutSessionCreate not found"
    assert hasattr(module, "PaymentPublic"), "PaymentPublic not found"
    assert hasattr(module, "PaymentListResponse"), "PaymentListResponse not found"


# ---------------------------------------------------------------------------
# BEHAVIOR-07: Config fields present in config.py
# ---------------------------------------------------------------------------


def test_b07_config_fields_present(project_dir: Path) -> None:
    """B-07: app/core/config.py must contain all 6 Stripe checkout config fields."""
    config_file = project_dir / "app" / "core" / "config.py"
    assert config_file.exists(), "app/core/config.py not found"
    content = config_file.read_text()
    for field in [
        "STRIPE_SECRET_KEY",
        "STRIPE_PUBLISHABLE_KEY",
        "STRIPE_WEBHOOK_SECRET",
        "STRIPE_API_VERSION",
        "STRIPE_CHECKOUT_SUCCESS_URL",
        "STRIPE_CHECKOUT_CANCEL_URL",
    ]:
        assert field in content, f"{field} not found in app/core/config.py"


# ---------------------------------------------------------------------------
# BEHAVIOR-08: stripe NOT at module top-level in any generated app/ file
# ---------------------------------------------------------------------------


def test_b08_stripe_not_at_module_top_level(project_dir: Path) -> None:
    """B-08: stripe must NOT be imported at module top-level in any app/ file."""
    app_dir = project_dir / "app"
    violations: list[str] = []

    for py_file in sorted(app_dir.rglob("*.py")):
        try:
            tree = ast.parse(py_file.read_text())
        except SyntaxError:
            continue

        for node in tree.body:
            if isinstance(node, ast.Import):
                for alias in node.names:
                    if alias.name == "stripe" or alias.name.startswith("stripe."):
                        violations.append(
                            f"{py_file.relative_to(project_dir)}:{node.lineno}: import stripe"
                        )
            elif (
                isinstance(node, ast.ImportFrom)
                and node.module
                and (node.module == "stripe" or node.module.startswith("stripe."))
            ):
                violations.append(
                    f"{py_file.relative_to(project_dir)}:{node.lineno}: from stripe import ..."
                )

    assert not violations, "stripe found at top-level in the following files:\n" + "\n".join(
        f"  {v}" for v in violations
    )


# ---------------------------------------------------------------------------
# Standalone runner (no pytest required)
# ---------------------------------------------------------------------------


def _run_async_test(coro_fn: Any, *args: Any) -> None:
    """Run an async test function synchronously via anyio.run."""
    import inspect

    async def _wrapper() -> None:
        await coro_fn(*args)

    if inspect.iscoroutinefunction(coro_fn):
        anyio.run(_wrapper)
    else:
        coro_fn(*args)


if __name__ == "__main__":
    _pd, _app = _get_shared_app()

    _TESTS: list[tuple[str, Any]] = [
        ("B-01: /healthz → 200", lambda: _run_async_test(test_b01_healthz_returns_200, _app)),
        (
            "B-02: POST /payments/checkout no auth → 401/422",
            lambda: _run_async_test(test_b02_create_checkout_without_auth_denied, _app),
        ),
        (
            "B-03: GET /payments/{id} no auth → 401/422",
            lambda: _run_async_test(test_b03_get_payment_without_auth_denied, _app),
        ),
        (
            "B-04: webhook no sig → 400/500/ModuleNotFoundError",
            lambda: _run_async_test(test_b04_webhook_without_signature_returns_400, _app),
        ),
        ("B-05: payment model AST structure", lambda: test_b05_payment_model_ast_structure(_pd)),
        (
            "B-06: payment schemas import clean",
            lambda: test_b06_payment_schemas_import_without_crash(_pd),
        ),
        ("B-07: config fields present", lambda: test_b07_config_fields_present(_pd)),
        (
            "B-08: stripe NOT at module top-level",
            lambda: test_b08_stripe_not_at_module_top_level(_pd),
        ),
    ]

    passed = 0
    failed = 0
    failures: list[str] = []

    for name, fn in _TESTS:
        try:
            fn()
            print(f"  PASS  {name}")
            passed += 1
        except Exception as exc:
            print(f"  FAIL  {name}: {exc}")
            failures.append(f"{name}: {exc}")
            failed += 1

    total = passed + failed
    result_status = "PASS" if failed == 0 else "FAIL"

    contract = {
        "tool": "TOOL-023 add_stripe_checkout",
        "test_file": "test_add_stripe_checkout_behavior.py",
        "total": total,
        "passed": passed,
        "failed": failed,
        "status": result_status,
        "failures": failures,
        "coverage": [
            "GET /healthz → 200",
            "POST /payments/checkout without auth → 401/403/404/422",
            "GET /payments/{id} without auth → 401/403/404/422",
            "POST /payments/webhook/stripe without sig → 400/422/500/ModuleNotFoundError",
            "app/models/payment.py AST structure (class Payment + required fields)",
            "app/schemas/payment.py imports clean (CheckoutSessionCreate, PaymentPublic, PaymentListResponse)",
            "config fields: STRIPE_SECRET_KEY, STRIPE_PUBLISHABLE_KEY, "
            "STRIPE_WEBHOOK_SECRET, STRIPE_API_VERSION, STRIPE_CHECKOUT_SUCCESS_URL, "
            "STRIPE_CHECKOUT_CANCEL_URL",
            "stripe NOT at module top-level in any app/ file",
        ],
    }

    print(f"\n{'=' * 60}")
    print(f"TOOL-023 BEHAVIOR: {passed}/{total} passed")
    print("\nDelivery contract JSON:")
    print(json.dumps(contract, indent=2))

    if failed:
        sys.exit(1)
