from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class CommandBusProtocol(Protocol):
    """Auto-inferred Protocol surface for `CommandBus`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_staging/`.
    """

    def register(self, command_name: str, handler: Handler) -> None: ...
    async def dispatch(self, command: object, **kwargs) -> Any: ...
