from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class FeatureToggleServiceProtocol(Protocol):
    """Auto-inferred Protocol surface for `FeatureToggleService`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    async def is_enabled(self, name: str, *, user_id: str | None = None, environment: str = 'production', default: bool = False) -> bool: ...
    async def create_toggle(self, toggle_in: ToggleCreate) -> ToggleRead: ...
    async def update_toggle(self, name: str, toggle_in: ToggleUpdate) -> ToggleRead | None: ...
    async def list_toggles(self) -> list[ToggleRead]: ...
