from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class OnboardingProgressProtocol(Protocol):
    """Auto-inferred Protocol surface for `OnboardingProgress`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_staging/`.
    """

    def to_dict(self) -> dict: ...
