"""Protocol for SessionStore — generated from SessionStore.py."""

from __future__ import annotations

from typing import Any, Optional, Protocol, runtime_checkable

@runtime_checkable
class SessionStore(Protocol):
    """SessionStore primitive — server-side session lifecycle with fixation resistance."""

    def create(self, subject: str) -> Session: ...
    def load(self, session_id: str) -> Session | None: ...
    def rotate(self, session_id: str) -> Session: ...
    def revoke(self, session_id: str) -> None: ...
    def revoke_all_for_subject(self, subject: str) -> int: ...
