"""Shared layout-detection helper for adapt tools.

Modern projects generated by this skill have a ``project/app/`` subdirectory
where all Python source lives. Legacy projects (or external projects being
adapted) may have a flat layout with source at the project root.

``resolve_app_root(project_dir)`` returns the directory adapt tools should
write source code into:

- ``<project_dir>/app`` if it exists (modern layout)
- ``<project_dir>`` otherwise (flat layout)

Project-root files (``Dockerfile``, ``.env.example``, ``requirements.txt``,
``docker-compose.yml``, ``.github/``, ``tests/``) always live at the
project root, not under ``app/`` — for those, use ``project_dir`` directly.
"""

from __future__ import annotations

from pathlib import Path


def resolve_app_root(project_dir: str | Path) -> Path:
    """Return the directory where Python source code should be written.

    Detects whether the project uses the modern ``app/`` subdirectory
    layout or a legacy flat layout.

    Args:
        project_dir: Root directory of the project.

    Returns:
        ``<project_dir>/app`` if that directory exists, otherwise
        ``<project_dir>``.
    """
    root = Path(project_dir)
    app_dir = root / "app"
    if app_dir.is_dir():
        return app_dir
    return root


def project_root(project_dir: str | Path) -> Path:
    """Return the project root (always the original ``project_dir``).

    Convenience for tools that write project-level files like
    ``requirements.txt`` or ``docker-compose.yml`` — these never go
    under ``app/``.
    """
    return Path(project_dir)
