"""Internal helpers for :mod:`generators.orchestrator` (file 2 of 3).

Leaf helper functions extracted verbatim from the original
``generators/orchestrator.py`` during the ≤500-LOC file split.  These
functions write standalone artefacts (BOLA audit, requirements.txt,
package ``__init__.py`` files) and are imported back into the public
``generators.orchestrator`` module so behaviour is unchanged.

DO NOT import this module directly — use ``generators.orchestrator``.
"""

from __future__ import annotations

from pathlib import Path


def _write_bola_shared_models_audit(
    out: Path,
    shared: list[str],
    prefix: str,
) -> Path:
    """Emit ``tests/test_bola_shared_models.py`` documenting BOLA opt-outs.

    The file lists every model that was passed in ``shared_models=`` and
    asserts (at import time) that the list is exactly what was declared.
    Reviewers grep for ``test_bola_shared_models`` to see which models
    intentionally bypass the per-object ownership guard.

    Args:
        out: Project root directory.
        shared: Sorted list of shared (BOLA-opt-out) model names.
        prefix: API route prefix (e.g. ``/api/v1``) — embedded in the
            docstring so reviewers know which routes are affected.

    Returns:
        Path to the emitted audit test file.
    """
    tests_dir = out / "tests"
    tests_dir.mkdir(parents=True, exist_ok=True)
    audit_path = tests_dir / "test_bola_shared_models.py"

    bullet_lines = "\n".join(
        f"  * ``{m}``  -> ``{prefix}/{m.lower()}s/`` (no per-object guard)" for m in shared
    )
    shared_repr = repr(shared)

    parts = [
        '"""BOLA opt-out audit — auto-generated by generate_project.',
        "",
        "This file documents every model passed in ``shared_models=`` to the",
        "project generator.  Each model listed here:",
        "",
        "  * Has an ``owner_id`` column populated server-side on create.",
        "  * Does NOT enforce per-object ownership on GET-by-id / PATCH / DELETE.",
        "  * Therefore: any authenticated user may read / update / delete any",
        "    row of these tables.",
        "",
        "Shared models in this project:",
        bullet_lines,
        "",
        "If you did NOT intend any of these models to be open-access, REMOVE",
        "them from ``shared_models=...`` in your ``generate_project(...)`` call",
        "and regenerate — they will get the secure-by-default BOLA guard back.",
        "",
        "This file exists so the open-access policy is auditable: a reviewer",
        "running ``grep -r test_bola_shared_models`` immediately sees every",
        "intentional opt-out.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "",
        "# Authoritative list of BOLA-opt-out models (audit anchor).",
        f"SHARED_MODELS: frozenset[str] = frozenset({shared_repr})",
        "",
        "",
        "def test_shared_models_list_matches_generator_input() -> None:",
        '    """Shared list matches what was passed to generate_project()."""',
        f"    assert SHARED_MODELS == frozenset({shared_repr}), (",
        '        "shared_models drift — regenerate the project."',
        "    )",
        "",
        "",
        "def test_shared_models_documented() -> None:",
        '    """Every shared model is named in this module\'s docstring."""',
        '    doc = __doc__ or ""',
        "    for model in SHARED_MODELS:",
        '        assert f"``{model}``" in doc, (',
        '            f"shared model {model!r} missing from audit docstring"',
        "        )",
        "",
    ]
    audit_path.write_text("\n".join(parts))
    return audit_path


def _generate_requirements(
    out: Path,
    with_auth: bool,
    with_redis: bool,
    with_otel: bool,
    with_prometheus: bool,
    with_sentry: bool = False,
) -> None:
    """Write requirements.txt with pinned, production-grade dependencies.

    When ``with_sentry`` is True, ``sentry-sdk`` MUST be present — the
    emitted ``main.py`` imports it unconditionally under that flag and
    the app would ``ModuleNotFoundError`` at boot without the pin.
    """
    deps = [
        "fastapi>=0.115.0",
        "uvicorn[standard]>=0.32.0",
        "pydantic>=2.10.0",
        "pydantic-settings>=2.6.0",
        "sqlalchemy[asyncio]>=2.0.36",
        "asyncpg>=0.30.0",
        "alembic>=1.14.0",
        "email-validator>=2.2.0",
        "structlog>=24.4.0",
        "httpx>=0.28.0",
    ]
    if with_auth:
        deps.extend(
            [
                "pwdlib[argon2]>=0.2.1",
                "PyJWT>=2.9.0",
                "python-multipart>=0.0.12",
                "slowapi>=0.1.9",
            ]
        )
    if with_redis:
        deps.append("redis[hiredis]>=5.2.0")
    if with_otel:
        deps.extend(
            [
                "opentelemetry-api>=1.28.0",
                "opentelemetry-sdk>=1.28.0",
                "opentelemetry-exporter-otlp>=1.28.0",
                "opentelemetry-instrumentation-fastapi>=0.49b0",
                "opentelemetry-instrumentation-sqlalchemy>=0.49b0",
                "opentelemetry-instrumentation-httpx>=0.49b0",
            ]
        )
    if with_prometheus:
        deps.extend(
            [
                "prometheus-client>=0.21.0",
            ]
        )
    if with_sentry:
        deps.append("sentry-sdk>=2.18.0")
    (out / "requirements.txt").write_text("\n".join(sorted(deps)) + "\n")


def _generate_package_inits(
    out: Path,
    models: dict[str, dict[str, str]],
    with_auth: bool,
) -> None:
    """Create __init__.py files for all packages and assemble the API router."""
    # Package init files (make directories importable)
    for pkg in ["core", "models", "crud", "schemas", "middleware", "api", "api/routes", "routes"]:
        pkg_dir = out / pkg
        if pkg_dir.exists():
            init_file = pkg_dir / "__init__.py"
            if not init_file.exists():
                init_file.write_text("")
        # Also handle observability and alerts if they exist
    for pkg in ["observability", "alerts"]:
        pkg_dir = out / pkg
        if pkg_dir.exists() and not (pkg_dir / "__init__.py").exists():
            (pkg_dir / "__init__.py").write_text("")

    # routes/__init__.py — exports:
    #   - health_router  → mounted at ROOT in main.py (K8s convention)
    #   - api_router     → mounted under prefix (/api/v1) in main.py
    routes_init = out / "routes" / "__init__.py"
    lines = [
        '"""Route registration."""',
        "",
        "from fastapi import APIRouter",
        "",
        "from app.routes.health import router as health_router",
        "",
        "# api_router collects all business routes; mounted under /api/v1 in main.py.",
        "# health_router is exported separately and mounted at ROOT.",
        "api_router = APIRouter()",
    ]

    # Include webhooks router if Stripe integration was added (registered separately
    # because webhooks have raw body parsing requirements)
    webhooks_path = out / "routes" / "webhooks.py"
    if webhooks_path.exists():
        lines.insert(4, "from app.routes.webhooks import router as webhooks_router")
        lines.append("api_router.include_router(webhooks_router)")

    # Include auth routes if generated
    if with_auth and (out / "api" / "routes" / "login.py").exists():
        lines.insert(4, "from app.api.routes.login import router as login_router")
        lines.append("api_router.include_router(login_router)")

    # Include user management routes if generated
    if with_auth and (out / "api" / "routes" / "users.py").exists():
        lines.insert(4, "from app.api.routes.users import router as users_router")
        lines.append("api_router.include_router(users_router)")

    # Include domain model routes
    for model_name in models:
        lower = model_name.lower()
        route_file = out / "api" / "routes" / f"{lower}.py"
        if route_file.exists():
            lines.insert(4, f"from app.api.routes.{lower} import router as {lower}_router")
            lines.append(f"api_router.include_router({lower}_router)")

    lines.append("")
    lines.append('__all__ = ["api_router", "health_router"]')
    lines.append("")
    routes_init.write_text("\n".join(lines))

    # models/__init__.py — import all models so Alembic can discover them
    models_dir = out / "models"
    if models_dir.exists():
        models_init = models_dir / "__init__.py"
        model_imports = ['"""Import all models for Alembic auto-discovery."""', ""]
        for model_name in models:
            lower = model_name.lower()
            if (models_dir / f"{lower}.py").exists():
                model_imports.append(f"from app.models.{lower} import {model_name}  # noqa: F401")
        if with_auth and (models_dir / "user.py").exists():
            model_imports.append("from app.models.user import User  # noqa: F401")
        model_imports.append("")
        models_init.write_text("\n".join(model_imports))
