from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class AdaptiveTimeoutProtocol(Protocol):
    """Auto-inferred Protocol surface for `AdaptiveTimeout`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    def record(self, latency_ms: float) -> None: ...
    def get_timeout_s(self) -> float: ...
    def get_stats(self) -> dict[str, float]: ...
