from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class StorageConfigProtocol(Protocol):
    """Auto-inferred Protocol surface for `StorageConfig`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    @classmethod
    def from_settings(cls) -> 'StorageConfig': ...
