from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class WorkerFactoryProtocol(Protocol):
    """Auto-inferred Protocol surface for `WorkerFactory`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    async def create(self, client: Any) -> Any: ...
