from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class StorageBackendProtocol(Protocol):
    """Auto-inferred Protocol surface for `StorageBackend`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    @abstractmethod
    async def save(self, file_obj: object, content_type: str) -> tuple[str, int]: ...
    @abstractmethod
    async def get_url(self, stored_key: str, expires_in: int = 3600) -> str: ...
    @abstractmethod
    async def delete(self, stored_key: str) -> None: ...
