from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class EventStoreProtocol(Protocol):
    """Auto-inferred Protocol surface for `EventStore`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_staging/`.
    """

    async def append(self, session: AsyncSession, stream_id: str, event_type: str, data: dict[str, Any], expected_version: int | None = None) -> DomainEvent: ...
    async def get_stream(self, session: AsyncSession, stream_id: str, from_version: int = 1) -> list[DomainEvent]: ...
    async def get_all_since(self, session: AsyncSession, since: datetime, limit: int = 1000) -> list[DomainEvent]: ...
