from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class BulkheadProtocol(Protocol):
    """Auto-inferred Protocol surface for `Bulkhead`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    def acquire(self, group: str) -> _PoolState: ...
    def status(self) -> dict[str, dict[str, int]]: ...
