from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class DeprecationEntryProtocol(Protocol):
    """Auto-inferred Protocol surface for `DeprecationEntry`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    @property
    def sunset_header(self) -> str: ...
    @property
    def days_until_sunset(self) -> int: ...
    @property
    def should_warn(self) -> bool: ...
    def to_dict(self) -> dict[str, Any]: ...
