from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class RetryBudgetProtocol(Protocol):
    """Auto-inferred Protocol surface for `RetryBudget`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_staging/`.
    """

    def record_request(self) -> None: ...
    def record_retry(self) -> None: ...
    def can_retry(self) -> bool: ...
    def current_ratio(self) -> float: ...
    def stats(self) -> dict: ...
