"""Generator for test files that exercise every generated endpoint.

Generates pytest test modules for login, users, and CRUD model routes.
All tests use ``httpx.AsyncClient`` (provided by conftest.py) with
``pytest.mark.asyncio`` for async execution.

The generated tests are designed to work with the fixtures from
``generate_test_infrastructure()`` (conftest.py):
- ``client`` — httpx.AsyncClient wired to the FastAPI app
- ``superuser_token`` — dict ``{"Authorization": "Bearer ..."}``
- ``normal_user_token`` — dict ``{"Authorization": "Bearer ..."}``
"""

from __future__ import annotations

import re
import textwrap
from pathlib import Path


# ---------------------------------------------------------------------------
# Simple inflection (duplicated from crud_routes.py to stay self-contained)
# ---------------------------------------------------------------------------

_IRREGULAR: dict[str, str] = {
    "person": "people",
    "child": "children",
    "mouse": "mice",
    "goose": "geese",
    "ox": "oxen",
}


def _pluralize(word: str) -> str:
    """Return a naive English plural for *word*."""
    lower = word.lower()
    if lower in _IRREGULAR:
        plural = _IRREGULAR[lower]
        return word[0] + plural[1:] if word[0].isupper() else plural
    if re.search(r"(s|x|z|ch|sh)$", lower):
        return word + "es"
    if re.search(r"[^aeiou]y$", lower):
        return word[:-1] + "ies"
    return word + "s"


# ---------------------------------------------------------------------------
# Field value factory — generates sensible test payloads from type hints
# ---------------------------------------------------------------------------

_SAMPLE_VALUES: dict[str, str] = {
    "str": '"test-value"',
    "text": '"A longer test value for text fields."',
    "int": "42",
    "float": "3.14",
    "bool": "True",
    "Decimal": '"9.99"',
    "decimal": '"9.99"',
    "date": '"2025-01-15"',
    "datetime": '"2025-01-15T12:00:00Z"',
    "EmailStr": '"test@example.com"',
    "email": '"test@example.com"',
    "url": '"https://example.com"',
    "password": '"SecurePass123!"',
    "uuid": '"00000000-0000-0000-0000-000000000001"',
}

_UPDATE_VALUES: dict[str, str] = {
    "str": '"updated-value"',
    "text": '"An updated text value."',
    "int": "99",
    "float": "6.28",
    "bool": "False",
    "Decimal": '"19.99"',
    "decimal": '"19.99"',
    "date": '"2025-06-01"',
    "datetime": '"2025-06-01T18:00:00Z"',
    "EmailStr": '"updated@example.com"',
    "email": '"updated@example.com"',
    "url": '"https://updated.example.com"',
    "password": '"NewSecurePass456!"',
    "uuid": '"00000000-0000-0000-0000-000000000002"',
}


def _build_payload(fields: dict[str, str], values: dict[str, str]) -> str:
    """Build a Python dict literal from a fields mapping."""
    items: list[str] = []
    for name, raw_type in fields.items():
        type_key = raw_type.rstrip("?")
        val = values.get(type_key, '"test"')
        items.append(f'    "{name}": {val},')
    return "{\n" + "\n".join(items) + "\n}"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_test_suite(
    output_dir: str,
    models: dict[str, dict[str, str]] | None = None,
    owner_models: dict[str, str] | None = None,
    with_auth: bool = True,
) -> dict:
    """Generate test files for login, user, and CRUD model endpoints.

    Produces test modules that work with the conftest.py generated by
    ``generate_test_infrastructure()``.  Every test uses
    ``pytest.mark.asyncio`` and ``httpx.AsyncClient``.

    Args:
        output_dir: Project root.  Files are written to
            ``tests/api/routes/``.
        models: Domain models dict — ``{"Product": {"name": "str", ...}}``.
            A ``test_{model_lower}.py`` file is generated for each.
        owner_models: Which models have owner-scoped access.
            ``{"Product": "user"}`` means the model has ``owner_id``.
        with_auth: Generate login and user test files.

    Returns:
        Dict with ``files_created`` and ``notes``.
    """
    out = Path(output_dir) / "tests"
    out.mkdir(parents=True, exist_ok=True)

    api_dir = out / "api"
    api_dir.mkdir(parents=True, exist_ok=True)

    routes_dir = api_dir / "routes"
    routes_dir.mkdir(parents=True, exist_ok=True)

    files: list[str] = []
    notes: list[str] = []

    # --- Package init files ---
    for pkg_dir in [api_dir, routes_dir]:
        init_file = pkg_dir / "__init__.py"
        if not init_file.exists():
            init_file.write_text("")
            files.append(str(init_file))

    # --- Login tests ---
    if with_auth:
        login_path = routes_dir / "test_login.py"
        login_path.write_text(_generate_login_tests())
        files.append(str(login_path))
        notes.append("Generated tests/api/routes/test_login.py with 5 login/token tests.")

    # --- User tests ---
    if with_auth:
        users_path = routes_dir / "test_users.py"
        users_path.write_text(_generate_user_tests())
        files.append(str(users_path))
        notes.append("Generated tests/api/routes/test_users.py with 8 user endpoint tests.")

    # --- CRUD model tests ---
    if models:
        for model_name, fields in models.items():
            has_owner = model_name in (owner_models or {})
            model_path = routes_dir / f"test_{model_name.lower()}.py"
            model_path.write_text(
                _generate_crud_tests(model_name, fields, has_owner)
            )
            files.append(str(model_path))
            notes.append(
                f"Generated tests/api/routes/test_{model_name.lower()}.py "
                f"with 6 CRUD tests for {model_name}."
            )

    return {"files_created": files, "notes": notes}


# ---------------------------------------------------------------------------
# Login test module
# ---------------------------------------------------------------------------


def _generate_login_tests() -> str:
    return textwrap.dedent('''\
        """Tests for authentication endpoints (/login)."""

        from __future__ import annotations

        import pytest
        from httpx import AsyncClient

        from app.core.config import settings


        API = settings.API_V1_STR


        # -------------------------------------------------------------------
        # POST /login/access-token
        # -------------------------------------------------------------------


        @pytest.mark.asyncio
        async def test_login_success(
            client: AsyncClient,
            superuser_token: dict[str, str],
        ) -> None:
            """Valid credentials return 200 with an access_token."""
            login_data = {
                "username": settings.FIRST_SUPERUSER_EMAIL,
                "password": "testpassword123",
            }
            response = await client.post(f"{API}/login/access-token", data=login_data)

            assert response.status_code == 200
            body = response.json()
            assert "access_token" in body
            assert body["access_token"]


        @pytest.mark.asyncio
        async def test_login_wrong_password(
            client: AsyncClient,
            superuser_token: dict[str, str],
        ) -> None:
            """Wrong password returns 401."""
            login_data = {
                "username": settings.FIRST_SUPERUSER_EMAIL,
                "password": "wrong-password",
            }
            response = await client.post(f"{API}/login/access-token", data=login_data)

            assert response.status_code == 401


        @pytest.mark.asyncio
        async def test_login_nonexistent_user(client: AsyncClient) -> None:
            """Non-existent email returns 401."""
            login_data = {
                "username": "nobody@example.com",
                "password": "doesnotmatter",
            }
            response = await client.post(f"{API}/login/access-token", data=login_data)

            assert response.status_code == 401


        # -------------------------------------------------------------------
        # POST /login/test-token
        # -------------------------------------------------------------------


        @pytest.mark.asyncio
        async def test_test_token(
            client: AsyncClient,
            superuser_token: dict[str, str],
        ) -> None:
            """Valid token returns 200 with user info."""
            response = await client.post(
                f"{API}/login/test-token",
                headers=superuser_token,
            )

            assert response.status_code == 200
            body = response.json()
            assert "email" in body
            assert "id" in body


        @pytest.mark.asyncio
        async def test_test_token_no_auth(client: AsyncClient) -> None:
            """Missing token returns 401."""
            response = await client.post(f"{API}/login/test-token")

            assert response.status_code == 401
    ''')


# ---------------------------------------------------------------------------
# User test module
# ---------------------------------------------------------------------------


def _generate_user_tests() -> str:
    return textwrap.dedent('''\
        """Tests for user endpoints (/users)."""

        from __future__ import annotations

        import pytest
        from httpx import AsyncClient

        from app.core.config import settings


        API = settings.API_V1_STR


        # -------------------------------------------------------------------
        # POST /users/signup
        # -------------------------------------------------------------------


        @pytest.mark.asyncio
        async def test_signup(client: AsyncClient) -> None:
            """Public signup creates a user and returns 201 without hashed_password."""
            payload = {
                "email": "newuser@example.com",
                "password": "StrongPass123!",
                "full_name": "New User",
            }
            response = await client.post(f"{API}/users/signup", json=payload)

            assert response.status_code == 201
            body = response.json()
            assert body["email"] == "newuser@example.com"
            assert "hashed_password" not in body


        @pytest.mark.asyncio
        async def test_signup_duplicate(client: AsyncClient) -> None:
            """Duplicate email returns 400."""
            payload = {
                "email": "duplicate@example.com",
                "password": "StrongPass123!",
                "full_name": "First User",
            }
            await client.post(f"{API}/users/signup", json=payload)

            # Second signup with same email
            response = await client.post(f"{API}/users/signup", json=payload)
            assert response.status_code == 400


        # -------------------------------------------------------------------
        # GET /users/me
        # -------------------------------------------------------------------


        @pytest.mark.asyncio
        async def test_get_me(
            client: AsyncClient,
            normal_user_token: dict[str, str],
        ) -> None:
            """Authenticated user can fetch their own profile."""
            response = await client.get(
                f"{API}/users/me",
                headers=normal_user_token,
            )

            assert response.status_code == 200
            body = response.json()
            assert "email" in body
            assert "id" in body


        # -------------------------------------------------------------------
        # PATCH /users/me
        # -------------------------------------------------------------------


        @pytest.mark.asyncio
        async def test_update_me(
            client: AsyncClient,
            normal_user_token: dict[str, str],
        ) -> None:
            """Authenticated user can update their own profile."""
            response = await client.patch(
                f"{API}/users/me",
                headers=normal_user_token,
                json={"full_name": "Updated Name"},
            )

            assert response.status_code == 200
            body = response.json()
            assert body["full_name"] == "Updated Name"


        # -------------------------------------------------------------------
        # PATCH /users/me/password
        # -------------------------------------------------------------------


        @pytest.mark.asyncio
        async def test_update_password(
            client: AsyncClient,
            normal_user_token: dict[str, str],
        ) -> None:
            """Authenticated user can change their password."""
            response = await client.patch(
                f"{API}/users/me/password",
                headers=normal_user_token,
                json={
                    "current_password": "testpassword123",
                    "new_password": "NewSecurePass456!",
                },
            )

            assert response.status_code == 200
            body = response.json()
            assert body["message"] == "Password updated successfully"


        @pytest.mark.asyncio
        async def test_update_password_wrong_current(
            client: AsyncClient,
            normal_user_token: dict[str, str],
        ) -> None:
            """Wrong current password returns 400."""
            response = await client.patch(
                f"{API}/users/me/password",
                headers=normal_user_token,
                json={
                    "current_password": "wrong-password",
                    "new_password": "NewSecurePass456!",
                },
            )

            assert response.status_code == 400


        # -------------------------------------------------------------------
        # GET /users/ (superuser only)
        # -------------------------------------------------------------------


        @pytest.mark.asyncio
        async def test_list_users_superuser(
            client: AsyncClient,
            superuser_token: dict[str, str],
        ) -> None:
            """Superuser can list all users."""
            response = await client.get(
                f"{API}/users/",
                headers=superuser_token,
            )

            assert response.status_code == 200
            body = response.json()
            assert "data" in body
            assert "count" in body
            assert isinstance(body["data"], list)


        @pytest.mark.asyncio
        async def test_list_users_regular(
            client: AsyncClient,
            normal_user_token: dict[str, str],
        ) -> None:
            """Regular user cannot list all users (403)."""
            response = await client.get(
                f"{API}/users/",
                headers=normal_user_token,
            )

            assert response.status_code == 403
    ''')


# ---------------------------------------------------------------------------
# CRUD model test module
# ---------------------------------------------------------------------------


def _generate_crud_tests(
    model_name: str,
    fields: dict[str, str],
    has_owner: bool,
) -> str:
    """Generate a test module for a CRUD model's endpoints."""
    lower = model_name.lower()
    plural = _pluralize(lower)
    create_payload = _build_payload(fields, _SAMPLE_VALUES)
    update_payload = _build_payload(fields, _UPDATE_VALUES)

    # Indent payloads to match their position inside the function bodies
    create_indented = create_payload.replace("\n", "\n    ")
    update_indented = update_payload.replace("\n", "\n    ")

    return (
        f'"""Tests for {model_name} CRUD endpoints (/{plural})."""\n'
        f"\n"
        f"from __future__ import annotations\n"
        f"\n"
        f"import pytest\n"
        f"from httpx import AsyncClient\n"
        f"\n"
        f"from app.core.config import settings\n"
        f"\n"
        f"\n"
        f"API = settings.API_V1_STR\n"
        f"\n"
        f"\n"
        f"# -------------------------------------------------------------------\n"
        f"# Helpers\n"
        f"# -------------------------------------------------------------------\n"
        f"\n"
        f"\n"
        f"async def _create_{lower}(\n"
        f"    client: AsyncClient,\n"
        f"    token: dict[str, str],\n"
        f") -> dict:\n"
        f'    """Create a {model_name} and return the response body."""\n'
        f"    payload = {create_indented}\n"
        f"    response = await client.post(\n"
        f'        f"{{API}}/{plural}/",\n'
        f"        json=payload,\n"
        f"        headers=token,\n"
        f"    )\n"
        f"    assert response.status_code == 201\n"
        f"    return response.json()\n"
        f"\n"
        f"\n"
        f"# -------------------------------------------------------------------\n"
        f"# POST /{plural}/ -- Create\n"
        f"# -------------------------------------------------------------------\n"
        f"\n"
        f"\n"
        f"@pytest.mark.asyncio\n"
        f"async def test_create_{lower}(\n"
        f"    client: AsyncClient,\n"
        f"    superuser_token: dict[str, str],\n"
        f") -> None:\n"
        f'    """Creating a {model_name} returns 201."""\n'
        f"    body = await _create_{lower}(client, superuser_token)\n"
        f"\n"
        f'    assert "id" in body\n'
        f'    assert body["id"]\n'
        f"\n"
        f"\n"
        f"# -------------------------------------------------------------------\n"
        f"# GET /{plural}/ -- List\n"
        f"# -------------------------------------------------------------------\n"
        f"\n"
        f"\n"
        f"@pytest.mark.asyncio\n"
        f"async def test_list_{plural}(\n"
        f"    client: AsyncClient,\n"
        f"    superuser_token: dict[str, str],\n"
        f") -> None:\n"
        f'    """Listing {plural} returns 200 with data and count."""\n'
        f"    await _create_{lower}(client, superuser_token)\n"
        f"\n"
        f"    response = await client.get(\n"
        f'        f"{{API}}/{plural}/",\n'
        f"        headers=superuser_token,\n"
        f"    )\n"
        f"\n"
        f"    assert response.status_code == 200\n"
        f"    body = response.json()\n"
        f'    assert "data" in body\n'
        f'    assert "count" in body\n'
        f'    assert body["count"] >= 1\n'
        f"\n"
        f"\n"
        f"# -------------------------------------------------------------------\n"
        f"# GET /{plural}/{{id}} -- Get by ID\n"
        f"# -------------------------------------------------------------------\n"
        f"\n"
        f"\n"
        f"@pytest.mark.asyncio\n"
        f"async def test_get_{lower}(\n"
        f"    client: AsyncClient,\n"
        f"    superuser_token: dict[str, str],\n"
        f") -> None:\n"
        f'    """Fetching a {model_name} by ID returns 200."""\n'
        f"    created = await _create_{lower}(client, superuser_token)\n"
        f"\n"
        f"    response = await client.get(\n"
        f"        f\"{{API}}/{plural}/{{created['id']}}\",\n"
        f"        headers=superuser_token,\n"
        f"    )\n"
        f"\n"
        f"    assert response.status_code == 200\n"
        f"    body = response.json()\n"
        f'    assert body["id"] == created["id"]\n'
        f"\n"
        f"\n"
        f"# -------------------------------------------------------------------\n"
        f"# PUT /{plural}/{{id}} -- Update\n"
        f"# -------------------------------------------------------------------\n"
        f"\n"
        f"\n"
        f"@pytest.mark.asyncio\n"
        f"async def test_update_{lower}(\n"
        f"    client: AsyncClient,\n"
        f"    superuser_token: dict[str, str],\n"
        f") -> None:\n"
        f'    """Updating a {model_name} returns 200."""\n'
        f"    created = await _create_{lower}(client, superuser_token)\n"
        f"\n"
        f"    update_data = {update_indented}\n"
        f"    response = await client.patch(\n"
        f"        f\"{{API}}/{plural}/{{created['id']}}\",\n"
        f"        json=update_data,\n"
        f"        headers=superuser_token,\n"
        f"    )\n"
        f"\n"
        f"    assert response.status_code == 200\n"
        f"\n"
        f"\n"
        f"# -------------------------------------------------------------------\n"
        f"# DELETE /{plural}/{{id}} -- Delete\n"
        f"# -------------------------------------------------------------------\n"
        f"\n"
        f"\n"
        f"@pytest.mark.asyncio\n"
        f"async def test_delete_{lower}(\n"
        f"    client: AsyncClient,\n"
        f"    superuser_token: dict[str, str],\n"
        f") -> None:\n"
        f'    """Deleting a {model_name} returns 200."""\n'
        f"    created = await _create_{lower}(client, superuser_token)\n"
        f"\n"
        f"    response = await client.delete(\n"
        f"        f\"{{API}}/{plural}/{{created['id']}}\",\n"
        f"        headers=superuser_token,\n"
        f"    )\n"
        f"\n"
        f"    assert response.status_code == 200\n"
        f"\n"
        f"\n"
        f"# -------------------------------------------------------------------\n"
        f"# GET /{plural}/{{id}} -- Not Found\n"
        f"# -------------------------------------------------------------------\n"
        f"\n"
        f"\n"
        f"@pytest.mark.asyncio\n"
        f"async def test_get_{lower}_not_found(\n"
        f"    client: AsyncClient,\n"
        f"    superuser_token: dict[str, str],\n"
        f") -> None:\n"
        f'    """Fetching a non-existent {model_name} returns 404."""\n'
        f'    fake_id = "00000000-0000-0000-0000-000000000000"\n'
        f"    response = await client.get(\n"
        f'        f"{{API}}/{plural}/{{fake_id}}",\n'
        f"        headers=superuser_token,\n"
        f"    )\n"
        f"\n"
        f"    assert response.status_code == 404\n"
    )
