"""BEHAVIOR TEST — TOOL-110 add_sbom_guardian.

Proves that the code generated by ``add_sbom_guardian`` works at runtime:
boots a real ASGI app, hits /healthz, verifies generated scripts are
importable and functionally correct.

Patches applied (so tests run without Docker):
- ``app/core/db.py``               → SQLite + aiosqlite (no Postgres)
- ``app/middleware/idempotency.py`` → pass-through stub (no Redis)
- ``REDIS_URL`` env var             → removed (no Redis needed)

Run::

    PYTHONPATH=. pytest adapt/extend/testing_tools/test_add_sbom_guardian_behavior.py -v

or standalone::

    PYTHONPATH=. python3 adapt/extend/testing_tools/test_add_sbom_guardian_behavior.py
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Environment setup — MUST happen before any app import
# ---------------------------------------------------------------------------
import os

os.environ.setdefault("RATE_LIMITING_ENABLED", "false")
os.environ.setdefault("ENVIRONMENT", "local")
os.environ.setdefault("SECRET_KEY", "behavior-test-sbom-secret-key-32+chars!!")
os.environ.setdefault("SBOM_FAIL_ON_CRITICAL", "true")
os.environ.setdefault("SBOM_LOCKFILE_PATH", "requirements.txt")
os.environ.pop("REDIS_URL", None)

import ast
import importlib
import importlib.util
import sys
import textwrap
from pathlib import Path
from typing import Any

import anyio
import httpx
import pytest

from adapt.contracts import ToolInput
from adapt.extend.testing_tools.add_sbom_guardian import add_sbom_guardian
from tests.common.fixture_factory import create_fixture_project

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_SQLITE_DB_PY = textwrap.dedent("""\
    \"\"\"Patched db.py — SQLite+aiosqlite, no Docker required.\"\"\"

    from sqlalchemy import text
    from sqlalchemy.ext.asyncio import create_async_engine

    engine = create_async_engine(
        "sqlite+aiosqlite:///:memory:",
        echo=False,
        future=True,
        connect_args={"check_same_thread": False},
    )


    async def init_db() -> None:
        \"\"\"Run startup checks (connection test).\"\"\"
        async with engine.begin() as conn:
            await conn.execute(text("SELECT 1"))


    __all__ = ["engine", "init_db"]
""")

_PASSTHROUGH_IDEMPOTENCY_PY = textwrap.dedent("""\
    \"\"\"Patched idempotency.py — pass-through stub (no Redis).\"\"\"

    from __future__ import annotations

    from starlette.middleware.base import BaseHTTPMiddleware, RequestResponseEndpoint
    from starlette.requests import Request
    from starlette.responses import Response


    class IdempotencyMiddleware(BaseHTTPMiddleware):
        \"\"\"No-op pass-through stub for testing without Redis.\"\"\"

        async def dispatch(
            self,
            request: Request,
            call_next: RequestResponseEndpoint,
        ) -> Response:
            return await call_next(request)
""")


def _patch_project(project_dir: Path) -> None:
    """Apply SQLite + idempotency stubs to the fixture project."""
    (project_dir / "app" / "core" / "db.py").write_text(_SQLITE_DB_PY)
    idempotency_path = project_dir / "app" / "middleware" / "idempotency.py"
    if idempotency_path.exists():
        idempotency_path.write_text(_PASSTHROUGH_IDEMPOTENCY_PY)


def _load_app(project_dir: Path) -> Any:
    """Load ``app.main:app`` from *project_dir* in an isolated sys.path context."""
    _orig_path = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        app_module = importlib.import_module("app.main")
    finally:
        sys.path[:] = _orig_path
    return app_module.app


def _setup_project() -> tuple[Path, Any]:
    """Create, patch, apply tool, and load app."""
    project_dir = create_fixture_project(name="sbom_behavior")
    result = add_sbom_guardian(ToolInput(project_dir=str(project_dir)))
    assert result.status == "success", (
        f"add_sbom_guardian failed: {result.error}\nnotes: {result.notes}"
    )
    _patch_project(project_dir)
    asgi_app = _load_app(project_dir)
    return project_dir, asgi_app


# ---------------------------------------------------------------------------
# Module-level shared fixture
# ---------------------------------------------------------------------------

_PROJECT_DIR: Path | None = None
_ASGI_APP: Any = None


def _get_shared_app() -> tuple[Path, Any]:
    global _PROJECT_DIR, _ASGI_APP
    if _PROJECT_DIR is None:
        _PROJECT_DIR, _ASGI_APP = _setup_project()
    return _PROJECT_DIR, _ASGI_APP


@pytest.fixture(scope="module")
def project_dir_and_app() -> tuple[Path, Any]:
    return _get_shared_app()


@pytest.fixture(scope="module")
def project_dir(project_dir_and_app: tuple[Path, Any]) -> Path:
    return project_dir_and_app[0]


@pytest.fixture(scope="module")
def asgi_app(project_dir_and_app: tuple[Path, Any]) -> Any:
    return project_dir_and_app[1]


# ---------------------------------------------------------------------------
# B-01: GET /healthz → 200
# ---------------------------------------------------------------------------

@pytest.mark.anyio
async def test_b01_healthz_returns_200(asgi_app: Any) -> None:
    """B-01: GET /healthz must return 200 after add_sbom_guardian applied."""
    transport = httpx.ASGITransport(app=asgi_app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.get("/healthz")
    assert response.status_code == 200, (
        f"Expected 200, got {response.status_code}; body: {response.text}"
    )


# ---------------------------------------------------------------------------
# B-02: generate_sbom.py importable
# ---------------------------------------------------------------------------

def test_b02_generate_sbom_importable(project_dir: Path) -> None:
    """B-02: scripts/generate_sbom.py must be importable without raising."""
    sbom_script = project_dir / "scripts" / "generate_sbom.py"
    assert sbom_script.exists()
    orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k.startswith("scripts")]
    for key in stale:
        del sys.modules[key]
    try:
        spec = importlib.util.spec_from_file_location("scripts.generate_sbom_b02", str(sbom_script))
        assert spec and spec.loader
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)  # type: ignore[attr-defined]
    except Exception as exc:
        raise AssertionError(f"generate_sbom.py raised on import: {exc}") from exc
    finally:
        sys.path[:] = orig
    assert hasattr(mod, "generate_sbom"), "generate_sbom function not exported"


# ---------------------------------------------------------------------------
# B-03: verify_lockfile.py importable
# ---------------------------------------------------------------------------

def test_b03_verify_lockfile_importable(project_dir: Path) -> None:
    """B-03: scripts/verify_lockfile.py must be importable without raising."""
    lockfile_script = project_dir / "scripts" / "verify_lockfile.py"
    assert lockfile_script.exists()
    orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k.startswith("scripts")]
    for key in stale:
        del sys.modules[key]
    try:
        spec = importlib.util.spec_from_file_location("scripts.verify_lockfile_b03", str(lockfile_script))
        assert spec and spec.loader
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)  # type: ignore[attr-defined]
    except Exception as exc:
        raise AssertionError(f"verify_lockfile.py raised on import: {exc}") from exc
    finally:
        sys.path[:] = orig
    assert hasattr(mod, "verify"), "verify function not exported"


# ---------------------------------------------------------------------------
# B-04: generate_sbom() returns dict with component_count
# ---------------------------------------------------------------------------

def test_b04_generate_sbom_returns_valid_result(project_dir: Path, tmp_path: Path) -> None:
    """B-04: generate_sbom() returns dict with component_count and output_path."""
    sbom_script = project_dir / "scripts" / "generate_sbom.py"
    orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k.startswith("scripts")]
    for key in stale:
        del sys.modules[key]
    try:
        spec = importlib.util.spec_from_file_location("scripts.generate_sbom_b04", str(sbom_script))
        assert spec and spec.loader
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)  # type: ignore[attr-defined]
        output = str(tmp_path / "test_sbom.json")
        result = mod.generate_sbom(output)
    finally:
        sys.path[:] = orig
    assert "component_count" in result, f"Missing component_count: {result}"
    assert "output_path" in result, f"Missing output_path: {result}"
    assert isinstance(result["component_count"], int)
    assert result["component_count"] >= 0


# ---------------------------------------------------------------------------
# B-05: sbom.json is valid CycloneDX
# ---------------------------------------------------------------------------

def test_b05_sbom_json_valid_cyclonedx(project_dir: Path, tmp_path: Path) -> None:
    """B-05: Generated sbom.json has CycloneDX bomFormat and components array."""
    import json
    sbom_script = project_dir / "scripts" / "generate_sbom.py"
    orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k.startswith("scripts")]
    for key in stale:
        del sys.modules[key]
    try:
        spec = importlib.util.spec_from_file_location("scripts.generate_sbom_b05", str(sbom_script))
        assert spec and spec.loader
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)  # type: ignore[attr-defined]
        output = str(tmp_path / "sbom_b05.json")
        mod.generate_sbom(output)
    finally:
        sys.path[:] = orig
    data = json.loads(Path(output).read_text())
    assert data.get("bomFormat") == "CycloneDX", f"Wrong bomFormat: {data.get('bomFormat')}"
    assert "components" in data, "Missing 'components' in SBOM"
    assert isinstance(data["components"], list)


# ---------------------------------------------------------------------------
# B-06: verify() returns dict with passed key
# ---------------------------------------------------------------------------

def test_b06_verify_returns_passed_key(project_dir: Path) -> None:
    """B-06: verify(lockfile) returns dict with 'passed' boolean key."""
    lockfile_script = project_dir / "scripts" / "verify_lockfile.py"
    requirements = project_dir / "requirements.txt"
    orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k.startswith("scripts")]
    for key in stale:
        del sys.modules[key]
    try:
        spec = importlib.util.spec_from_file_location("scripts.verify_lockfile_b06", str(lockfile_script))
        assert spec and spec.loader
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)  # type: ignore[attr-defined]
        result = mod.verify(str(requirements), fail_on_critical=False)
    finally:
        sys.path[:] = orig
    assert "passed" in result, f"Missing 'passed' key: {result}"
    assert isinstance(result["passed"], bool)


# ---------------------------------------------------------------------------
# B-07: all generated functions <= 50 LOC
# ---------------------------------------------------------------------------

def test_b07_all_generated_functions_under_50_loc(project_dir: Path) -> None:
    """B-07: All generated functions in scripts/ are <= 50 LOC."""
    scripts_dir = project_dir / "scripts"
    violations: list[str] = []
    for py_file in sorted(scripts_dir.rglob("*.py")):
        tree = ast.parse(py_file.read_text())
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                loc = (node.end_lineno or node.lineno) - node.lineno + 1
                if loc > 50:
                    violations.append(f"{py_file.name}:{node.name} ({loc} LOC)")
    assert not violations, "Functions > 50 LOC:\n" + "\n".join(violations)


# ---------------------------------------------------------------------------
# B-08: config fields 4-space indent
# ---------------------------------------------------------------------------

def test_b08_config_fields_4_space_indent(project_dir: Path) -> None:
    """B-08: SBOM_* config fields have 4-space indent in config.py."""
    config = project_dir / "app" / "core" / "config.py"
    assert config.exists()
    content = config.read_text()
    for line in content.splitlines():
        if any(f in line for f in ("SBOM_FAIL_ON_CRITICAL", "SBOM_LOCKFILE_PATH")):
            assert line.startswith("    "), f"Not 4-space indented: {line!r}"


# ---------------------------------------------------------------------------
# Standalone runner
# ---------------------------------------------------------------------------

def _run_async_test(coro_fn: Any, *args: Any) -> None:
    import inspect

    async def _wrapper() -> None:
        await coro_fn(*args)

    if inspect.iscoroutinefunction(coro_fn):
        anyio.run(_wrapper)
    else:
        coro_fn(*args)


if __name__ == "__main__":
    import tempfile
    _pd, _app = _get_shared_app()
    _tmp = Path(tempfile.mkdtemp())

    _TESTS: list[tuple[str, Any]] = [
        ("B-01: /healthz → 200", lambda: _run_async_test(test_b01_healthz_returns_200, _app)),
        ("B-02: generate_sbom.py importable", lambda: test_b02_generate_sbom_importable(_pd)),
        ("B-03: verify_lockfile.py importable", lambda: test_b03_verify_lockfile_importable(_pd)),
        ("B-04: generate_sbom() returns valid result", lambda: test_b04_generate_sbom_returns_valid_result(_pd, _tmp)),
        ("B-05: sbom.json is valid CycloneDX", lambda: test_b05_sbom_json_valid_cyclonedx(_pd, _tmp)),
        ("B-06: verify() returns passed key", lambda: test_b06_verify_returns_passed_key(_pd)),
        ("B-07: all funcs <= 50 LOC", lambda: test_b07_all_generated_functions_under_50_loc(_pd)),
        ("B-08: config 4-space indent", lambda: test_b08_config_fields_4_space_indent(_pd)),
    ]

    passed = failed = 0
    for name, fn in _TESTS:
        try:
            fn()
            print(f"  PASS  {name}")
            passed += 1
        except Exception as exc:
            print(f"  FAIL  {name}: {exc}")
            failed += 1

    print(f"\n{'='*60}")
    print(f"TOOL-110 BEHAVIOR: {passed}/{passed + failed} passed")
    if failed:
        sys.exit(1)
