"""BEHAVIOR TEST — TOOL-117 add_schema_enforcer.

Proves that the code generated by ``add_schema_enforcer`` works at runtime:
boots a real ASGI app, verifies schema enforcement middleware is registered,
and exercises the core engine logic (shadow detection, extra-field rejection).

Patches applied (so tests run without Docker):
- ``app/core/db.py``         → SQLite + aiosqlite (no Postgres)
- ``app/middleware/idempotency.py`` → pass-through stub (no Redis)
- ``REDIS_URL`` env var      → removed

Run::

    PYTHONPATH=. pytest adapt/extend/testing_tools/test_add_schema_enforcer_behavior.py -v

or standalone::

    PYTHONPATH=. python3 adapt/extend/testing_tools/test_add_schema_enforcer_behavior.py
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Environment setup — MUST happen before any app import
# ---------------------------------------------------------------------------
import os

os.environ.setdefault("SCHEMA_ENFORCER_MODE", "detect")
os.environ.setdefault("SCHEMA_ENFORCER_BLOCK_SHADOW", "false")
os.environ.setdefault("ENVIRONMENT", "local")
os.environ.setdefault("SECRET_KEY", "behavior-test-schema-enforcer-secret-key-32+!")
os.environ.pop("REDIS_URL", None)

import ast
import importlib
import importlib.util
import json
import sys
import textwrap
from pathlib import Path
from typing import Any

import anyio
import httpx
import pytest

from adapt.contracts import ToolInput
from adapt.extend.testing_tools.add_schema_enforcer import add_schema_enforcer
from tests.common.fixture_factory import create_fixture_project


# ---------------------------------------------------------------------------
# Patch helpers
# ---------------------------------------------------------------------------

_SQLITE_DB_PY = textwrap.dedent("""\
    \"\"\"Patched db.py — SQLite+aiosqlite, no Docker required.\"\"\"

    from sqlalchemy import text
    from sqlalchemy.ext.asyncio import create_async_engine

    engine = create_async_engine(
        "sqlite+aiosqlite:///:memory:",
        echo=False,
        future=True,
        connect_args={"check_same_thread": False},
    )


    async def init_db() -> None:
        \"\"\"Run startup checks (connection test).\"\"\"
        async with engine.begin() as conn:
            await conn.execute(text("SELECT 1"))


    __all__ = ["engine", "init_db"]
""")

_PASSTHROUGH_IDEMPOTENCY_PY = textwrap.dedent("""\
    \"\"\"Patched idempotency.py — pass-through stub (no Redis).\"\"\"

    from __future__ import annotations

    from starlette.middleware.base import BaseHTTPMiddleware, RequestResponseEndpoint
    from starlette.requests import Request
    from starlette.responses import Response


    class IdempotencyMiddleware(BaseHTTPMiddleware):
        \"\"\"No-op pass-through stub for testing without Redis.\"\"\"

        async def dispatch(
            self,
            request: Request,
            call_next: RequestResponseEndpoint,
        ) -> Response:
            return await call_next(request)
""")


def _patch_project(project_dir: Path) -> None:
    """Apply SQLite + idempotency stubs to the fixture project."""
    (project_dir / "app" / "core" / "db.py").write_text(_SQLITE_DB_PY)
    mw_dir = project_dir / "app" / "middleware"
    mw_dir.mkdir(parents=True, exist_ok=True)
    (mw_dir / "idempotency.py").write_text(_PASSTHROUGH_IDEMPOTENCY_PY)


def _load_app(project_dir: Path) -> Any:
    """Load ``app.main:app`` from *project_dir* in an isolated sys.path context."""
    _orig_path = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        app_module = importlib.import_module("app.main")
    finally:
        sys.path[:] = _orig_path
    return app_module.app


def _setup_project() -> tuple[Path, Any]:
    """Create, apply tool, patch, and load app."""
    project_dir = create_fixture_project(name="se_behavior")
    result = add_schema_enforcer(ToolInput(project_dir=str(project_dir)))
    assert result.status == "success", (
        f"add_schema_enforcer failed: {result.error}\nnotes: {result.notes}"
    )
    _patch_project(project_dir)
    asgi_app = _load_app(project_dir)
    return project_dir, asgi_app


_PROJECT_DIR: Path | None = None
_ASGI_APP: Any = None


def _get_shared_app() -> tuple[Path, Any]:
    global _PROJECT_DIR, _ASGI_APP
    if _PROJECT_DIR is None:
        _PROJECT_DIR, _ASGI_APP = _setup_project()
    return _PROJECT_DIR, _ASGI_APP


@pytest.fixture(scope="module")
def project_dir_and_app() -> tuple[Path, Any]:
    return _get_shared_app()


@pytest.fixture(scope="module")
def project_dir(project_dir_and_app: tuple[Path, Any]) -> Path:
    return project_dir_and_app[0]


@pytest.fixture(scope="module")
def asgi_app(project_dir_and_app: tuple[Path, Any]) -> Any:
    return project_dir_and_app[1]


# ---------------------------------------------------------------------------
# BEHAVIOR-01: GET /healthz → 200
# ---------------------------------------------------------------------------

@pytest.mark.anyio
async def test_b01_healthz_returns_200(asgi_app: Any) -> None:
    """B-01: GET /healthz must return 200 — base liveness probe."""
    transport = httpx.ASGITransport(app=asgi_app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.get("/healthz")
    assert response.status_code == 200, (
        f"Expected 200, got {response.status_code}; body: {response.text}"
    )


# ---------------------------------------------------------------------------
# BEHAVIOR-02: Schema enforcer in detect mode passes requests through
# ---------------------------------------------------------------------------

@pytest.mark.anyio
async def test_b02_detect_mode_passes_requests(asgi_app: Any) -> None:
    """B-02: In detect mode, all requests must pass through (no blocking)."""
    transport = httpx.ASGITransport(app=asgi_app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.get("/healthz")
    assert response.status_code not in (403, 422), (
        f"Detect mode should not block requests, got {response.status_code}"
    )


# ---------------------------------------------------------------------------
# BEHAVIOR-03: Core engine imports without crash
# ---------------------------------------------------------------------------

def test_b03_core_engine_imports_without_crash(project_dir: Path) -> None:
    """B-03: app/core/schema_enforcer.py must be importable without raising."""
    core_file = project_dir / "app" / "core" / "schema_enforcer.py"
    assert core_file.exists(), "app/core/schema_enforcer.py not found"

    spec = importlib.util.spec_from_file_location(
        "app.core.schema_enforcer_behavior_test", str(core_file)
    )
    assert spec is not None and spec.loader is not None

    _orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    try:
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)  # type: ignore[attr-defined]
    except Exception as exc:
        raise AssertionError(
            f"app/core/schema_enforcer.py raised on import: {exc}"
        ) from exc
    finally:
        sys.path[:] = _orig

    assert hasattr(module, "load_spec"), "load_spec not found"
    assert hasattr(module, "detect_shadow_routes"), "detect_shadow_routes not found"
    assert hasattr(module, "has_extra_fields"), "has_extra_fields not found"


# ---------------------------------------------------------------------------
# BEHAVIOR-04: has_extra_fields detects injection
# ---------------------------------------------------------------------------

def test_b04_has_extra_fields_detects_mass_assignment(project_dir: Path) -> None:
    """B-04: has_extra_fields must flag unexpected keys as extras."""
    core_file = project_dir / "app" / "core" / "schema_enforcer.py"
    _orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k.startswith("app.core.schema")]
    for k in stale:
        del sys.modules[k]
    try:
        spec = importlib.util.spec_from_file_location("_se_core", str(core_file))
        assert spec and spec.loader
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)  # type: ignore[attr-defined]
    finally:
        sys.path[:] = _orig

    schema = {"properties": {"username": {}, "email": {}}}
    extras = module.has_extra_fields({"username": "x", "admin": True}, schema)
    assert "admin" in extras, f"Expected 'admin' in extras, got: {extras}"


# ---------------------------------------------------------------------------
# BEHAVIOR-05: detect_shadow_routes identifies undocumented paths
# ---------------------------------------------------------------------------

def test_b05_detect_shadow_routes(project_dir: Path) -> None:
    """B-05: detect_shadow_routes must flag routes absent from spec."""
    core_file = project_dir / "app" / "core" / "schema_enforcer.py"
    _orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    try:
        spec = importlib.util.spec_from_file_location("_se_core2", str(core_file))
        assert spec and spec.loader
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)  # type: ignore[attr-defined]
    finally:
        sys.path[:] = _orig

    shadow = module.detect_shadow_routes(["/admin/config"], {"/users"})
    assert "/admin/config" in shadow


# ---------------------------------------------------------------------------
# BEHAVIOR-06: fuzz test file parses without error
# ---------------------------------------------------------------------------

def test_b06_fuzz_test_file_parses(project_dir: Path) -> None:
    """B-06: tests/test_schema_fuzz.py must parse as valid Python."""
    fuzz_file = project_dir / "tests" / "test_schema_fuzz.py"
    assert fuzz_file.exists(), "tests/test_schema_fuzz.py not found"
    try:
        ast.parse(fuzz_file.read_text())
    except SyntaxError as exc:
        raise AssertionError(f"test_schema_fuzz.py has syntax error: {exc}") from exc


# ---------------------------------------------------------------------------
# BEHAVIOR-07: lazy SDK imports
# ---------------------------------------------------------------------------

def test_b07_no_optional_sdks_at_module_level(project_dir: Path) -> None:
    """B-07: No optional SDK should be imported at module level in any app/ file."""
    app_dir = project_dir / "app"
    optional_sdks = ["jsonschema", "schemathesis"]
    violations: list[str] = []

    for py_file in sorted(app_dir.rglob("*.py")):
        try:
            tree = ast.parse(py_file.read_text())
        except SyntaxError:
            continue
        for child in tree.body:
            if isinstance(child, ast.Import):
                for alias in child.names:
                    if any(alias.name == sdk or alias.name.startswith(sdk + ".") for sdk in optional_sdks):
                        violations.append(f"{py_file.name}:{child.lineno}: import {alias.name}")
            elif isinstance(child, ast.ImportFrom):
                if child.module and any(
                    child.module == sdk or child.module.startswith(sdk + ".")
                    for sdk in optional_sdks
                ):
                    violations.append(f"{py_file.name}:{child.lineno}: from {child.module} import ...")

    assert not violations, (
        "Optional SDK imported at module level:\n" + "\n".join(f"  {v}" for v in violations)
    )


# ---------------------------------------------------------------------------
# BEHAVIOR-08: all functions <= 50 LOC
# ---------------------------------------------------------------------------

def test_b08_all_functions_50_loc_or_less(project_dir: Path) -> None:
    """B-08: All generated functions in app/ must be <= 50 LOC."""
    app_dir = project_dir / "app"
    violations: list[str] = []
    for py_file in sorted(app_dir.rglob("*.py")):
        try:
            tree = ast.parse(py_file.read_text())
        except SyntaxError:
            continue
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                if hasattr(node, "end_lineno") and node.end_lineno:
                    loc = node.end_lineno - node.lineno + 1
                    if loc > 50:
                        violations.append(
                            f"{py_file.name}:{node.lineno}: {node.name} ({loc} LOC)"
                        )
    assert not violations, "Functions over 50 LOC:\n" + "\n".join(violations)


# ---------------------------------------------------------------------------
# BEHAVIOR-09: config 4-space indent
# ---------------------------------------------------------------------------

def test_b09_config_fields_4space_indent(project_dir: Path) -> None:
    """B-09: SCHEMA_ENFORCER_* fields must be inside Settings class body."""
    config_file = project_dir / "app" / "core" / "config.py"
    content = config_file.read_text()
    for line in content.splitlines():
        if "SCHEMA_ENFORCER_MODE" in line and "=" in line:
            assert line.startswith("    "), (
                f"Field not indented inside Settings: {line!r}"
            )
            return
    raise AssertionError("SCHEMA_ENFORCER_MODE not found in config.py")


# ---------------------------------------------------------------------------
# Shared runner helper
# ---------------------------------------------------------------------------

def _run_async_test(coro_fn: Any, *args: Any) -> None:
    """Run an async test function synchronously via anyio.run."""
    import inspect

    async def _wrapper() -> None:
        await coro_fn(*args)

    if inspect.iscoroutinefunction(coro_fn):
        anyio.run(_wrapper)
    else:
        coro_fn(*args)


# ---------------------------------------------------------------------------
# Standalone runner
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    _pd, _app = _get_shared_app()

    _TESTS: list[tuple[str, Any]] = [
        ("B-01: /healthz → 200", lambda: _run_async_test(test_b01_healthz_returns_200, _app)),
        ("B-02: detect mode passes requests", lambda: _run_async_test(test_b02_detect_mode_passes_requests, _app)),
        ("B-03: core engine imports clean", lambda: test_b03_core_engine_imports_without_crash(_pd)),
        ("B-04: has_extra_fields detects mass assignment", lambda: test_b04_has_extra_fields_detects_mass_assignment(_pd)),
        ("B-05: detect_shadow_routes works", lambda: test_b05_detect_shadow_routes(_pd)),
        ("B-06: fuzz test file parses", lambda: test_b06_fuzz_test_file_parses(_pd)),
        ("B-07: no optional sdks at module level", lambda: test_b07_no_optional_sdks_at_module_level(_pd)),
        ("B-08: all functions <= 50 LOC", lambda: test_b08_all_functions_50_loc_or_less(_pd)),
        ("B-09: config 4-space indent", lambda: test_b09_config_fields_4space_indent(_pd)),
    ]

    passed = failed = 0
    failures: list[str] = []

    for name, fn in _TESTS:
        try:
            fn()
            print(f"  PASS  {name}")
            passed += 1
        except Exception as exc:
            print(f"  FAIL  {name}: {exc}")
            failures.append(f"{name}: {exc}")
            failed += 1

    total = passed + failed
    status = "PASS" if failed == 0 else "FAIL"

    contract = {
        "tool": "TOOL-117 add_schema_enforcer",
        "test_file": "test_add_schema_enforcer_behavior.py",
        "total": total,
        "passed": passed,
        "failed": failed,
        "status": status,
        "failures": failures,
    }

    print(f"\n{'='*60}")
    print(f"TOOL-117 BEHAVIOR: {passed}/{total} passed")
    print(f"\nDelivery contract JSON:")
    print(json.dumps(contract, indent=2))

    if failed:
        sys.exit(1)
