"""
SKILL-001 Observability Tool: Generate Prometheus alerting rules and Grafana dashboard.

Creates production-ready alerting based on the Google SRE Workbook's multi-window
multi-burn-rate pattern, plus a Grafana dashboard with the Four Golden Signals
(Latency, Traffic, Errors, Saturation) and SLO error budget panels.

Generated files:
    prometheus_rules.yaml      -- Recording rules + multi-burn-rate alerts
    grafana_dashboard.json     -- Essential API monitoring panels (importable)
"""

from __future__ import annotations

MCP_TOOL = {
    'name': 'fastapi_observability_generate_alerts',
    'description': 'Generate Prometheus multi-burn-rate alerting rules and Grafana dashboard with Four Golden Signals + SLO error budget.',
    'tags': ['observability', 'generator'],
    'entry': 'generate_alerting_rules',
    'annotations': {'readOnlyHint': False, 'destructiveHint': False},
}

import json
import sys
import textwrap
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))
from core.models import Finding, Severity


# ---------------------------------------------------------------------------
# Prometheus Rules Generator
# ---------------------------------------------------------------------------


def _generate_prometheus_rules(
    service_name: str,
    slo_availability: float,
    slo_latency_p99_ms: int,
) -> str:
    """Generate Prometheus recording rules and multi-burn-rate alert rules.

    Follows the Google SRE Workbook multi-window multi-burn-rate pattern:
    - Fast burn (14.4x): pages immediately — 2% budget consumed in 1 hour
    - Medium burn (6x): pages — 5% budget consumed in 6 hours
    - Slow burn (1x): creates ticket — on track to exhaust budget
    """
    error_budget = round(1.0 - slo_availability, 6)
    latency_threshold_s = slo_latency_p99_ms / 1000.0

    # Calculate burn rates from the Google SRE Workbook table:
    # burn_rate = (1 / (1 - slo)) * (budget_consumed / hours * (window_hours / 720))
    # Simplified: for 30-day window, burn_rate_14.4 exhausts budget in ~50h
    fast_burn = 14.4
    medium_burn = 6.0
    slow_burn = 1.0

    return textwrap.dedent(f"""\
        # =======================================================================
        # Prometheus Alerting Rules — {service_name}
        # =======================================================================
        #
        # Generated by SKILL-001 Observability Module.
        #
        # SLO targets:
        #   Availability: {slo_availability * 100:.1f}% (error budget: {error_budget})
        #   Latency p99:  {slo_latency_p99_ms}ms
        #
        # Alert strategy: Multi-window multi-burn-rate (Google SRE Workbook Ch.5)
        #   Fast burn (14.4x):  PAGE  — exhausts 30-day budget in ~50 hours
        #   Medium burn (6x):   PAGE  — exhausts 30-day budget in ~5 days
        #   Slow burn (1x):     TICKET — on track to exhaust budget at window end
        #
        # Short windows prevent stale alerts from resolved incidents.
        # Rule of thumb: short_window = long_window / 12
        #
        # Installation:
        #   Copy to /etc/prometheus/rules/ and reload Prometheus:
        #   curl -X POST http://localhost:9090/-/reload
        #
        # =======================================================================

        groups:
          # -------------------------------------------------------------------
          # Recording rules: pre-compute error ratios and latency over windows
          # -------------------------------------------------------------------
          - name: {service_name}_slo_recording
            interval: 30s
            rules:
              # Error ratio: fraction of 5xx responses over each window
              - record: {service_name}:error_ratio:5m
                expr: |
                  sum(rate(http_requests_total{{service="{service_name}", status=~"5.."}}[5m]))
                  / sum(rate(http_requests_total{{service="{service_name}"}}[5m]))

              - record: {service_name}:error_ratio:30m
                expr: |
                  sum(rate(http_requests_total{{service="{service_name}", status=~"5.."}}[30m]))
                  / sum(rate(http_requests_total{{service="{service_name}"}}[30m]))

              - record: {service_name}:error_ratio:1h
                expr: |
                  sum(rate(http_requests_total{{service="{service_name}", status=~"5.."}}[1h]))
                  / sum(rate(http_requests_total{{service="{service_name}"}}[1h]))

              - record: {service_name}:error_ratio:6h
                expr: |
                  sum(rate(http_requests_total{{service="{service_name}", status=~"5.."}}[6h]))
                  / sum(rate(http_requests_total{{service="{service_name}"}}[6h]))

              # Burn rate: error_ratio / error_budget
              # burn_rate = 1.0 means budget consumed exactly at window end
              # burn_rate > 1.0 means budget will be exhausted early
              - record: {service_name}:burn_rate:1h
                expr: |
                  {service_name}:error_ratio:1h / {error_budget}

              - record: {service_name}:burn_rate:6h
                expr: |
                  {service_name}:error_ratio:6h / {error_budget}

              # Latency p99 over 5-minute window
              - record: {service_name}:latency_p99:5m
                expr: |
                  histogram_quantile(0.99,
                    sum(rate(http_request_duration_seconds_bucket{{service="{service_name}"}}[5m])) by (le)
                  )

              # Request rate (for traffic panel)
              - record: {service_name}:request_rate:5m
                expr: |
                  sum(rate(http_requests_total{{service="{service_name}"}}[5m]))

              # Error budget remaining (fraction of budget not yet consumed)
              - record: {service_name}:error_budget_remaining:30d
                expr: |
                  1 - (
                    sum(increase(http_requests_total{{service="{service_name}", status=~"5.."}}[30d]))
                    / sum(increase(http_requests_total{{service="{service_name}"}}[30d]))
                  ) / {error_budget}

          # -------------------------------------------------------------------
          # Alert rules: multi-window multi-burn-rate
          # -------------------------------------------------------------------
          - name: {service_name}_slo_alerts
            rules:
              # ---------------------------------------------------------------
              # FAST BURN — PAGE (critical)
              # 14.4x burn rate = exhausts 30-day budget in ~50 hours
              # Long window: 1h, Short window: 5m (1h / 12)
              # ---------------------------------------------------------------
              - alert: {service_name}_SLO_FastBurn
                expr: |
                  {service_name}:error_ratio:1h / {error_budget} > {fast_burn}
                  and
                  {service_name}:error_ratio:5m / {error_budget} > {fast_burn}
                for: 2m
                labels:
                  service: {service_name}
                  severity: critical
                  slo: availability
                  alert_type: page
                annotations:
                  summary: "CRITICAL: {{{{ $labels.service }}}} burning error budget at {fast_burn}x rate"
                  description: |
                    Error burn rate is {fast_burn}x the budget.
                    At this rate, the 30-day error budget will be exhausted in ~50 hours.
                    Current 1h error ratio: {{{{ $value | humanizePercentage }}}}
                    Error budget: {error_budget} ({slo_availability * 100:.1f}% SLO)
                  runbook: "https://wiki.example.com/runbooks/{service_name}/slo-fast-burn"

              # ---------------------------------------------------------------
              # MEDIUM BURN — PAGE (warning)
              # 6x burn rate = exhausts 30-day budget in ~5 days
              # Long window: 6h, Short window: 30m (6h / 12)
              # ---------------------------------------------------------------
              - alert: {service_name}_SLO_MediumBurn
                expr: |
                  {service_name}:error_ratio:6h / {error_budget} > {medium_burn}
                  and
                  {service_name}:error_ratio:30m / {error_budget} > {medium_burn}
                for: 5m
                labels:
                  service: {service_name}
                  severity: warning
                  slo: availability
                  alert_type: page
                annotations:
                  summary: "WARNING: {{{{ $labels.service }}}} elevated error burn rate ({medium_burn}x)"
                  description: |
                    Error burn rate is {medium_burn}x the budget over 6 hours.
                    At this rate, the 30-day error budget will be exhausted in ~5 days.
                    Current 6h error ratio: {{{{ $value | humanizePercentage }}}}
                  runbook: "https://wiki.example.com/runbooks/{service_name}/slo-medium-burn"

              # ---------------------------------------------------------------
              # SLOW BURN — TICKET (info)
              # 1x burn rate = on track to exhaust budget at window end
              # Long window: 6h, Short window: 1h
              # ---------------------------------------------------------------
              - alert: {service_name}_SLO_SlowBurn
                expr: |
                  {service_name}:error_ratio:6h / {error_budget} > {slow_burn}
                  and
                  {service_name}:error_ratio:1h / {error_budget} > {slow_burn}
                for: 30m
                labels:
                  service: {service_name}
                  severity: info
                  slo: availability
                  alert_type: ticket
                annotations:
                  summary: "INFO: {{{{ $labels.service }}}} error rate above SLO budget"
                  description: |
                    Sustained error rate above SLO budget.
                    If this continues, the 30-day error budget will be exhausted.
                    Current 6h error ratio: {{{{ $value | humanizePercentage }}}}
                  runbook: "https://wiki.example.com/runbooks/{service_name}/slo-slow-burn"

              # ---------------------------------------------------------------
              # LATENCY SLO — TICKET
              # p99 latency exceeds target for sustained period
              # ---------------------------------------------------------------
              - alert: {service_name}_SLO_LatencyHigh
                expr: |
                  {service_name}:latency_p99:5m > {latency_threshold_s}
                for: 10m
                labels:
                  service: {service_name}
                  severity: warning
                  slo: latency
                  alert_type: ticket
                annotations:
                  summary: "WARNING: {{{{ $labels.service }}}} p99 latency exceeds {slo_latency_p99_ms}ms"
                  description: |
                    The 99th percentile request latency has exceeded {slo_latency_p99_ms}ms
                    for more than 10 minutes.
                    Current p99: {{{{ $value | humanizeDuration }}}}
                  runbook: "https://wiki.example.com/runbooks/{service_name}/latency-high"

              # ---------------------------------------------------------------
              # ERROR BUDGET EXHAUSTED — PAGE
              # Less than 10% of error budget remaining
              # ---------------------------------------------------------------
              - alert: {service_name}_ErrorBudgetLow
                expr: |
                  {service_name}:error_budget_remaining:30d < 0.1
                for: 5m
                labels:
                  service: {service_name}
                  severity: critical
                  slo: availability
                  alert_type: page
                annotations:
                  summary: "CRITICAL: {{{{ $labels.service }}}} error budget nearly exhausted"
                  description: |
                    Less than 10% of the 30-day error budget remains.
                    Remaining budget: {{{{ $value | humanizePercentage }}}}
                    Stop feature work and focus on reliability.
                  runbook: "https://wiki.example.com/runbooks/{service_name}/error-budget-exhausted"
    """)


# ---------------------------------------------------------------------------
# Grafana Dashboard Generator
# ---------------------------------------------------------------------------


def _generate_grafana_dashboard(
    service_name: str,
    slo_availability: float,
    slo_latency_p99_ms: int,
) -> dict:
    """Generate a Grafana dashboard JSON model with essential API panels.

    Panels follow the Four Golden Signals:
    1. Latency (p50, p95, p99 time series + heatmap)
    2. Traffic (request rate by endpoint)
    3. Errors (error rate % + error budget remaining)
    4. Saturation (active requests gauge)
    """
    error_budget = round(1.0 - slo_availability, 6)

    dashboard = {
        "annotations": {"list": []},
        "description": f"Production monitoring for {service_name} — Four Golden Signals + SLO",
        "editable": True,
        "fiscalYearStartMonth": 0,
        "graphTooltip": 1,  # Shared crosshair
        "id": None,
        "links": [],
        "panels": [],
        "refresh": "30s",
        "schemaVersion": 39,
        "tags": ["api", "slo", "red", service_name],
        "templating": {
            "list": [
                {
                    "current": {"selected": False, "text": "default", "value": "default"},
                    "hide": 0,
                    "includeAll": False,
                    "multi": False,
                    "name": "datasource",
                    "options": [],
                    "query": "prometheus",
                    "refresh": 1,
                    "type": "datasource",
                },
            ],
        },
        "time": {"from": "now-6h", "to": "now"},
        "timepicker": {},
        "timezone": "utc",
        "title": f"{service_name} — API Observability",
        "uid": f"{service_name.replace('-', '_')}_api_obs",
        "version": 1,
    }

    y_pos = 0
    panel_id = 1

    # --- Row: Traffic & Errors ---
    dashboard["panels"].append({
        "collapsed": False,
        "gridPos": {"h": 1, "w": 24, "x": 0, "y": y_pos},
        "id": panel_id,
        "title": "Traffic & Errors",
        "type": "row",
    })
    panel_id += 1
    y_pos += 1

    # Panel: Request Rate (by endpoint)
    dashboard["panels"].append({
        "datasource": {"type": "prometheus", "uid": "${datasource}"},
        "fieldConfig": {
            "defaults": {
                "color": {"mode": "palette-classic"},
                "custom": {
                    "axisBorderShow": False,
                    "drawStyle": "line",
                    "fillOpacity": 10,
                    "lineWidth": 2,
                    "pointSize": 5,
                    "showPoints": "never",
                    "stacking": {"mode": "none"},
                },
                "unit": "reqps",
            },
            "overrides": [],
        },
        "gridPos": {"h": 8, "w": 12, "x": 0, "y": y_pos},
        "id": panel_id,
        "options": {"legend": {"calcs": ["mean", "max"], "displayMode": "table", "placement": "bottom"}},
        "targets": [
            {
                "expr": f'sum(rate(http_requests_total{{service="{service_name}"}}[5m])) by (endpoint)',
                "legendFormat": "{{endpoint}}",
                "refId": "A",
            },
        ],
        "title": "Request Rate (by endpoint)",
        "type": "timeseries",
    })
    panel_id += 1

    # Panel: Error Rate %
    dashboard["panels"].append({
        "datasource": {"type": "prometheus", "uid": "${datasource}"},
        "fieldConfig": {
            "defaults": {
                "color": {"fixedColor": "red", "mode": "fixed"},
                "custom": {
                    "drawStyle": "line",
                    "fillOpacity": 20,
                    "lineWidth": 2,
                    "showPoints": "never",
                    "thresholdsStyle": {"mode": "line"},
                },
                "thresholds": {
                    "mode": "absolute",
                    "steps": [
                        {"color": "green", "value": None},
                        {"color": "yellow", "value": error_budget * 100 * 0.5},
                        {"color": "red", "value": error_budget * 100},
                    ],
                },
                "unit": "percent",
                "max": max(error_budget * 100 * 10, 1.0),
            },
            "overrides": [],
        },
        "gridPos": {"h": 8, "w": 12, "x": 12, "y": y_pos},
        "id": panel_id,
        "targets": [
            {
                "expr": (
                    f'sum(rate(http_requests_total{{service="{service_name}", status=~"5.."}}[5m]))'
                    f' / sum(rate(http_requests_total{{service="{service_name}"}}[5m])) * 100'
                ),
                "legendFormat": "Error Rate %",
                "refId": "A",
            },
        ],
        "title": f"Error Rate % (SLO: <{error_budget * 100:.2f}%)",
        "type": "timeseries",
    })
    panel_id += 1
    y_pos += 8

    # --- Row: Latency ---
    dashboard["panels"].append({
        "collapsed": False,
        "gridPos": {"h": 1, "w": 24, "x": 0, "y": y_pos},
        "id": panel_id,
        "title": "Latency",
        "type": "row",
    })
    panel_id += 1
    y_pos += 1

    # Panel: Latency Percentiles (p50, p95, p99)
    dashboard["panels"].append({
        "datasource": {"type": "prometheus", "uid": "${datasource}"},
        "fieldConfig": {
            "defaults": {
                "color": {"mode": "palette-classic"},
                "custom": {
                    "drawStyle": "line",
                    "fillOpacity": 0,
                    "lineWidth": 2,
                    "showPoints": "never",
                    "thresholdsStyle": {"mode": "line"},
                },
                "thresholds": {
                    "mode": "absolute",
                    "steps": [
                        {"color": "green", "value": None},
                        {"color": "red", "value": slo_latency_p99_ms / 1000},
                    ],
                },
                "unit": "s",
            },
            "overrides": [],
        },
        "gridPos": {"h": 8, "w": 12, "x": 0, "y": y_pos},
        "id": panel_id,
        "targets": [
            {
                "expr": (
                    f"histogram_quantile(0.50, "
                    f'sum(rate(http_request_duration_seconds_bucket{{service="{service_name}"}}[5m])) by (le))'
                ),
                "legendFormat": "p50",
                "refId": "A",
            },
            {
                "expr": (
                    f"histogram_quantile(0.95, "
                    f'sum(rate(http_request_duration_seconds_bucket{{service="{service_name}"}}[5m])) by (le))'
                ),
                "legendFormat": "p95",
                "refId": "B",
            },
            {
                "expr": (
                    f"histogram_quantile(0.99, "
                    f'sum(rate(http_request_duration_seconds_bucket{{service="{service_name}"}}[5m])) by (le))'
                ),
                "legendFormat": "p99",
                "refId": "C",
            },
        ],
        "title": f"Latency Percentiles (SLO: p99 < {slo_latency_p99_ms}ms)",
        "type": "timeseries",
    })
    panel_id += 1

    # Panel: Latency Heatmap
    dashboard["panels"].append({
        "datasource": {"type": "prometheus", "uid": "${datasource}"},
        "fieldConfig": {
            "defaults": {
                "color": {"mode": "scheme", "schemeVersion": 1},
                "custom": {"hideFrom": {"legend": False, "tooltip": False, "viz": False}},
            },
            "overrides": [],
        },
        "gridPos": {"h": 8, "w": 12, "x": 12, "y": y_pos},
        "id": panel_id,
        "options": {
            "calculate": False,
            "cellGap": 1,
            "color": {"mode": "scheme", "scheme": "Oranges", "steps": 64},
            "yAxis": {"unit": "s"},
        },
        "targets": [
            {
                "expr": (
                    f'sum(increase(http_request_duration_seconds_bucket{{service="{service_name}"}}[5m])) by (le)'
                ),
                "format": "heatmap",
                "legendFormat": "{{le}}",
                "refId": "A",
            },
        ],
        "title": "Latency Distribution (Heatmap)",
        "type": "heatmap",
    })
    panel_id += 1
    y_pos += 8

    # --- Row: Saturation & SLO ---
    dashboard["panels"].append({
        "collapsed": False,
        "gridPos": {"h": 1, "w": 24, "x": 0, "y": y_pos},
        "id": panel_id,
        "title": "Saturation & SLO",
        "type": "row",
    })
    panel_id += 1
    y_pos += 1

    # Panel: Active Requests (saturation)
    dashboard["panels"].append({
        "datasource": {"type": "prometheus", "uid": "${datasource}"},
        "fieldConfig": {
            "defaults": {
                "color": {"fixedColor": "blue", "mode": "fixed"},
                "custom": {
                    "drawStyle": "line",
                    "fillOpacity": 30,
                    "lineWidth": 2,
                    "showPoints": "never",
                },
                "unit": "short",
            },
            "overrides": [],
        },
        "gridPos": {"h": 8, "w": 8, "x": 0, "y": y_pos},
        "id": panel_id,
        "targets": [
            {
                "expr": f'sum(http_requests_in_progress{{service="{service_name}"}})',
                "legendFormat": "Active Requests",
                "refId": "A",
            },
        ],
        "title": "Active Requests (Saturation)",
        "type": "timeseries",
    })
    panel_id += 1

    # Panel: Error Budget Remaining (gauge)
    dashboard["panels"].append({
        "datasource": {"type": "prometheus", "uid": "${datasource}"},
        "fieldConfig": {
            "defaults": {
                "color": {"mode": "thresholds"},
                "thresholds": {
                    "mode": "absolute",
                    "steps": [
                        {"color": "red", "value": None},
                        {"color": "yellow", "value": 0.2},
                        {"color": "green", "value": 0.5},
                    ],
                },
                "unit": "percentunit",
                "min": 0,
                "max": 1,
            },
            "overrides": [],
        },
        "gridPos": {"h": 8, "w": 8, "x": 8, "y": y_pos},
        "id": panel_id,
        "options": {
            "reduceOptions": {"calcs": ["lastNotNull"], "fields": "", "values": False},
            "showThresholdLabels": False,
            "showThresholdMarkers": True,
        },
        "targets": [
            {
                "expr": (
                    f"1 - ("
                    f'sum(increase(http_requests_total{{service="{service_name}", status=~"5.."}}[30d]))'
                    f' / sum(increase(http_requests_total{{service="{service_name}"}}[30d]))'
                    f") / {error_budget}"
                ),
                "legendFormat": "Budget Remaining",
                "refId": "A",
            },
        ],
        "title": f"Error Budget Remaining ({slo_availability * 100:.1f}% SLO)",
        "type": "gauge",
    })
    panel_id += 1

    # Panel: Burn Rate (1h and 6h)
    dashboard["panels"].append({
        "datasource": {"type": "prometheus", "uid": "${datasource}"},
        "fieldConfig": {
            "defaults": {
                "color": {"mode": "palette-classic"},
                "custom": {
                    "drawStyle": "line",
                    "fillOpacity": 0,
                    "lineWidth": 2,
                    "showPoints": "never",
                    "thresholdsStyle": {"mode": "line+area"},
                },
                "thresholds": {
                    "mode": "absolute",
                    "steps": [
                        {"color": "transparent", "value": None},
                        {"color": "red", "value": 14.4},
                    ],
                },
                "unit": "short",
            },
            "overrides": [],
        },
        "gridPos": {"h": 8, "w": 8, "x": 16, "y": y_pos},
        "id": panel_id,
        "targets": [
            {
                "expr": f'{service_name}:burn_rate:1h',
                "legendFormat": "Burn Rate (1h)",
                "refId": "A",
            },
            {
                "expr": f'{service_name}:burn_rate:6h',
                "legendFormat": "Burn Rate (6h)",
                "refId": "B",
            },
        ],
        "title": "Error Budget Burn Rate",
        "type": "timeseries",
    })

    return dashboard


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------


def generate_alerting_rules(
    service_name: str,
    slo_availability: float = 0.999,
    slo_latency_p99_ms: int = 500,
    output_dir: str | None = None,
) -> dict[str, str]:
    """
    Generate Prometheus alerting rules and a Grafana dashboard for an API service.

    Creates two files:
    1. ``prometheus_rules.yaml`` — Recording rules for error ratios, burn rates,
       and latency percentiles, plus multi-window multi-burn-rate alert rules
       following the Google SRE Workbook pattern (Chapter 5).
    2. ``grafana_dashboard.json`` — Importable Grafana dashboard with the Four
       Golden Signals (Latency, Traffic, Errors, Saturation) plus SLO error
       budget panels.

    Alert severity mapping:
        - **critical** (page): Fast burn (14.4x), error budget < 10%
        - **warning** (page): Medium burn (6x), p99 latency exceeded
        - **info** (ticket): Slow burn (1x), budget consumption on track to fail

    Args:
        service_name: Service name used in metric labels and alert names.
            Must match the ``service`` label on your Prometheus metrics.
        slo_availability: Availability SLO as a fraction (default 0.999 = 99.9%).
            Error budget = 1 - slo_availability.
        slo_latency_p99_ms: Maximum acceptable p99 latency in milliseconds
            (default 500ms).
        output_dir: Directory to write files. If None, returns content without
            writing to disk.

    Returns:
        Dict mapping filename to file content:
        ``{"prometheus_rules.yaml": "...", "grafana_dashboard.json": "..."}``

    Example::

        files = generate_alerting_rules(
            service_name="order-api",
            slo_availability=0.999,
            slo_latency_p99_ms=500,
            output_dir="/tmp/monitoring",
        )
        print(files.keys())
        # dict_keys(['prometheus_rules.yaml', 'grafana_dashboard.json'])
    """
    if not 0 < slo_availability < 1:
        raise ValueError(
            f"slo_availability must be between 0 and 1 (exclusive), "
            f"got {slo_availability}"
        )

    if slo_latency_p99_ms <= 0:
        raise ValueError(
            f"slo_latency_p99_ms must be positive, got {slo_latency_p99_ms}"
        )

    # Generate content
    prometheus_yaml = _generate_prometheus_rules(
        service_name, slo_availability, slo_latency_p99_ms,
    )

    grafana_model = _generate_grafana_dashboard(
        service_name, slo_availability, slo_latency_p99_ms,
    )
    grafana_json = json.dumps(grafana_model, indent=2, ensure_ascii=False)

    result = {
        "prometheus_rules.yaml": prometheus_yaml,
        "grafana_dashboard.json": grafana_json,
    }

    # Write to disk if output_dir is specified
    if output_dir is not None:
        out_path = Path(output_dir)
        out_path.mkdir(parents=True, exist_ok=True)

        for filename, content in result.items():
            filepath = out_path / filename
            filepath.write_text(content, encoding="utf-8")

    return result
