from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class TemporalClientFactoryProtocol(Protocol):
    """Auto-inferred Protocol surface for `TemporalClientFactory`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    async def connect(self) -> Any: ...
