from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class InputSanitizerProtocol(Protocol):
    """Auto-inferred Protocol surface for `InputSanitizer`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    def sanitize_html(self, value: str) -> str: ...
    def strip_tags(self, value: str) -> str: ...
    def escape_sql_chars(self, value: str) -> str: ...
