from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class QueryBusProtocol(Protocol):
    """Auto-inferred Protocol surface for `QueryBus`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    def register(self, query_name: str, handler: Handler) -> None: ...
    async def query(self, q: object, **kwargs) -> Any: ...
