from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class IdempotencyStoreProtocol(Protocol):
    """Auto-inferred Protocol surface for `IdempotencyStore`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    def get(self, key: str) -> _Any | None: ...
    def put(self, key: str, result: _Any) -> None: ...
    def seen(self, key: str) -> bool: ...
