from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class EmailProviderProtocol(Protocol):
    """Auto-inferred Protocol surface for `EmailProvider`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    async def send(self, message: EmailMessage) -> EmailResult: ...
