from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class OnboardingOrchestratorProtocol(Protocol):
    """Auto-inferred Protocol surface for `OnboardingOrchestrator`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_staging/`.
    """

    def add_step(self, step: OnboardingStep) -> None: ...
    def start(self, tenant_name: str, admin_email: str) -> OnboardingProgress: ...
