from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class ChaosEngineProtocol(Protocol):
    """Auto-inferred Protocol surface for `ChaosEngine`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    def enable(self) -> None: ...
    def disable(self) -> None: ...
    def is_enabled(self) -> bool: ...
    def status(self) -> dict: ...
