"""Protocol for LifecycleHook — generated from LifecycleHook.py."""

from __future__ import annotations

from typing import Any, Optional, Protocol, runtime_checkable

@runtime_checkable
class LifecycleHookProtocol(Protocol):
    """LifecycleHook primitive — named callback fired at a defined application phase."""

    ...

@runtime_checkable
class LifecyclePhaseProtocol(Protocol):
    """Protocol surface for `LifecyclePhase`."""

    ...

@runtime_checkable
class LifecycleRegistryProtocol(Protocol):
    """Reference registry for lifecycle hooks."""

    def register(self, hook: LifecycleHook) -> None: ...
    async def run_starting(self) -> None: ...
    async def run_ready(self) -> None: ...
    async def run_stopping(self) -> None: ...
    async def run_stopped(self) -> None: ...
    def ready_fired(self) -> bool: ...
    def starting_failed(self) -> bool: ...
    def stopped(self) -> bool: ...
    def hooks_for(self, phase: LifecyclePhase) -> tuple[LifecycleHook, ...]: ...
