from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class RequestReplayerProtocol(Protocol):
    """Auto-inferred Protocol surface for `RequestReplayer`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_staging/`.
    """

    async def replay(self, record: dict) -> dict: ...
