from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class ModelRegistryProtocol(Protocol):
    """Auto-inferred Protocol surface for `ModelRegistry`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    def register(self, name: str, loader_fn: Callable[[], Any], version: str = 'latest') -> None: ...
    def get(self, name: str, version: str = 'latest') -> Any: ...
    def list_models(self) -> list[dict[str, Any]]: ...
    def update_stats(self, name: str, version: str, latency_ms: float, *, error: bool = False) -> None: ...
