from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class CedarEngineProtocol(Protocol):
    """Auto-inferred Protocol surface for `CedarEngine`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_staging/`.
    """

    def load_policies(self, directory: str | Path | None = None) -> None: ...
    def is_authorized(self, principal: str, action: str, resource: str, context: dict | None = None) -> bool: ...
