from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class RequestMetricsProtocol(Protocol):
    """Auto-inferred Protocol surface for `RequestMetrics`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_staging/`.
    """

    def record_request(self, method: str, path: str, status: int, duration: float) -> None: ...
