from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class VersionInfoProtocol(Protocol):
    """Auto-inferred Protocol surface for `VersionInfo`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_staging/`.
    """

    @property
    def sunset_header(self) -> str | None: ...
