"""Generator for email utilities — SMTP sending + HTML templates."""

from __future__ import annotations

MCP_TOOL = {
    'name': 'fastapi_deployment_generate_email',
    'description': 'Generate email utilities: SMTP sender, password reset email, welcome email with HTML templates.',
    'tags': ['generator', 'infra'],
    'entry': 'generate_email_utils',
}

import textwrap
from pathlib import Path


def generate_email_utils(output_dir: str) -> dict:
    """Generate ``utils/email.py`` with SMTP email sending and HTML templates.

    Provides:
    - ``send_email()`` — generic HTML email via SMTP (no-op if SMTP not configured).
    - ``send_password_reset_email()`` — password reset with token link.
    - ``send_new_account_email()`` — welcome email for new users.
    - Inline HTML templates (no MJML dependency).

    The email functions read SMTP config from ``app.core.config.settings``
    (generated by ``generate_config(with_smtp=True)``).  When SMTP is not
    configured (``settings.emails_enabled`` is ``False``), all sends are
    silently skipped with a warning log.

    Args:
        output_dir: Project root.  File is written to ``utils/email.py``.

    Returns:
        Dict with ``files_created`` and ``notes``.
    """
    out = Path(output_dir) / "utils"
    out.mkdir(parents=True, exist_ok=True)

    # --- utils/__init__.py ---
    init_path = out / "__init__.py"
    if not init_path.exists():
        init_path.write_text("")

    # --- utils/email.py ---
    content = textwrap.dedent('''\
        """Email utilities -- send transactional emails via SMTP.

        All functions are safe to call even when SMTP is not configured:
        they log a warning and return immediately (no-op).  This avoids
        crashes in development/test environments without an SMTP server.
        """

        from __future__ import annotations

        import asyncio
        import logging
        import smtplib
        import ssl
        from email.mime.multipart import MIMEMultipart
        from email.mime.text import MIMEText

        from app.core.config import settings

        logger = logging.getLogger(__name__)


        def _send_email_sync(to: str, subject: str, html_content: str) -> None:
            """Blocking SMTP send — only call via ``send_email`` wrapper."""
            msg = MIMEMultipart("alternative")
            msg["From"] = (
                f"{settings.EMAILS_FROM_NAME} <{settings.EMAILS_FROM_EMAIL}>"
                if settings.EMAILS_FROM_NAME
                else settings.EMAILS_FROM_EMAIL
            )
            msg["To"] = to
            msg["Subject"] = subject
            msg.attach(MIMEText(html_content, "html"))

            try:
                if settings.SMTP_SSL:
                    context = ssl.create_default_context()
                    with smtplib.SMTP_SSL(
                        settings.SMTP_HOST, settings.SMTP_PORT, context=context
                    ) as server:
                        if settings.SMTP_USER and settings.SMTP_PASSWORD:
                            server.login(settings.SMTP_USER, settings.SMTP_PASSWORD)
                        server.sendmail(settings.EMAILS_FROM_EMAIL, to, msg.as_string())
                else:
                    with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT) as server:
                        if settings.SMTP_TLS:
                            context = ssl.create_default_context()
                            server.starttls(context=context)
                        if settings.SMTP_USER and settings.SMTP_PASSWORD:
                            server.login(settings.SMTP_USER, settings.SMTP_PASSWORD)
                        server.sendmail(settings.EMAILS_FROM_EMAIL, to, msg.as_string())

                logger.info("Email sent to %s: %s", to, subject)
            except Exception:
                logger.exception("Failed to send email to %s", to)
                raise


        async def send_email(to: str, subject: str, html_content: str) -> None:
            """Send an HTML email via SMTP (non-blocking).

            The underlying ``smtplib`` calls are synchronous — they run
            inside ``asyncio.to_thread`` so the FastAPI event loop stays
            free while waiting on the SMTP server.

            No-op if SMTP is not configured
            (``settings.emails_enabled`` is False).

            Args:
                to: Recipient email address.
                subject: Email subject line.
                html_content: HTML body content.
            """
            if not settings.emails_enabled:
                logger.warning("SMTP not configured -- email to %s not sent", to)
                return
            await asyncio.to_thread(_send_email_sync, to, subject, html_content)


        async def send_password_reset_email(to: str, token: str) -> None:
            """Send a password-reset email with a reset link.

            Args:
                to: Recipient email address.
                token: Password reset JWT token.
            """
            reset_url = f"{settings.FRONTEND_URL}/reset-password?token={token}"
            html = RESET_PASSWORD_TEMPLATE.format(
                project_name=settings.PROJECT_NAME,
                reset_url=reset_url,
            )
            await send_email(
                to=to,
                subject=f"{settings.PROJECT_NAME} - Password Reset Request",
                html_content=html,
            )


        async def send_new_account_email(to: str, full_name: str) -> None:
            """Send a welcome email to a newly registered user.

            Args:
                to: Recipient email address.
                full_name: User's full name for personalization.
            """
            html = NEW_ACCOUNT_TEMPLATE.format(
                project_name=settings.PROJECT_NAME,
                full_name=full_name,
            )
            await send_email(
                to=to,
                subject=f"Welcome to {settings.PROJECT_NAME}",
                html_content=html,
            )


        # -------------------------------------------------------------------
        # HTML Templates (inline -- no external dependencies)
        # -------------------------------------------------------------------

        RESET_PASSWORD_TEMPLATE = """<!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <style>
                body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }}
                .header {{ background: #1a1a2e; color: #fff; padding: 20px; border-radius: 8px 8px 0 0; text-align: center; }}
                .content {{ background: #f8f9fa; padding: 30px; border: 1px solid #e9ecef; }}
                .button {{ display: inline-block; background: #0066cc; color: #fff; padding: 12px 24px; text-decoration: none; border-radius: 6px; margin: 20px 0; }}
                .footer {{ text-align: center; padding: 20px; font-size: 12px; color: #999; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>{project_name}</h1>
            </div>
            <div class="content">
                <h2>Password Reset Request</h2>
                <p>You have requested to reset your password. Click the button below to proceed:</p>
                <p style="text-align: center;">
                    <a href="{reset_url}" class="button">Reset Password</a>
                </p>
                <p>If you did not request a password reset, please ignore this email. The link will expire in 30 minutes.</p>
                <p style="font-size: 12px; color: #666;">
                    If the button does not work, copy and paste this URL into your browser:<br>
                    <code>{reset_url}</code>
                </p>
            </div>
            <div class="footer">
                <p>This is an automated message from {project_name}. Please do not reply.</p>
            </div>
        </body>
        </html>"""

        NEW_ACCOUNT_TEMPLATE = """<!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <style>
                body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }}
                .header {{ background: #1a1a2e; color: #fff; padding: 20px; border-radius: 8px 8px 0 0; text-align: center; }}
                .content {{ background: #f8f9fa; padding: 30px; border: 1px solid #e9ecef; }}
                .footer {{ text-align: center; padding: 20px; font-size: 12px; color: #999; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>{project_name}</h1>
            </div>
            <div class="content">
                <h2>Welcome, {full_name}!</h2>
                <p>Your account has been successfully created.</p>
                <p>You can now log in and start using {project_name}.</p>
            </div>
            <div class="footer">
                <p>This is an automated message from {project_name}. Please do not reply.</p>
            </div>
        </body>
        </html>"""
    ''')

    email_path = out / "email.py"
    email_path.write_text(content)

    files = [str(init_path), str(email_path)]
    notes = [
        "Generated utils/email.py with SMTP email sending (TLS + SSL support).",
        "Includes send_password_reset_email() and send_new_account_email() with inline HTML templates.",
        "No-op when SMTP is not configured (settings.emails_enabled = False).",
    ]

    return {"files_created": files, "notes": notes}
