from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class HealthRegistryProtocol(Protocol):
    """Auto-inferred Protocol surface for `HealthRegistry`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_staging/`.
    """

    def register_check(self, name: str, check_fn: Callable[[], Coroutine[Any, Any, DependencyCheck]], *, critical: bool = False) -> None: ...
    async def run_all(self) -> HealthReport: ...
    async def run_readiness(self) -> HealthReport: ...
    async def run_liveness(self) -> HealthReport: ...
