from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class MeterEventBufferProtocol(Protocol):
    """Auto-inferred Protocol surface for `MeterEventBuffer`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    def add(self, event: MeterEvent) -> None: ...
    def drain(self, batch_size: int) -> list[MeterEvent]: ...
    @property
    def size(self) -> int: ...
