from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class ImportProcessorProtocol(Protocol):
    """Auto-inferred Protocol surface for `ImportProcessor`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    def parse_csv(self, content: bytes) -> list[dict[str, Any]]: ...
    def parse_excel(self, content: bytes) -> list[dict[str, Any]]: ...
    def validate_rows(self, rows: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]: ...
    async def process_batch(self, session: AsyncSession, rows: list[dict[str, Any]]) -> int: ...
