from __future__ import annotations

from typing import Protocol, runtime_checkable
from typing import Any

@runtime_checkable
class MigrationCIRunnerProtocol(Protocol):
    """Auto-inferred Protocol surface for `MigrationCIRunner`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_staging/`.
    """

    def check_pending(self) -> dict[str, Any]: ...
    def verify_rollback(self) -> dict[str, Any]: ...
    def schema_diff(self) -> dict[str, Any]: ...
