"""Generator for docker-compose.yml."""

from __future__ import annotations

from pathlib import Path


def generate_docker_compose(
    output_dir: str,
    services: list[str] | None = None,
    postgres_version: str = "16",
    redis: bool = False,
    app_port: int = 8000,
) -> dict:
    """Generate a production-grade docker-compose.yml.

    Args:
        output_dir: Directory where docker-compose.yml will be written.
        services: Explicit list of services to include. Defaults to
            ``["app", "postgres"]`` (plus ``redis`` if *redis* is True).
        postgres_version: PostgreSQL major version for the official image.
        redis: Include a Redis service with append-only persistence.
        app_port: Host port mapped to the application container.

    Returns:
        Dict with files_created and notes.
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    if services is None:
        services = ["app", "postgres"]
        if redis and "redis" not in services:
            services.append("redis")
    elif redis and "redis" not in services:
        services.append("redis")

    include_postgres = "postgres" in services
    include_redis = redis or "redis" in services

    # --- Build depends_on block for app service ---
    depends_lines = ""
    if include_postgres or include_redis:
        depends_parts = []
        if include_postgres:
            depends_parts.append(
                "      postgres:\n"
                "        condition: service_healthy"
            )
        if include_redis:
            depends_parts.append(
                "      redis:\n"
                "        condition: service_healthy"
            )
        depends_lines = "    depends_on:\n" + "\n".join(depends_parts) + "\n"

    # --- App service ---
    app_block = (
        f"  app:\n"
        f"    build:\n"
        f"      context: .\n"
        f"      dockerfile: Dockerfile\n"
        f"    ports:\n"
        f'      - "{app_port}:8000"\n'
        f"    env_file:\n"
        f"      - .env\n"
        f"{depends_lines}"
        f"    restart: unless-stopped\n"
        f"    networks:\n"
        f"      - backend\n"
    )

    # --- Postgres service ---
    postgres_block = ""
    if include_postgres:
        postgres_block = (
            f"\n"
            f"  postgres:\n"
            f"    image: postgres:{postgres_version}-alpine\n"
            f"    environment:\n"
            f"      POSTGRES_USER: ${{POSTGRES_USER:-postgres}}\n"
            f"      POSTGRES_PASSWORD: ${{POSTGRES_PASSWORD:?Set POSTGRES_PASSWORD in .env}}\n"
            f"      POSTGRES_DB: ${{POSTGRES_DB:-app}}\n"
            f"    volumes:\n"
            f"      - postgres_data:/var/lib/postgresql/data\n"
            f"    ports:\n"
            f'      - "5432:5432"\n'
            f"    healthcheck:\n"
            f'      test: ["CMD-SHELL", "pg_isready -U ${{POSTGRES_USER:-postgres}} -d ${{POSTGRES_DB:-app}}"]\n'
            f"      interval: 5s\n"
            f"      timeout: 5s\n"
            f"      retries: 5\n"
            f"    restart: unless-stopped\n"
            f"    networks:\n"
            f"      - backend\n"
        )

    # --- Redis service ---
    redis_block = ""
    if include_redis:
        redis_block = (
            "\n"
            "  redis:\n"
            "    image: redis:7-alpine\n"
            "    command: redis-server --appendonly yes\n"
            "    volumes:\n"
            "      - redis_data:/data\n"
            "    ports:\n"
            '      - "6379:6379"\n'
            "    healthcheck:\n"
            '      test: ["CMD", "redis-cli", "ping"]\n'
            "      interval: 5s\n"
            "      timeout: 5s\n"
            "      retries: 5\n"
            "    restart: unless-stopped\n"
            "    networks:\n"
            "      - backend\n"
        )

    # --- Volumes ---
    volume_entries = []
    if include_postgres:
        volume_entries.append("  postgres_data:")
    if include_redis:
        volume_entries.append("  redis_data:")

    volumes_section = ""
    if volume_entries:
        volumes_section = "\nvolumes:\n" + "\n".join(volume_entries) + "\n"

    # --- Networks ---
    networks_section = (
        "\n"
        "networks:\n"
        "  backend:\n"
        "    driver: bridge\n"
    )

    # --- Assemble ---
    content = (
        "# docker-compose.yml -- generated by SKILL-001-fastapi-production\n"
        "# Usage:\n"
        "#   cp .env.example .env   # fill in secrets\n"
        "#   docker compose up -d\n"
        "#   docker compose logs -f app\n"
        "\n"
        "services:\n"
    )
    content += app_block + postgres_block + redis_block
    content += volumes_section + networks_section

    file_path = out / "docker-compose.yml"
    file_path.write_text(content)

    svc_names = ["app"]
    if include_postgres:
        svc_names.append(f"postgres:{postgres_version}-alpine")
    if include_redis:
        svc_names.append("redis:7-alpine")

    notes = [
        f"Services: {', '.join(svc_names)}. App mapped to host port {app_port}.",
        "All services use healthchecks (5s interval, 5s timeout, 5 retries).",
        "Postgres password required via .env (POSTGRES_PASSWORD).",
    ]
    if include_redis:
        notes.append("Redis configured with append-only persistence.")

    return {"files_created": [str(file_path)], "notes": notes}
