"""Generator for GitHub Actions CI workflow."""

from __future__ import annotations

MCP_TOOL = {
    'name': 'fastapi_deployment_generate_ci',
    'description': 'Generate GitHub Actions CI: lint (ruff+mypy), test (pytest+postgres), build (Docker), scan (Trivy).',
    'tags': ['deployment', 'generator'],
    'entry': 'generate_github_actions',
}

import textwrap
from pathlib import Path


def generate_github_actions(
    output_dir: str,
    python_version: str = "3.12",
    postgres_version: str = "16",
) -> dict:
    """Generate a production-grade GitHub Actions CI pipeline.

    Creates ``.github/workflows/ci.yml`` with lint, test, build, and scan
    jobs.  The test job uses a Postgres service container for integration
    tests.

    Args:
        output_dir: Root directory; the file is written to
            ``<output_dir>/.github/workflows/ci.yml``.
        python_version: Python version for the runner matrix.
        postgres_version: PostgreSQL version for the service container.

    Returns:
        Dict with files_created and notes.
    """
    out = Path(output_dir) / ".github" / "workflows"
    out.mkdir(parents=True, exist_ok=True)

    content = textwrap.dedent(f"""\
        # CI Pipeline -- generated by SKILL-001-fastapi-production
        name: CI

        on:
          push:
            branches: [main]
          pull_request:
            branches: [main]

        env:
          PYTHON_VERSION: "{python_version}"
          REGISTRY: ghcr.io
          IMAGE_NAME: ${{{{ github.repository }}}}

        permissions:
          contents: read
          packages: write
          security-events: write

        jobs:
          # ------------------------------------------------------------------
          # Lint: ruff + mypy
          # ------------------------------------------------------------------
          lint:
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@v4

              - name: Set up Python
                uses: actions/setup-python@v5
                with:
                  python-version: ${{{{ env.PYTHON_VERSION }}}}
                  cache: pip

              - name: Install dependencies
                run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install ruff mypy

              - name: Ruff check
                run: ruff check app/ tests/

              - name: Ruff format check
                run: ruff format --check app/ tests/

              - name: Mypy
                run: mypy app/ --ignore-missing-imports

          # ------------------------------------------------------------------
          # Test: pytest + coverage with Postgres service
          # ------------------------------------------------------------------
          test:
            runs-on: ubuntu-latest
            needs: lint

            services:
              postgres:
                image: postgres:{postgres_version}-alpine
                env:
                  POSTGRES_USER: postgres
                  POSTGRES_PASSWORD: postgres
                  POSTGRES_DB: app_test
                ports:
                  - 5432:5432
                options: >-
                  --health-cmd "pg_isready -U postgres"
                  --health-interval 5s
                  --health-timeout 5s
                  --health-retries 5

            env:
              DATABASE_URL: "postgresql+asyncpg://postgres:postgres@localhost:5432/app_test"
              SECRET_KEY: "test-secret-key-not-for-production"
              ENVIRONMENT: "local"

            steps:
              - uses: actions/checkout@v4

              - name: Set up Python
                uses: actions/setup-python@v5
                with:
                  python-version: ${{{{ env.PYTHON_VERSION }}}}
                  cache: pip

              - name: Install dependencies
                run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install pytest pytest-cov pytest-asyncio httpx

              - name: Run tests with coverage
                run: |
                  pytest tests/ \\
                    -v \\
                    --tb=short \\
                    --cov=app \\
                    --cov-report=term-missing \\
                    --cov-report=xml:coverage.xml \\
                    --cov-fail-under=80

              - name: Upload coverage artifact
                uses: actions/upload-artifact@v4
                if: always()
                with:
                  name: coverage-report
                  path: coverage.xml

          # ------------------------------------------------------------------
          # Build: Docker image
          # ------------------------------------------------------------------
          build:
            runs-on: ubuntu-latest
            needs: test
            if: github.event_name == 'push' && github.ref == 'refs/heads/main'

            steps:
              - uses: actions/checkout@v4

              - name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

              - name: Log in to container registry
                uses: docker/login-action@v3
                with:
                  registry: ${{{{ env.REGISTRY }}}}
                  username: ${{{{ github.actor }}}}
                  password: ${{{{ secrets.GITHUB_TOKEN }}}}

              - name: Extract metadata
                id: meta
                uses: docker/metadata-action@v5
                with:
                  images: ${{{{ env.REGISTRY }}}}/${{{{ env.IMAGE_NAME }}}}
                  tags: |
                    type=sha,prefix=
                    type=raw,value=latest

              - name: Build and push
                uses: docker/build-push-action@v5
                with:
                  context: .
                  push: true
                  tags: ${{{{ steps.meta.outputs.tags }}}}
                  labels: ${{{{ steps.meta.outputs.labels }}}}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

          # ------------------------------------------------------------------
          # Scan: Trivy container vulnerability scan
          # ------------------------------------------------------------------
          scan:
            runs-on: ubuntu-latest
            needs: build
            if: github.event_name == 'push' && github.ref == 'refs/heads/main'

            steps:
              - uses: actions/checkout@v4

              - name: Build image for scanning
                run: docker build -t ${{{{ env.IMAGE_NAME }}}}:scan .

              - name: Run Trivy vulnerability scanner
                uses: aquasecurity/trivy-action@master
                with:
                  image-ref: ${{{{ env.IMAGE_NAME }}}}:scan
                  format: sarif
                  output: trivy-results.sarif
                  severity: CRITICAL,HIGH
                  exit-code: "1"

              - name: Upload Trivy scan results
                uses: github/codeql-action/upload-sarif@v3
                if: always()
                with:
                  sarif_file: trivy-results.sarif
    """)

    file_path = out / "ci.yml"
    file_path.write_text(content)

    return {
        "files_created": [str(file_path)],
        "notes": [
            f"GitHub Actions CI: Python {python_version}, Postgres {postgres_version} service container.",
            "Jobs: lint (ruff + mypy) -> test (pytest + coverage >= 80%) -> build (Docker) -> scan (Trivy).",
            "Build + scan only run on push to main (not on PRs).",
            "Uses GHCR (ghcr.io) for container registry with GitHub token auth.",
            "Docker layer caching via GitHub Actions cache (type=gha).",
        ],
    }
