from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class S3ClientProtocol(Protocol):
    """Auto-inferred Protocol surface for `S3Client`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_staging/`.
    """

    def generate_key(self, filename: str, prefix: str = '') -> str: ...
    def presigned_upload_url(self, key: str, content_type: str, expiration: int | None = None) -> str: ...
    def presigned_download_url(self, key: str, expiration: int | None = None) -> str: ...
    def delete_object(self, key: str) -> None: ...
    def guess_content_type(self, filename: str) -> str: ...
