"""BEHAVIOR TEST — TOOL-097 add_bulkhead_isolation.

Proves that the code generated by ``add_bulkhead_isolation`` works at **runtime**:
boots a real ASGI app and verifies bulkhead isolation contracts.

Patches applied (so tests run without Docker):
- ``app/core/db.py``         → SQLite + aiosqlite (no Postgres)
- ``app/middleware/idempotency.py`` → pass-through stub (no Redis)
- ``REDIS_URL`` env var      → removed (no Redis needed)

Run::

    PYTHONPATH=. pytest adapt/extend/infrastructure/test_add_bulkhead_isolation_behavior.py -v

or standalone::

    PYTHONPATH=. python3 adapt/extend/infrastructure/test_add_bulkhead_isolation_behavior.py
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Environment setup — MUST happen before any app import
# ---------------------------------------------------------------------------
import os

os.environ.setdefault("RATE_LIMITING_ENABLED", "false")
os.environ.setdefault("ENVIRONMENT", "local")
os.environ.setdefault("SECRET_KEY", "behavior-test-bulkhead-secret-key-32+chars!")
os.environ.pop("REDIS_URL", None)

import ast
import importlib
import sys
import textwrap
from pathlib import Path
from typing import Any

import anyio
import httpx
import pytest

from adapt.contracts import ToolInput
from adapt.extend.infrastructure.add_bulkhead_isolation import add_bulkhead_isolation
from tests.common.fixture_factory import create_fixture_project

# ---------------------------------------------------------------------------
# Patch templates
# ---------------------------------------------------------------------------

_SQLITE_DB_PY = textwrap.dedent("""\
    \"\"\"Patched db.py — SQLite+aiosqlite, no Docker required.\"\"\"

    from sqlalchemy import text
    from sqlalchemy.ext.asyncio import create_async_engine

    engine = create_async_engine(
        "sqlite+aiosqlite:///:memory:",
        echo=False,
        future=True,
        connect_args={"check_same_thread": False},
    )


    async def init_db() -> None:
        \"\"\"Run startup checks (connection test).\"\"\"
        async with engine.begin() as conn:
            await conn.execute(text("SELECT 1"))


    __all__ = ["engine", "init_db"]
""")

_PASSTHROUGH_IDEMPOTENCY_PY = textwrap.dedent("""\
    \"\"\"Patched idempotency.py — pass-through stub (no Redis).\"\"\"

    from __future__ import annotations

    from starlette.middleware.base import BaseHTTPMiddleware, RequestResponseEndpoint
    from starlette.requests import Request
    from starlette.responses import Response


    class IdempotencyMiddleware(BaseHTTPMiddleware):
        \"\"\"No-op pass-through stub for testing without Redis.\"\"\"

        async def dispatch(
            self,
            request: Request,
            call_next: RequestResponseEndpoint,
        ) -> Response:
            return await call_next(request)
""")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _patch_project(project_dir: Path) -> None:
    """Apply SQLite + idempotency stubs to the fixture project."""
    (project_dir / "app" / "core" / "db.py").write_text(_SQLITE_DB_PY)
    mw_dir = project_dir / "app" / "middleware"
    mw_dir.mkdir(parents=True, exist_ok=True)
    (mw_dir / "idempotency.py").write_text(_PASSTHROUGH_IDEMPOTENCY_PY)


def _load_app(project_dir: Path) -> Any:
    """Load ``app.main:app`` from *project_dir* in an isolated sys.path context."""
    _orig_path = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        app_module = importlib.import_module("app.main")
    finally:
        sys.path[:] = _orig_path
    return app_module.app


def _setup_project() -> tuple[Path, Any]:
    """Create, patch, apply tool, and load app."""
    project_dir = create_fixture_project(name="bh_behavior")
    result = add_bulkhead_isolation(ToolInput(project_dir=str(project_dir)))
    assert result.status == "success", (
        f"add_bulkhead_isolation failed: {result.error}\nnotes: {result.notes}"
    )
    _patch_project(project_dir)
    asgi_app = _load_app(project_dir)
    return project_dir, asgi_app


# ---------------------------------------------------------------------------
# Module-level shared fixture
# ---------------------------------------------------------------------------

_PROJECT_DIR: Path | None = None
_ASGI_APP: Any = None


def _get_shared_app() -> tuple[Path, Any]:
    global _PROJECT_DIR, _ASGI_APP
    if _PROJECT_DIR is None:
        _PROJECT_DIR, _ASGI_APP = _setup_project()
    return _PROJECT_DIR, _ASGI_APP


@pytest.fixture(scope="module")
def project_dir_and_app() -> tuple[Path, Any]:
    return _get_shared_app()


@pytest.fixture(scope="module")
def project_dir(project_dir_and_app: tuple[Path, Any]) -> Path:
    return project_dir_and_app[0]


@pytest.fixture(scope="module")
def asgi_app(project_dir_and_app: tuple[Path, Any]) -> Any:
    return project_dir_and_app[1]


# ---------------------------------------------------------------------------
# B-01: GET /healthz → 200
# ---------------------------------------------------------------------------

@pytest.mark.anyio
async def test_b01_healthz_returns_200(asgi_app: Any) -> None:
    """B-01: GET /healthz returns 200 after bulkhead isolation applied."""
    transport = httpx.ASGITransport(app=asgi_app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.get("/healthz")
    assert response.status_code == 200, (
        f"Expected 200, got {response.status_code}; body: {response.text}"
    )


# ---------------------------------------------------------------------------
# B-02: Bulkhead rejects when pool is full
# ---------------------------------------------------------------------------

@pytest.mark.anyio
async def test_b02_bulkhead_rejects_when_full(project_dir: Path) -> None:
    """B-02: Bulkhead raises BulkheadFullError when max_concurrent is reached."""
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        from app.resilience.bulkhead import Bulkhead, BulkheadFullError
        from app.resilience.pool_config import BulkheadConfig
        bulkhead = Bulkhead(BulkheadConfig(limits={"test_group": 1}))
        pool = bulkhead.acquire("test_group")

        async def _exhaust_and_try() -> None:
            # Exhaust the semaphore
            await pool.__aenter__()
            try:
                # Now this should fail — pool is full
                with pytest.raises(BulkheadFullError):
                    await pool.__aenter__()
            finally:
                await pool.__aexit__(None, None, None)

        await _exhaust_and_try()
    finally:
        sys.path.remove(str(project_dir))


# ---------------------------------------------------------------------------
# B-03: classify_route maps paths to groups
# ---------------------------------------------------------------------------

def test_b03_classify_route(project_dir: Path) -> None:
    """B-03: classify_route() maps payment paths to 'payments', analytics to 'analytics'."""
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        from app.resilience.pool_config import classify_route
        assert classify_route("/payments/charge") == "payments"
        assert classify_route("/billing/invoice") == "payments"
        assert classify_route("/analytics/events") == "analytics"
        assert classify_route("/api/items") == "crud"
        assert classify_route("/users/profile") == "crud"
    finally:
        sys.path.remove(str(project_dir))


# ---------------------------------------------------------------------------
# B-04: Bulkhead.status() returns pool utilization
# ---------------------------------------------------------------------------

def test_b04_bulkhead_status(project_dir: Path) -> None:
    """B-04: Bulkhead.status() returns dict with active/max/available per group."""
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        from app.resilience.bulkhead import Bulkhead
        from app.resilience.pool_config import BulkheadConfig
        bulkhead = Bulkhead(BulkheadConfig(limits={"payments": 10, "crud": 50}))
        status = bulkhead.status()
        assert "payments" in status
        assert "crud" in status
        for group_status in status.values():
            assert "active" in group_status
            assert "max" in group_status
            assert "available" in group_status
    finally:
        sys.path.remove(str(project_dir))


# ---------------------------------------------------------------------------
# B-05: GET /resilience/bulkheads endpoint (if router included)
# ---------------------------------------------------------------------------

def test_b05_bulkhead_status_route_file(project_dir: Path) -> None:
    """B-05: bulkhead_status.py contains a route returning bulkhead status."""
    status_file = project_dir / "app" / "api" / "routes" / "bulkhead_status.py"
    assert status_file.exists(), "bulkhead_status.py must exist"
    content = status_file.read_text()
    assert "bulkheads" in content, "Route must reference 'bulkheads'"
    assert "get_bulkhead" in content, "Route must call get_bulkhead()"


# ---------------------------------------------------------------------------
# B-06: BulkheadConfig validates positive limits
# ---------------------------------------------------------------------------

def test_b06_bulkhead_config_validates_limits(project_dir: Path) -> None:
    """B-06: BulkheadConfig raises ValueError for limits < 1."""
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        from app.resilience.pool_config import BulkheadConfig
        with pytest.raises((ValueError, Exception)):
            BulkheadConfig(limits={"payments": 0})
    finally:
        sys.path.remove(str(project_dir))


# ---------------------------------------------------------------------------
# B-07: Lazy SDK imports verified via AST
# ---------------------------------------------------------------------------

def test_b07_lazy_sdk_imports(project_dir: Path) -> None:
    """B-07: No optional SDKs are imported at module top-level in OUR generated files."""
    # Only scan the directories we generated — not pre-existing project files
    generated_dirs = [
        project_dir / "app" / "resilience",
        project_dir / "app" / "middleware",
    ]
    optional_sdks = {"redis", "stripe", "boto3", "psutil", "prometheus_client"}
    violations: list[str] = []
    for check_dir in generated_dirs:
        if not check_dir.exists():
            continue
        for py_file in check_dir.rglob("*.py"):
            source = py_file.read_text()
            try:
                tree = ast.parse(source)
            except SyntaxError:
                continue
            for node in tree.body:
                if isinstance(node, ast.Import):
                    for alias in node.names:
                        root_name = alias.name.split(".")[0]
                        if root_name in optional_sdks:
                            violations.append(f"{py_file.name}:{node.lineno} import {alias.name}")
                elif isinstance(node, ast.ImportFrom):
                    if node.module:
                        root_name = node.module.split(".")[0]
                        if root_name in optional_sdks:
                            violations.append(
                                f"{py_file.name}:{node.lineno} from {node.module} import ..."
                            )
    assert not violations, (
        "Optional SDKs found at top-level in generated files:\n"
        + "\n".join(f"  {v}" for v in violations)
    )


# ---------------------------------------------------------------------------
# B-08: All generated functions <= 50 LOC
# ---------------------------------------------------------------------------

def test_b08_all_functions_max_50_loc(project_dir: Path) -> None:
    """B-08: No function in generated resilience or middleware files exceeds 50 LOC."""
    resilience_dir = project_dir / "app" / "resilience"
    middleware_dir = project_dir / "app" / "middleware"
    violations: list[str] = []
    check_dirs = []
    if resilience_dir.exists():
        check_dirs.append(resilience_dir)
    if middleware_dir.exists():
        check_dirs.append(middleware_dir)
    for d in check_dirs:
        for py_file in d.rglob("*.py"):
            tree = ast.parse(py_file.read_text())
            for node in ast.walk(tree):
                if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    loc = (node.end_lineno or node.lineno) - node.lineno + 1
                    if loc > 50:
                        violations.append(
                            f"{py_file.name}:{node.lineno} {node.name}() = {loc} LOC"
                        )
    assert not violations, "Functions > 50 LOC:\n" + "\n".join(violations)


# ---------------------------------------------------------------------------
# B-09: Config fields 4-space indent
# ---------------------------------------------------------------------------

def test_b09_config_fields_4_space_indent(project_dir: Path) -> None:
    """B-09: BULKHEAD_* fields in config.py use 4-space indent."""
    config_file = project_dir / "app" / "core" / "config.py"
    assert config_file.exists()
    content = config_file.read_text()
    assert "    BULKHEAD_ENABLED" in content, (
        "BULKHEAD_ENABLED must be indented with 4 spaces in Settings class"
    )


# ---------------------------------------------------------------------------
# B-10: get_default_config reads from environment
# ---------------------------------------------------------------------------

def test_b10_get_default_config(project_dir: Path) -> None:
    """B-10: get_default_config() returns BulkheadConfig with expected defaults."""
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        from app.resilience.pool_config import get_default_config
        config = get_default_config()
        assert "payments" in config.limits
        assert "crud" in config.limits
        assert "analytics" in config.limits
        assert config.limits["payments"] >= 1
        assert config.limits["crud"] >= 1
        assert config.limits["analytics"] >= 1
    finally:
        sys.path.remove(str(project_dir))


# ---------------------------------------------------------------------------
# Standalone runner
# ---------------------------------------------------------------------------

def _run_async_test(coro_fn: Any, *args: Any) -> None:
    import inspect
    async def _wrapper() -> None:
        await coro_fn(*args)
    if inspect.iscoroutinefunction(coro_fn):
        anyio.run(_wrapper)
    else:
        coro_fn(*args)


if __name__ == "__main__":
    _pd, _app = _get_shared_app()

    _TESTS: list[tuple[str, Any]] = [
        ("B-01: /healthz → 200", lambda: _run_async_test(test_b01_healthz_returns_200, _app)),
        ("B-02: Rejects when full", lambda: _run_async_test(test_b02_bulkhead_rejects_when_full, _pd)),
        ("B-03: classify_route", lambda: test_b03_classify_route(_pd)),
        ("B-04: status() utilization", lambda: test_b04_bulkhead_status(_pd)),
        ("B-05: status route file", lambda: test_b05_bulkhead_status_route_file(_pd)),
        ("B-06: config validates limits", lambda: test_b06_bulkhead_config_validates_limits(_pd)),
        ("B-07: Lazy SDK imports", lambda: test_b07_lazy_sdk_imports(_pd)),
        ("B-08: All functions <= 50 LOC", lambda: test_b08_all_functions_max_50_loc(_pd)),
        ("B-09: Config 4-space indent", lambda: test_b09_config_fields_4_space_indent(_pd)),
        ("B-10: get_default_config", lambda: test_b10_get_default_config(_pd)),
    ]

    passed = failed = 0
    for name, fn in _TESTS:
        try:
            fn()
            print(f"  PASS  {name}")
            passed += 1
        except Exception as exc:
            print(f"  FAIL  {name}: {exc}")
            failed += 1

    print(f"\n{'='*60}")
    print(f"TOOL-097 BEHAVIOR: {passed}/{passed + failed} passed")
    if failed:
        sys.exit(1)
