"""BEHAVIOR TEST — TOOL-111 add_runtime_sentinel.

Proves that the code generated by ``add_runtime_sentinel`` works at runtime:
boots a real ASGI app, hits /healthz, verifies InjectionDetector and
RuntimeSentinelMiddleware are importable and functionally correct.

Patches applied (so tests run without Docker):
- ``app/core/db.py``               → SQLite + aiosqlite (no Postgres)
- ``app/middleware/idempotency.py`` → pass-through stub (no Redis)
- ``REDIS_URL`` env var             → removed (no Redis needed)

Run::

    PYTHONPATH=. pytest adapt/extend/infrastructure/test_add_runtime_sentinel_behavior.py -v

or standalone::

    PYTHONPATH=. python3 adapt/extend/infrastructure/test_add_runtime_sentinel_behavior.py
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Environment setup — MUST happen before any app import
# ---------------------------------------------------------------------------
import os

os.environ.setdefault("RATE_LIMITING_ENABLED", "false")
os.environ.setdefault("ENVIRONMENT", "local")
os.environ.setdefault("SECRET_KEY", "behavior-test-sentinel-secret-key-32+chars!")
os.environ.setdefault("SENTINEL_ENABLED", "true")
os.environ.setdefault("SENTINEL_MODE", "learning")
os.environ.setdefault("SENTINEL_ALLOWED_HOSTS", "")
os.environ.pop("REDIS_URL", None)

import ast
import importlib
import importlib.util
import sys
import textwrap
from pathlib import Path
from typing import Any

import anyio
import httpx
import pytest

from adapt.contracts import ToolInput
from adapt.extend.infrastructure.add_runtime_sentinel import add_runtime_sentinel
from tests.common.fixture_factory import create_fixture_project


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_SQLITE_DB_PY = textwrap.dedent("""\
    \"\"\"Patched db.py — SQLite+aiosqlite, no Docker required.\"\"\"

    from sqlalchemy import text
    from sqlalchemy.ext.asyncio import create_async_engine

    engine = create_async_engine(
        "sqlite+aiosqlite:///:memory:",
        echo=False,
        future=True,
        connect_args={"check_same_thread": False},
    )


    async def init_db() -> None:
        \"\"\"Run startup checks (connection test).\"\"\"
        async with engine.begin() as conn:
            await conn.execute(text("SELECT 1"))


    __all__ = ["engine", "init_db"]
""")

_PASSTHROUGH_IDEMPOTENCY_PY = textwrap.dedent("""\
    \"\"\"Patched idempotency.py — pass-through stub (no Redis).\"\"\"

    from __future__ import annotations

    from starlette.middleware.base import BaseHTTPMiddleware, RequestResponseEndpoint
    from starlette.requests import Request
    from starlette.responses import Response


    class IdempotencyMiddleware(BaseHTTPMiddleware):
        \"\"\"No-op pass-through stub for testing without Redis.\"\"\"

        async def dispatch(
            self,
            request: Request,
            call_next: RequestResponseEndpoint,
        ) -> Response:
            return await call_next(request)
""")


def _patch_project(project_dir: Path) -> None:
    """Apply SQLite + idempotency stubs to the fixture project."""
    (project_dir / "app" / "core" / "db.py").write_text(_SQLITE_DB_PY)
    idempotency_path = project_dir / "app" / "middleware" / "idempotency.py"
    if idempotency_path.exists():
        idempotency_path.write_text(_PASSTHROUGH_IDEMPOTENCY_PY)


def _load_app(project_dir: Path) -> Any:
    """Load ``app.main:app`` from *project_dir* in an isolated sys.path context."""
    _orig_path = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        app_module = importlib.import_module("app.main")
    finally:
        sys.path[:] = _orig_path
    return app_module.app


def _setup_project() -> tuple[Path, Any]:
    """Create, patch, apply tool, and load app."""
    project_dir = create_fixture_project(name="sentinel_behavior")
    result = add_runtime_sentinel(ToolInput(project_dir=str(project_dir)))
    assert result.status == "success", (
        f"add_runtime_sentinel failed: {result.error}\nnotes: {result.notes}"
    )
    _patch_project(project_dir)
    asgi_app = _load_app(project_dir)
    return project_dir, asgi_app


# ---------------------------------------------------------------------------
# Module-level shared fixture
# ---------------------------------------------------------------------------

_PROJECT_DIR: Path | None = None
_ASGI_APP: Any = None


def _get_shared_app() -> tuple[Path, Any]:
    global _PROJECT_DIR, _ASGI_APP
    if _PROJECT_DIR is None:
        _PROJECT_DIR, _ASGI_APP = _setup_project()
    return _PROJECT_DIR, _ASGI_APP


@pytest.fixture(scope="module")
def project_dir_and_app() -> tuple[Path, Any]:
    return _get_shared_app()


@pytest.fixture(scope="module")
def project_dir(project_dir_and_app: tuple[Path, Any]) -> Path:
    return project_dir_and_app[0]


@pytest.fixture(scope="module")
def asgi_app(project_dir_and_app: tuple[Path, Any]) -> Any:
    return project_dir_and_app[1]


# ---------------------------------------------------------------------------
# B-01: GET /healthz → 200
# ---------------------------------------------------------------------------

@pytest.mark.anyio
async def test_b01_healthz_returns_200(asgi_app: Any) -> None:
    """B-01: GET /healthz must return 200 after add_runtime_sentinel applied."""
    transport = httpx.ASGITransport(app=asgi_app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.get("/healthz")
    assert response.status_code == 200, (
        f"Expected 200, got {response.status_code}; body: {response.text}"
    )


# ---------------------------------------------------------------------------
# B-02: runtime_sentinel.py importable without starlette crash
# ---------------------------------------------------------------------------

def test_b02_runtime_sentinel_importable(project_dir: Path) -> None:
    """B-02: app/middleware/runtime_sentinel.py must be importable without raising."""
    sentinel_file = project_dir / "app" / "middleware" / "runtime_sentinel.py"
    assert sentinel_file.exists()
    orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        spec = importlib.util.spec_from_file_location(
            "app.middleware.runtime_sentinel_b02", str(sentinel_file)
        )
        assert spec and spec.loader
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)  # type: ignore[attr-defined]
    except Exception as exc:
        raise AssertionError(f"runtime_sentinel.py raised on import: {exc}") from exc
    finally:
        sys.path[:] = orig
    assert hasattr(mod, "RuntimeSentinelMiddleware")
    assert hasattr(mod, "InjectionDetector")


# ---------------------------------------------------------------------------
# B-03: InjectionDetector.check_sql detects tautology
# ---------------------------------------------------------------------------

def test_b03_injection_detector_sql_tautology(project_dir: Path) -> None:
    """B-03: InjectionDetector.check_sql returns True for tautology attack."""
    sentinel_file = project_dir / "app" / "middleware" / "runtime_sentinel.py"
    orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        spec = importlib.util.spec_from_file_location(
            "app.middleware.runtime_sentinel_b03", str(sentinel_file)
        )
        assert spec and spec.loader
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)  # type: ignore[attr-defined]
        detector = mod.InjectionDetector()
        assert detector.check_sql("1 OR 1=1"), "Tautology not detected"
        assert not detector.check_sql("hello world"), "False positive on safe string"
    finally:
        sys.path[:] = orig


# ---------------------------------------------------------------------------
# B-04: InjectionDetector.check_sql detects UNION SELECT
# ---------------------------------------------------------------------------

def test_b04_injection_detector_sql_union(project_dir: Path) -> None:
    """B-04: InjectionDetector.check_sql returns True for UNION SELECT attack."""
    sentinel_file = project_dir / "app" / "middleware" / "runtime_sentinel.py"
    orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        spec = importlib.util.spec_from_file_location(
            "app.middleware.runtime_sentinel_b04", str(sentinel_file)
        )
        assert spec and spec.loader
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)  # type: ignore[attr-defined]
        detector = mod.InjectionDetector()
        assert detector.check_sql("1 UNION SELECT password FROM users"), "UNION SELECT not detected"
    finally:
        sys.path[:] = orig


# ---------------------------------------------------------------------------
# B-05: InjectionDetector.check_ssrf blocks metadata IP
# ---------------------------------------------------------------------------

def test_b05_injection_detector_ssrf_metadata(project_dir: Path) -> None:
    """B-05: InjectionDetector.check_ssrf returns True for cloud metadata IP."""
    sentinel_file = project_dir / "app" / "middleware" / "runtime_sentinel.py"
    orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        spec = importlib.util.spec_from_file_location(
            "app.middleware.runtime_sentinel_b05", str(sentinel_file)
        )
        assert spec and spec.loader
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)  # type: ignore[attr-defined]
        detector = mod.InjectionDetector()
        assert detector.check_ssrf("http://169.254.169.254/latest/meta-data/", frozenset()), (
            "Cloud metadata IP not blocked"
        )
        assert not detector.check_ssrf("https://api.stripe.com/v1/charges", frozenset()), (
            "False positive on legitimate external URL"
        )
    finally:
        sys.path[:] = orig


# ---------------------------------------------------------------------------
# B-06: AttackPatternRegistry records events
# ---------------------------------------------------------------------------

def test_b06_attack_pattern_registry_records_events(project_dir: Path) -> None:
    """B-06: AttackPatternRegistry.record() increments count and stores event."""
    registry_file = project_dir / "app" / "core" / "sentinel_registry.py"
    orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        spec = importlib.util.spec_from_file_location(
            "app.core.sentinel_registry_b06", str(registry_file)
        )
        assert spec and spec.loader
        mod = importlib.util.module_from_spec(spec)
        sys.modules["app.core.sentinel_registry_b06"] = mod  # required for @dataclass in Py3.14
        spec.loader.exec_module(mod)  # type: ignore[attr-defined]
        registry = mod.AttackPatternRegistry()
        event = mod.SecurityEvent(
            attack_type="sql_injection",
            request_path="/api/users",
            payload_snippet="1 OR 1=1",
        )
        registry.record(event)
        assert registry.count("sql_injection") == 1, "count() should be 1 after one record"
        assert len(registry.recent("sql_injection", since_seconds=60)) == 1
    finally:
        sys.path[:] = orig


# ---------------------------------------------------------------------------
# B-07: all generated functions <= 50 LOC
# ---------------------------------------------------------------------------

def test_b07_all_generated_functions_under_50_loc(project_dir: Path) -> None:
    """B-07: All generated functions in middleware + core are <= 50 LOC."""
    sentinel_file = project_dir / "app" / "middleware" / "runtime_sentinel.py"
    registry_file = project_dir / "app" / "core" / "sentinel_registry.py"
    violations: list[str] = []
    for py_file in (sentinel_file, registry_file):
        if not py_file.exists():
            continue
        tree = ast.parse(py_file.read_text())
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                loc = (node.end_lineno or node.lineno) - node.lineno + 1
                if loc > 50:
                    violations.append(f"{py_file.name}:{node.name} ({loc} LOC)")
    assert not violations, "Functions > 50 LOC:\n" + "\n".join(violations)


# ---------------------------------------------------------------------------
# B-08: config fields 4-space indent
# ---------------------------------------------------------------------------

def test_b08_config_fields_4_space_indent(project_dir: Path) -> None:
    """B-08: SENTINEL_* config fields have 4-space indent in config.py."""
    config = project_dir / "app" / "core" / "config.py"
    assert config.exists()
    content = config.read_text()
    for line in content.splitlines():
        if any(f in line for f in ("SENTINEL_ENABLED", "SENTINEL_MODE", "SENTINEL_ALLOWED_HOSTS")):
            assert line.startswith("    "), f"Not 4-space indented: {line!r}"


# ---------------------------------------------------------------------------
# Standalone runner
# ---------------------------------------------------------------------------

def _run_async_test(coro_fn: Any, *args: Any) -> None:
    import inspect

    async def _wrapper() -> None:
        await coro_fn(*args)

    if inspect.iscoroutinefunction(coro_fn):
        anyio.run(_wrapper)
    else:
        coro_fn(*args)


if __name__ == "__main__":
    _pd, _app = _get_shared_app()

    _TESTS: list[tuple[str, Any]] = [
        ("B-01: /healthz → 200", lambda: _run_async_test(test_b01_healthz_returns_200, _app)),
        ("B-02: runtime_sentinel.py importable", lambda: test_b02_runtime_sentinel_importable(_pd)),
        ("B-03: SQL tautology detected", lambda: test_b03_injection_detector_sql_tautology(_pd)),
        ("B-04: UNION SELECT detected", lambda: test_b04_injection_detector_sql_union(_pd)),
        ("B-05: SSRF metadata blocked", lambda: test_b05_injection_detector_ssrf_metadata(_pd)),
        ("B-06: registry records events", lambda: test_b06_attack_pattern_registry_records_events(_pd)),
        ("B-07: all funcs <= 50 LOC", lambda: test_b07_all_generated_functions_under_50_loc(_pd)),
        ("B-08: config 4-space indent", lambda: test_b08_config_fields_4_space_indent(_pd)),
    ]

    passed = failed = 0
    for name, fn in _TESTS:
        try:
            fn()
            print(f"  PASS  {name}")
            passed += 1
        except Exception as exc:
            print(f"  FAIL  {name}: {exc}")
            failed += 1

    print(f"\n{'='*60}")
    print(f"TOOL-111 BEHAVIOR: {passed}/{passed + failed} passed")
    if failed:
        sys.exit(1)
