"""BEHAVIOR TEST — TOOL-102 add_anomaly_detector.

Proves that the code generated by ``add_anomaly_detector`` works at
**runtime**: boots a real ASGI app, hits endpoints with an httpx client,
and asserts structural quality invariants.

Patches applied (so tests run without Docker/Redis):
- ``app/core/db.py``                  → SQLite+aiosqlite (no Postgres)
- ``app/middleware/idempotency.py``   → pass-through stub (no Redis)
- ``REDIS_URL`` env var               → removed

Run::

    PYTHONPATH=. pytest adapt/extend/infrastructure/test_add_anomaly_detector_behavior.py -v

or standalone::

    PYTHONPATH=. python3 adapt/extend/infrastructure/test_add_anomaly_detector_behavior.py
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Environment setup — MUST happen before any app import
# ---------------------------------------------------------------------------
import os

os.environ.setdefault("RATE_LIMITING_ENABLED", "false")
os.environ.setdefault("ENVIRONMENT", "local")
os.environ.setdefault("SECRET_KEY", "behavior-test-anomaly-detector-secret-key-32chars!")
os.environ.pop("REDIS_URL", None)

import ast
import importlib
import importlib.util
import json
import sys
import textwrap
from pathlib import Path
from typing import Any

import anyio
import httpx
import pytest

from adapt.contracts import ToolInput
from adapt.extend.infrastructure.add_anomaly_detector import add_anomaly_detector
from tests.common.fixture_factory import create_fixture_project


# ---------------------------------------------------------------------------
# Patch templates
# ---------------------------------------------------------------------------

_SQLITE_DB_PY = textwrap.dedent("""\
    \"\"\"Patched db.py — SQLite+aiosqlite, no Docker required.\"\"\"

    from sqlalchemy import text
    from sqlalchemy.ext.asyncio import create_async_engine

    engine = create_async_engine(
        "sqlite+aiosqlite:///:memory:",
        echo=False,
        future=True,
        connect_args={"check_same_thread": False},
    )


    async def init_db() -> None:
        \"\"\"Run startup checks (connection test).\"\"\"
        async with engine.begin() as conn:
            await conn.execute(text("SELECT 1"))


    __all__ = ["engine", "init_db"]
""")

_PASSTHROUGH_IDEMPOTENCY_PY = textwrap.dedent("""\
    \"\"\"Patched idempotency.py — pass-through stub (no Redis).\"\"\"

    from __future__ import annotations

    from starlette.middleware.base import BaseHTTPMiddleware, RequestResponseEndpoint
    from starlette.requests import Request
    from starlette.responses import Response


    class IdempotencyMiddleware(BaseHTTPMiddleware):
        \"\"\"No-op pass-through stub for testing without Redis.\"\"\"

        async def dispatch(
            self,
            request: Request,
            call_next: RequestResponseEndpoint,
        ) -> Response:
            return await call_next(request)
""")


def _patch_project(project_dir: Path) -> None:
    """Apply SQLite + idempotency stubs to the fixture project."""
    (project_dir / "app" / "core" / "db.py").write_text(_SQLITE_DB_PY)
    (project_dir / "app" / "middleware" / "idempotency.py").write_text(
        _PASSTHROUGH_IDEMPOTENCY_PY
    )


def _load_app(project_dir: Path) -> Any:
    """Load ``app.main:app`` from *project_dir* in an isolated sys.path context."""
    _orig_path = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]
    try:
        app_module = importlib.import_module("app.main")
    finally:
        sys.path[:] = _orig_path
    return app_module.app


def _setup_project() -> tuple[Path, Any]:
    """Create, apply tool, patch, load app. Returns (project_dir, asgi_app)."""
    project_dir = create_fixture_project(name="anomaly_behavior")
    result = add_anomaly_detector(ToolInput(project_dir=str(project_dir)))
    assert result.status == "success", (
        f"add_anomaly_detector failed: {result.error}\nnotes: {result.notes}"
    )
    _patch_project(project_dir)
    asgi_app = _load_app(project_dir)
    return project_dir, asgi_app


# ---------------------------------------------------------------------------
# Module-level shared fixture
# ---------------------------------------------------------------------------

_PROJECT_DIR: Path | None = None
_ASGI_APP: Any = None


def _get_shared_app() -> tuple[Path, Any]:
    global _PROJECT_DIR, _ASGI_APP
    if _PROJECT_DIR is None:
        _PROJECT_DIR, _ASGI_APP = _setup_project()
    return _PROJECT_DIR, _ASGI_APP


@pytest.fixture(scope="module")
def project_dir_and_app() -> tuple[Path, Any]:
    """Shared (module-scoped) fixture: one project for all behavior tests."""
    return _get_shared_app()


@pytest.fixture(scope="module")
def project_dir(project_dir_and_app: tuple[Path, Any]) -> Path:
    return project_dir_and_app[0]


@pytest.fixture(scope="module")
def asgi_app(project_dir_and_app: tuple[Path, Any]) -> Any:
    return project_dir_and_app[1]


# ---------------------------------------------------------------------------
# BEHAVIOR-01: GET /healthz → 200
# ---------------------------------------------------------------------------

@pytest.mark.anyio
async def test_b01_healthz_returns_200(asgi_app: Any) -> None:
    """B-01: GET /healthz must return 200 — base liveness probe."""
    transport = httpx.ASGITransport(app=asgi_app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.get("/healthz")
    assert response.status_code == 200, (
        f"Expected 200, got {response.status_code}; body: {response.text}"
    )


# ---------------------------------------------------------------------------
# BEHAVIOR-02: detector.py importable
# ---------------------------------------------------------------------------

def test_b02_detector_importable(project_dir: Path) -> None:
    """B-02: app/anomaly/detector.py must be importable without raising."""
    detector_file = project_dir / "app" / "anomaly" / "detector.py"
    assert detector_file.exists(), "detector.py not found"
    spec = importlib.util.spec_from_file_location(
        "app.anomaly.detector_behavior_test", str(detector_file)
    )
    assert spec is not None and spec.loader is not None
    _orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    try:
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)  # type: ignore[attr-defined]
    except Exception as exc:
        raise AssertionError(f"detector.py raised on import: {exc}") from exc
    finally:
        sys.path[:] = _orig
    assert hasattr(module, "AnomalyDetector"), "AnomalyDetector not found"
    assert hasattr(module, "get_detector"), "get_detector not found"
    assert hasattr(module, "init_detector"), "init_detector not found"


# ---------------------------------------------------------------------------
# BEHAVIOR-03: alerter.py importable
# ---------------------------------------------------------------------------

def test_b03_alerter_importable(project_dir: Path) -> None:
    """B-03: app/anomaly/alerter.py must be importable without raising."""
    alerter_file = project_dir / "app" / "anomaly" / "alerter.py"
    assert alerter_file.exists(), "alerter.py not found"
    _orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    try:
        spec = importlib.util.spec_from_file_location(
            "app.anomaly.alerter_behavior_test", str(alerter_file)
        )
        assert spec and spec.loader
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)  # type: ignore[attr-defined]
    except Exception as exc:
        raise AssertionError(f"alerter.py raised on import: {exc}") from exc
    finally:
        sys.path[:] = _orig
    assert hasattr(module, "AlertDispatcher"), "AlertDispatcher not found"


# ---------------------------------------------------------------------------
# BEHAVIOR-04: ANOMALY_ENABLED in config.py
# ---------------------------------------------------------------------------

def test_b04_config_has_anomaly_enabled(project_dir: Path) -> None:
    """B-04: app/core/config.py must contain ANOMALY_ENABLED."""
    config_file = project_dir / "app" / "core" / "config.py"
    assert config_file.exists(), "config.py not found"
    content = config_file.read_text()
    assert "ANOMALY_ENABLED" in content, (
        "ANOMALY_ENABLED not found in app/core/config.py"
    )


# ---------------------------------------------------------------------------
# BEHAVIOR-05: httpx NOT at top level in alerter.py
# ---------------------------------------------------------------------------

def test_b05_httpx_not_top_level_in_alerter(project_dir: Path) -> None:
    """B-05: httpx must NOT appear in top-level imports in alerter.py."""
    alerter_file = project_dir / "app" / "anomaly" / "alerter.py"
    source = alerter_file.read_text()
    tree = ast.parse(source)
    violations: list[str] = []
    for node in tree.body:
        if isinstance(node, ast.Import):
            for alias in node.names:
                if "httpx" in alias.name.lower():
                    violations.append(f"line {node.lineno}: import {alias.name}")
        elif isinstance(node, ast.ImportFrom) and node.module:
            if "httpx" in node.module.lower():
                violations.append(f"line {node.lineno}: from {node.module} import ...")
    assert not violations, (
        "httpx found at top level in alerter.py:\n"
        + "\n".join(f"  {v}" for v in violations)
    )


# ---------------------------------------------------------------------------
# BEHAVIOR-06: all generated functions <= 50 LOC
# ---------------------------------------------------------------------------

def test_b06_no_function_over_50_loc(project_dir: Path) -> None:
    """B-06: All functions in app/anomaly/ must be <= 50 LOC."""
    anomaly_dir = project_dir / "app" / "anomaly"
    violations: list[str] = []
    for py_file in sorted(anomaly_dir.rglob("*.py")):
        try:
            tree = ast.parse(py_file.read_text())
        except SyntaxError:
            continue
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                if node.end_lineno:
                    loc = node.end_lineno - node.lineno + 1
                    if loc > 50:
                        violations.append(
                            f"{py_file.name}::{node.name} ({loc} LOC)"
                        )
    assert not violations, (
        "Functions exceed 50 LOC in anomaly package:\n"
        + "\n".join(f"  {v}" for v in violations)
    )


# ---------------------------------------------------------------------------
# BEHAVIOR-07: config fields have 4-space indent
# ---------------------------------------------------------------------------

def test_b07_config_fields_4space_indent(project_dir: Path) -> None:
    """B-07: ANOMALY_* config fields must have 4-space indent in config.py."""
    config_file = project_dir / "app" / "core" / "config.py"
    content = config_file.read_text()
    anomaly_fields = ["ANOMALY_ENABLED", "ANOMALY_SENSITIVITY", "ANOMALY_WINDOW_SIZE"]
    for field in anomaly_fields:
        for line in content.splitlines():
            if field in line and ":" in line:
                assert line.startswith("    "), (
                    f"Field {field} must be 4-space indented, got: {line!r}"
                )
                break


# ---------------------------------------------------------------------------
# BEHAVIOR-08: AnomalyDetector Z-score computation is pure Python (no external deps)
# ---------------------------------------------------------------------------

def test_b08_detector_z_score_pure_python(project_dir: Path) -> None:
    """B-08: AnomalyDetector Z-score uses math stdlib only (no numpy/scipy)."""
    detector_file = project_dir / "app" / "anomaly" / "detector.py"
    source = detector_file.read_text()
    tree = ast.parse(source)
    for node in tree.body:
        if isinstance(node, ast.Import):
            for alias in node.names:
                assert alias.name not in ("numpy", "scipy", "pandas"), (
                    f"detector.py uses heavy data library at top-level: {alias.name}"
                )
        elif isinstance(node, ast.ImportFrom) and node.module:
            top = node.module.split(".")[0]
            assert top not in ("numpy", "scipy", "pandas"), (
                f"detector.py uses heavy data library at top-level: {node.module}"
            )


# ---------------------------------------------------------------------------
# Helpers for standalone runner
# ---------------------------------------------------------------------------

def _run_async_test(coro_fn: Any, *args: Any) -> None:
    """Run an async test function via anyio.run."""
    import inspect

    async def _wrapper() -> None:
        await coro_fn(*args)

    if inspect.iscoroutinefunction(coro_fn):
        anyio.run(_wrapper)
    else:
        coro_fn(*args)


# ---------------------------------------------------------------------------
# Standalone runner
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    _pd, _app = _get_shared_app()

    _TESTS: list[tuple[str, Any]] = [
        ("B-01: /healthz → 200", lambda: _run_async_test(test_b01_healthz_returns_200, _app)),
        ("B-02: detector.py importable", lambda: test_b02_detector_importable(_pd)),
        ("B-03: alerter.py importable", lambda: test_b03_alerter_importable(_pd)),
        ("B-04: ANOMALY_ENABLED in config", lambda: test_b04_config_has_anomaly_enabled(_pd)),
        ("B-05: httpx NOT at top-level in alerter", lambda: test_b05_httpx_not_top_level_in_alerter(_pd)),
        ("B-06: no function > 50 LOC", lambda: test_b06_no_function_over_50_loc(_pd)),
        ("B-07: config fields 4-space indent", lambda: test_b07_config_fields_4space_indent(_pd)),
        ("B-08: Z-score pure Python", lambda: test_b08_detector_z_score_pure_python(_pd)),
    ]

    passed = 0
    failed = 0
    failures: list[str] = []

    for name, fn in _TESTS:
        try:
            fn()
            print(f"  PASS  {name}")
            passed += 1
        except Exception as exc:
            print(f"  FAIL  {name}: {exc}")
            failures.append(f"{name}: {exc}")
            failed += 1

    total = passed + failed
    status = "PASS" if failed == 0 else "FAIL"

    contract = {
        "tool": "TOOL-102 add_anomaly_detector",
        "test_file": "test_add_anomaly_detector_behavior.py",
        "total": total,
        "passed": passed,
        "failed": failed,
        "status": status,
        "failures": failures,
    }

    print(f"\n{'='*60}")
    print(f"TOOL-102 BEHAVIOR: {passed}/{total} passed")
    print(f"\nDelivery contract JSON:")
    print(json.dumps(contract, indent=2))

    if failed:
        sys.exit(1)
