"""BEHAVIOR TEST — TOOL-085 add_opentelemetry.

Proves that the code generated by ``add_opentelemetry`` works at runtime:
boots a real ASGI app (with OTEL_ENABLED=false so SDK is never imported),
hits /healthz, and verifies lazy SDK imports, LOC limits, config field
presence, and ruff F401 cleanliness.

Patches applied (so tests run without Docker or OTEL collector):
- ``app/core/db.py``                → SQLite + aiosqlite (no Postgres)
- ``app/middleware/idempotency.py`` → pass-through stub (no Redis)
- ``REDIS_URL`` env var             → removed (no Redis needed)
- ``OTEL_ENABLED``                  → false (no SDK needed)

Run::

    PYTHONPATH=. .venv/bin/pytest adapt/extend/infrastructure/test_add_opentelemetry_behavior.py -v

or standalone::

    PYTHONPATH=. .venv/bin/python adapt/extend/infrastructure/test_add_opentelemetry_behavior.py
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Environment setup — MUST happen before any app import
# ---------------------------------------------------------------------------
import os

os.environ.setdefault("RATE_LIMITING_ENABLED", "false")
os.environ.setdefault("ENVIRONMENT", "local")
os.environ.setdefault("SECRET_KEY", "behavior-test-otel-secret-key-32+chars!")
os.environ.setdefault("OTEL_ENABLED", "false")
os.environ.pop("REDIS_URL", None)

import ast
import importlib
import importlib.util
import subprocess
import sys
import textwrap
from pathlib import Path
from typing import Any

import anyio
import httpx
import pytest

from adapt.contracts import ToolInput
from adapt.extend.infrastructure.add_opentelemetry import add_opentelemetry
from tests.common.fixture_factory import create_fixture_project


# ---------------------------------------------------------------------------
# Patch templates
# ---------------------------------------------------------------------------

_SQLITE_DB_PY = textwrap.dedent("""\
    \"\"\"Patched db.py — SQLite+aiosqlite, no Docker required.\"\"\"

    from sqlalchemy.ext.asyncio import create_async_engine

    engine = create_async_engine(
        "sqlite+aiosqlite:///:memory:",
        echo=False,
        future=True,
        connect_args={"check_same_thread": False},
    )


    async def init_db() -> None:
        \"\"\"Create all tables from SQLAlchemy metadata (SQLite in-memory).\"\"\"
        from app.models.base import Base
        import app.models
        async with engine.begin() as conn:
            await conn.run_sync(Base.metadata.create_all)


    __all__ = ["engine", "init_db"]
""")

_PASSTHROUGH_IDEMPOTENCY_PY = textwrap.dedent("""\
    \"\"\"Patched idempotency.py — pass-through stub (no Redis).\"\"\"

    from __future__ import annotations

    from starlette.middleware.base import BaseHTTPMiddleware, RequestResponseEndpoint
    from starlette.requests import Request
    from starlette.responses import Response


    class IdempotencyMiddleware(BaseHTTPMiddleware):
        \"\"\"No-op pass-through stub for testing without Redis.\"\"\"

        async def dispatch(
            self,
            request: Request,
            call_next: RequestResponseEndpoint,
        ) -> Response:
            return await call_next(request)
""")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _patch_project(project_dir: Path) -> None:
    """Apply SQLite + idempotency stubs to the fixture project."""
    (project_dir / "app" / "core" / "db.py").write_text(_SQLITE_DB_PY)
    mw_dir = project_dir / "app" / "middleware"
    mw_dir.mkdir(parents=True, exist_ok=True)
    (mw_dir / "idempotency.py").write_text(_PASSTHROUGH_IDEMPOTENCY_PY)


def _load_app(project_dir: Path) -> Any:
    """Load ``app.main:app`` from *project_dir* in an isolated sys.path context."""
    orig_path = sys.path.copy()
    sys.path.insert(0, str(project_dir))

    stale = [k for k in sys.modules if k == "app" or k.startswith("app.")]
    for key in stale:
        del sys.modules[key]

    try:
        app_module = importlib.import_module("app.main")
    finally:
        sys.path[:] = orig_path

    return app_module.app


def _setup_project() -> tuple[Path, Any]:
    """Create, apply tool, patch, and load the ASGI app."""
    project_dir = create_fixture_project(name="otel_behavior")
    result = add_opentelemetry(ToolInput(project_dir=str(project_dir)))
    assert result.status == "success", (
        f"add_opentelemetry failed: {result.error}\nnotes: {result.notes}"
    )
    _patch_project(project_dir)
    asgi_app = _load_app(project_dir)
    return project_dir, asgi_app


# ---------------------------------------------------------------------------
# Module-level shared singleton
# ---------------------------------------------------------------------------

_PROJECT_DIR: Path | None = None
_ASGI_APP: Any = None


def _get_shared_app() -> tuple[Path, Any]:
    global _PROJECT_DIR, _ASGI_APP
    if _PROJECT_DIR is None:
        _PROJECT_DIR, _ASGI_APP = _setup_project()
    return _PROJECT_DIR, _ASGI_APP


@pytest.fixture(scope="module")
def project_dir_and_app() -> tuple[Path, Any]:
    """Shared (module-scoped) fixture: one project for all behavior tests."""
    return _get_shared_app()


@pytest.fixture(scope="module")
def project_dir(project_dir_and_app: tuple[Path, Any]) -> Path:
    """Return the project directory."""
    return project_dir_and_app[0]


@pytest.fixture(scope="module")
def asgi_app(project_dir_and_app: tuple[Path, Any]) -> Any:
    """Return the loaded ASGI app."""
    return project_dir_and_app[1]


# ---------------------------------------------------------------------------
# BEHAVIOR-01: GET /healthz → 200 (app boots without OTEL SDK)
# ---------------------------------------------------------------------------

@pytest.mark.anyio
async def test_b01_healthz_returns_200(asgi_app: Any) -> None:
    """B-01: GET /healthz must return 200 even without opentelemetry SDK installed."""
    transport = httpx.ASGITransport(app=asgi_app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.get("/healthz")
    assert response.status_code == 200, (
        f"Expected 200, got {response.status_code}; body: {response.text}"
    )


# ---------------------------------------------------------------------------
# BEHAVIOR-02: app boots without opentelemetry SDK (lazy imports verified)
# ---------------------------------------------------------------------------

def test_b02_setup_has_zero_toplevel_otel_imports(project_dir: Path) -> None:
    """B-02: app/telemetry/setup.py must have ZERO top-level opentelemetry imports."""
    setup_file = project_dir / "app" / "telemetry" / "setup.py"
    assert setup_file.exists(), "app/telemetry/setup.py not found"
    tree = ast.parse(setup_file.read_text())
    for node in tree.body:
        if isinstance(node, ast.Import):
            for alias in node.names:
                assert "opentelemetry" not in alias.name.lower(), (
                    f"opentelemetry at top level in setup.py: {alias.name}"
                )
        elif isinstance(node, ast.ImportFrom) and node.module:
            assert "opentelemetry" not in node.module.lower(), (
                f"opentelemetry at top level in setup.py: {node.module}"
            )


# ---------------------------------------------------------------------------
# BEHAVIOR-03: middleware.py has zero top-level otel imports
# ---------------------------------------------------------------------------

def test_b03_middleware_has_zero_toplevel_otel_imports(project_dir: Path) -> None:
    """B-03: app/telemetry/middleware.py must have ZERO top-level opentelemetry imports."""
    mw_file = project_dir / "app" / "telemetry" / "middleware.py"
    assert mw_file.exists(), "app/telemetry/middleware.py not found"
    tree = ast.parse(mw_file.read_text())
    for node in tree.body:
        if isinstance(node, ast.Import):
            for alias in node.names:
                assert "opentelemetry" not in alias.name.lower(), (
                    f"opentelemetry at top level in middleware.py: {alias.name}"
                )
        elif isinstance(node, ast.ImportFrom) and node.module:
            assert "opentelemetry" not in node.module.lower(), (
                f"opentelemetry at top level in middleware.py: {node.module}"
            )


# ---------------------------------------------------------------------------
# BEHAVIOR-04: metrics.py has zero top-level otel imports
# ---------------------------------------------------------------------------

def test_b04_metrics_has_zero_toplevel_otel_imports(project_dir: Path) -> None:
    """B-04: app/telemetry/metrics.py must have ZERO top-level opentelemetry imports."""
    metrics_file = project_dir / "app" / "telemetry" / "metrics.py"
    assert metrics_file.exists(), "app/telemetry/metrics.py not found"
    tree = ast.parse(metrics_file.read_text())
    for node in tree.body:
        if isinstance(node, ast.Import):
            for alias in node.names:
                assert "opentelemetry" not in alias.name.lower(), (
                    f"opentelemetry at top level in metrics.py: {alias.name}"
                )
        elif isinstance(node, ast.ImportFrom) and node.module:
            assert "opentelemetry" not in node.module.lower(), (
                f"opentelemetry at top level in metrics.py: {node.module}"
            )


# ---------------------------------------------------------------------------
# BEHAVIOR-05: all generated functions ≤50 LOC
# ---------------------------------------------------------------------------

def test_b05_all_functions_50_loc(project_dir: Path) -> None:
    """B-05: Every function in app/telemetry/ must be ≤50 LOC."""
    telemetry_dir = project_dir / "app" / "telemetry"
    assert telemetry_dir.exists(), "app/telemetry/ not found"
    for py_file in sorted(telemetry_dir.rglob("*.py")):
        tree = ast.parse(py_file.read_text())
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                if hasattr(node, "end_lineno") and node.end_lineno:
                    loc = node.end_lineno - node.lineno + 1
                    assert loc <= 50, (
                        f"Function '{node.name}' in {py_file} has {loc} LOC (limit: 50)"
                    )


# ---------------------------------------------------------------------------
# BEHAVIOR-06: config fields are 4-space indented
# ---------------------------------------------------------------------------

def test_b06_config_fields_4_space_indent(project_dir: Path) -> None:
    """B-06: OTEL_* config fields must be 4-space indented (inside class)."""
    config_file = project_dir / "app" / "core" / "config.py"
    assert config_file.exists(), "app/core/config.py not found"
    content = config_file.read_text()
    for field in ("OTEL_ENABLED", "OTEL_SERVICE_NAME"):
        assert field in content, f"{field} not in config.py"
    for line in content.splitlines():
        if "OTEL_ENABLED" in line and ":" in line:
            assert line.startswith("    "), (
                f"OTEL_ENABLED not 4-space indented: {line!r}"
            )
            break


# ---------------------------------------------------------------------------
# BEHAVIOR-07: ruff F401 clean on generated telemetry package
# ---------------------------------------------------------------------------

def test_b07_ruff_f401_clean(project_dir: Path) -> None:
    """B-07: No unused imports (F401) in app/telemetry/."""
    import shutil

    ruff_bin = shutil.which("ruff")
    if ruff_bin is None:
        pytest.skip("ruff not found in PATH — skipping F401 check")

    telemetry_dir = project_dir / "app" / "telemetry"
    if not telemetry_dir.exists():
        return

    for f in sorted(telemetry_dir.rglob("*.py")):
        result = subprocess.run(
            [ruff_bin, "check", "--select=F401", str(f)],
            capture_output=True,
            text=True,
        )
        assert result.returncode == 0, (
            f"ruff F401 violations in {f}:\n{result.stdout}{result.stderr}"
        )


# ---------------------------------------------------------------------------
# BEHAVIOR-08: setup.py importable without opentelemetry SDK
# ---------------------------------------------------------------------------

def test_b08_setup_module_loads_without_sdk(project_dir: Path) -> None:
    """B-08: app/telemetry/setup.py imports without raising even without SDK."""
    setup_file = project_dir / "app" / "telemetry" / "setup.py"
    assert setup_file.exists(), "app/telemetry/setup.py not found"

    spec = importlib.util.spec_from_file_location(
        "app.telemetry.setup_behavior_test", str(setup_file)
    )
    assert spec is not None and spec.loader is not None

    orig = sys.path.copy()
    sys.path.insert(0, str(project_dir))
    try:
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)  # type: ignore[attr-defined]
    except Exception as exc:
        raise AssertionError(
            f"app/telemetry/setup.py raised on import: {exc}"
        ) from exc
    finally:
        sys.path[:] = orig

    assert hasattr(module, "init_telemetry"), "init_telemetry not found in setup.py"
    assert hasattr(module, "get_tracer"), "get_tracer not found in setup.py"


# ---------------------------------------------------------------------------
# Standalone runner
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    tests_sync = [
        test_b02_setup_has_zero_toplevel_otel_imports,
        test_b03_middleware_has_zero_toplevel_otel_imports,
        test_b04_metrics_has_zero_toplevel_otel_imports,
        test_b05_all_functions_50_loc,
        test_b06_config_fields_4_space_indent,
        test_b07_ruff_f401_clean,
        test_b08_setup_module_loads_without_sdk,
    ]
    tests_async = [
        test_b01_healthz_returns_200,
    ]

    proj, app = _get_shared_app()

    counts = [0, 0]  # [passed, failed]

    for t in tests_sync:
        try:
            t(proj)
            print(f"  PASS  {t.__name__}")
            counts[0] += 1
        except Exception as exc:
            print(f"  FAIL  {t.__name__}: {exc}")
            counts[1] += 1

    async def _run_async() -> None:
        for t in tests_async:
            try:
                await t(app)
                print(f"  PASS  {t.__name__}")
                counts[0] += 1
            except Exception as exc:
                print(f"  FAIL  {t.__name__}: {exc}")
                counts[1] += 1

    anyio.run(_run_async)
    total = counts[0] + counts[1]
    print(f"\n{counts[0]}/{total} passed")
    sys.exit(0 if counts[1] == 0 else 1)
