from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class TokenBucketProtocol(Protocol):
    """Auto-inferred Protocol surface for `TokenBucket`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    async def try_acquire(self, tokens: float = 1.0) -> bool: ...
