from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class DeprecationReporterProtocol(Protocol):
    """Auto-inferred Protocol surface for `DeprecationReporter`.

    Generated by `engine.extraction.infer_protocol`; review and tighten
    annotations before promoting the primitive out of `_extracted/`.
    """

    def record(self, path: str, method: str) -> None: ...
    def get_count(self, path: str, method: str) -> int: ...
    def usage_report(self) -> list[dict[str, Any]]: ...
    def reset(self) -> None: ...
